### ISSUE TITLE
Command still gives player Item

### ISSUE THREAD

**Issue by LuluSupreme** [ConnorLinfoot/CratesPlus#100]
![thingy](https://cloud.githubusercontent.com/assets/10571625/13244653/ba1c84e0-d9bc-11e5-8d83-1dcaab7d7c83.png)

When I try to have the server execute a command for a crate it still gives the player the item. I am using the current version of the plugin 3.1.2

**Comment by ConnorLinfoot** [comment]
Issue is fixed in the upcoming 4.0.

**Comment by LuluSupreme** [comment]
when will 4.0 be available?
