### ISSUE TITLE
CratesPlus Issue - Players Can Take Items From Preview GUI

### ISSUE THREAD

**Issue by TurtlesBeOP** [ConnorLinfoot/CratesPlus#102]
When players view the preview GUI on a crate, they can take items out. Please tell me a way to fix this or send me a version of the plugin without the preview GUI please!

**Comment by TurtlesBeOP** [comment]
What was wrong wth this? You only flagged it as a duplicate? Or invalid?

**Comment by ConnorLinfoot** [comment]
This issue has been fixed, it was caused by using CraftBukkit.

You can now use version 3.1.6 or above and it should be fixed; https://www.spigotmc.org/resources/cratesplus-custom-crates-1-8-1-9-free.5018/download?version=72888
