### ISSUE TITLE
Lots of  Suggestion  & 1 Problem

### ISSUE THREAD

**Issue by Josh9722** [ConnorLinfoot/CratesPlus#103]
Would like to say very nice plugin, very helpful and the in-game setup is helpful however you should make it so you can get multiple rewards from the 1 option (I think you can already, if so how plz) and the problem is that the hologram doesn't have a colour, Cheers, Thx, Bai, Goodplugin, Help Needed. ~Josh

**Comment by Josh9722** [comment]
Also Written Books Wont Stay In Format Or My Damaged Pickaxe's

**Comment by Josh9722** [comment]
Maybe A Buy Sign For Keys?

**Comment by Josh9722** [comment]
Win Sounds And Effects when a chest is opened? effects meaning partials. Sorry if you already have these, ill be your ideas man lel

**Comment by Josh9722** [comment]
What I havent seen in a crates plugin would be a option to add a random enchant per tools, eg. You put in a diamond pickaxe and if the feature is enabled for that item then it would apply a random enchantment (maybe customisable)

**Comment by Josh9722** [comment]
Also if a player makes a error in the config you should make it not completely delete itself and just rename the file to broken-config#1 and then #2 and so on :)

**Comment by Josh9722** [comment]
Also I dont know if this is possible already but maybe like multiple items inside the same thing (be able to do in /Crates settings would be good as well) and maybe edit chances in there as well?

**Comment by Josh9722** [comment]
random money amount option? without having to specify all possible options just like 1-100 and it will give any inbetween? can also give money with other rewards? idk ;p

**Comment by jon4397** [comment]
Perhaps also the ability to run commands as a winning, and as another option, maybe multiple commands separated by a ";". This, of course, would really only be doable in the config file.

**Comment by ConnorLinfoot** [comment]
Stop adding multiple posts to one issue, just edit your original. Your last comment is pointless as you can run command as a win and have multiple commands also. Please use the plugin before submitting feature requests.

**Comment by jon4397** [comment]
Perhaps you should be more clear in the descriptions then...

**Comment by Josh9722** [comment]
Connor you said "Please use the plugin before submitting feature requests."

Well I do use the plugin and as jon has said, "Perhaps you should be more clear in the descriptions then..." exactly. Was just trying to help as much as I could..

**Comment by ConnorLinfoot** [comment]
There is information on the website about using commands or percentages. It states to view the example config file. If you viewed the example config for the reason it's there you'd know about things like commands.

**Comment by jon4397** [comment]
True, you would know if you viewed the config. But, so that you know, nobody will view the config unless they already started using it. That's the way people are. They won't know about the commands feature, because it doesn't state it in the descriptions. If you add it there though, I can guarantee you that more people will like and download it. 
If I had known about it, I wouldn't have switched to Crate Reloaded. I may switch back, because I don't like having to make my own colored holograms with custom plugins. That is one thing your plugin has above the other. :)
