### ISSUE TITLE
Issues w/ Lore

### ISSUE THREAD

**Issue by philip-ulrich** [ConnorLinfoot/CratesPlus#104]
Hello,

While using this program, I try to couple it with it's own keys and bank notes. The lore on each of these items is doubled on one and a duplicate item with no lore is also dispensed. 

You can reproduce this by sticking a vote key as a chest item. Please fix this. :)

**Comment by ConnorLinfoot** [comment]
Issue is fixed in 4.0, I may release a 3.1.6 with it fixed also depending on time frame for 4.0
