### ISSUE TITLE
Decimal Reward Chance

### ISSUE THREAD

**Issue by F0xyYT** [ConnorLinfoot/CratesPlus#105]
I Tried to put Percentage: 0.1 or Percentage: 0,1 but in-game it don't show anything :(
If there is another way tell me, i want to put a rank in-crates but with a extremely rare chance !
Halp!

**Comment by ConnorLinfoot** [comment]
Currently there isn't support for decimals with percentages, I'll try and look at this for V4.0 but no promise!

**Comment by ConnorLinfoot** [comment]
I've now added this to snapshot 15! If you guys can test it out that'd be great ;D

**Comment by CaptDarkStar** [comment]
This is absolutely amazing! I have just tested out this feature on my server. Seems to display correctly, and I didn't get any errors on load in console. I would assume that it is functioning properly based on decimal reward chance. Thank you so much for this feature! :dancer:
