### ISSUE TITLE
Percentages 

### ISSUE THREAD

**Issue by LuluSupreme** [ConnorLinfoot/CratesPlus#106]
If i put a percentage on one item and not on another then the second item will show up in the chest but I cant win it. Also would it be possible to add a system so you can have some items have a fairly high drop chance and some items have a fairly low drop chance (without have to have to totals add up to 100 percent)

**Comment by ConnorLinfoot** [comment]
That's how it's suppose to work, if your using percentages each item you want to work needs a percentage and it can't go over 100%
