### ISSUE TITLE
drag items while rolling. (still not working)

### ISSUE THREAD

**Issue by Bjezirds** [ConnorLinfoot/CratesPlus#107]
So basicly i don't know why but players can drag or click items out of the crates whilr rolling and thats just not good :( Is there anyway to fix/prevent this happening.

**Comment by ConnorLinfoot** [comment]
It's usually caused by specific plugins been installed or some config setting, try removing plugins and testing it.

**Comment by Bjezirds** [comment]
Alright i'll remove all plugins and install 1 by 1 then.

**Comment by Bjezirds** [comment]
So i just created a new server without any plugins and i put crate protection true in config still doesnt work?

**Comment by ConnorLinfoot** [comment]
Crate protection doesn't protect the crate's items been taken as that just shouldn't happen. What version of Spigot are you using?

**Comment by Bjezirds** [comment]
Im currently using Bukkit 1.8.8.

**Comment by ConnorLinfoot** [comment]
Have you tried with Spigot at all? I personally haven't tested this plugin in Bukkit and advertise it as a Spigot only plugin because of this.

**Comment by Bjezirds** [comment]
aah because this came up as bukkit plugin :/

**Comment by ConnorLinfoot** [comment]
I've found where the main issue is causing it to be incompatible with CraftBukkit, will update CratesPlus soon to fix it!

**Comment by ConnorLinfoot** [comment]
Try this version with Bukkit; https://www.spigotmc.org/resources/cratesplus-custom-crates-1-8-1-9-free.5018/download?version=72888

**Comment by Bjezirds** [comment]
Thanks
