### ISSUE TITLE
v4.0.0 - New crate placement does not show hologram.

### ISSUE THREAD

**Issue by CaptDarkStar** [ConnorLinfoot/CratesPlus#109]
This is a issue post as requested. In v4.0.0 Snapshot 8, when you place down a crate, it will not show the hologram name at all. This is what it shows in my logs when I place a crate:

http://pastebin.com/svyuTvir

**Comment by ConnorLinfoot** [comment]
See if this is fixed in Snapshot 9, couldn't re-produce but I may have found where the issue was.

**Comment by CaptDarkStar** [comment]
As of snapshot 9, this is now a corrected issue and works nicely :)
