### ISSUE TITLE
v4.0.0 - Players can still drop keys.

### ISSUE THREAD

**Issue by CaptDarkStar** [ConnorLinfoot/CratesPlus#110]
It is currently blocks that players can not place keys at all, however players are still able to drop the keys. This should be prevented to stop players from sharing/bartering the keys. An additional options to enable/disable this option would be good to for those servers that want to let players trade/barter keys.

**Comment by ConnorLinfoot** [comment]
It was never an intended feature to block key dropping but I like the idea. Will add it in the next snapshot for 4.0.

**Comment by ConnorLinfoot** [comment]
Feature added in Snapshot 9
