### ISSUE TITLE
Players cant use crates

### ISSUE THREAD

**Issue by sleepspark** [ConnorLinfoot/CratesPlus#111]
Hi, as OP i can use keys on crates, but when a player attempts to use it, nothing happens. It's like they don't have permission to use it for some reason.

**Comment by ConnorLinfoot** [comment]
There isn't a permission in the plugin for opening crates at this time. However this issue is most commonly caused with either spawn protection or world guard.

**Comment by sleepspark** [comment]
Thanks. I just literally saw someone post a previous issue a few months ago. Sorting it now. Thanks for the quick reply though and thanks for the awesome plugin! 10 / 10!
