### ISSUE TITLE
Only 4 rewards are working? Help!

### ISSUE THREAD

**Issue by Sikatsu** [ConnorLinfoot/CratesPlus#114]
@ConnorLinfoot I have an issue with the crates, this is my config: http://pastebin.com/QrCSXELe

But only 4 items are showing up: http://prntscr.com/abgpul

Error:

`05.03 12:57:14 [Server] ERROR Could not pass event BlockBreakEvent to CratesPlus v4.0.0-SNAPSHOT-9
05.03 12:57:14 [Server] INFO org.bukkit.event.EventException
05.03 12:57:14 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.jar:git-Spigot-b39373b-60f01ef]
05.03 12:57:14 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.jar:git-Spigot-b39373b-60f01ef]
05.03 12:57:14 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.jar:git-Spigot-b39373b-60f01ef]
05.03 12:57:14 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.jar:git-Spigot-b39373b-60f01ef]
05.03 12:57:14 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:292) [spigot-1.9.jar:git-Spigot-b39373b-60f01ef]
05.03 12:57:14 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:124) [spigot-1.9.jar:git-Spigot-b39373b-60f01ef]
05.03 12:57:14 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:796) [spigot-1.9.jar:git-Spigot-b39373b-60f01ef]
05.03 12:57:14 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot-1.9.jar:git-Spigot-b39373b-60f01ef]
05.03 12:57:14 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot-1.9.jar:git-Spigot-b39373b-60f01ef]
05.03 12:57:14 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-b39373b-60f01ef]
05.03 12:57:14 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
05.03 12:57:14 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
05.03 12:57:14 [Server] INFO at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-b39373b-60f01ef]
05.03 12:57:14 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.jar:git-Spigot-b39373b-60f01ef]
05.03 12:57:14 [Server] INFO at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-b39373b-60f01ef]
05.03 12:57:14 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-b39373b-60f01ef]
05.03 12:57:14 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-b39373b-60f01ef]
05.03 12:57:14 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
05.03 12:57:14 [Server] INFO Caused by: java.lang.NullPointerException
05.03 12:57:14 [Server] INFO at plus.crates.Listeners.BlockListeners.onBlockBreak(BlockListeners.java:263) ~[?:?]
05.03 12:57:14 [Server] INFO at sun.reflect.GeneratedMethodAccessor122.invoke(Unknown Source) ~[?:?]
05.03 12:57:14 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
05.03 12:57:14 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
05.03 12:57:14 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-b39373b-60f01ef]
05.03 12:57:14 [Server] INFO ... 17 more`

**Comment by ConnorLinfoot** [comment]
The error you posted is not related to the config file, that's not causing any issues (Although I will fix that)

The issue seems to be because you have 2 items with the ID of 5 which is causing it to break. Also a note, I noticed you're using ID's with "Item Type" that won't work. You have to use valid material values as found here https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

**Comment by ConnorLinfoot** [comment]
I've just "fixed" the config for you including updating the ID's to materials - http://pastebin.com/rS9XK27Z

That should work :)

**Comment by Sikatsu** [comment]
Ah, thanks for the explanation! I found the ID 5 later on, that didn't fix it. 

It's working now! Seems indeed to be related to the materials, thanks a lot!
