### ISSUE TITLE
Snapshot 1.9 error

### ISSUE THREAD

**Issue by Sikatsu** [ConnorLinfoot/CratesPlus#115]
In the closed issue, there was an error about the break event, this is one about the Interact event.

`05.03 13:30:45 [Server] ERROR Could not pass event PlayerInteractEvent to CratesPlus v4.0.0-SNAPSHOT-9
05.03 13:30:45 [Server] INFO org.bukkit.event.EventException
05.03 13:30:45 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.jar:git-Spigot-b39373b-60f01ef]
05.03 13:30:45 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.jar:git-Spigot-b39373b-60f01ef]
05.03 13:30:45 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.jar:git-Spigot-b39373b-60f01ef]
05.03 13:30:45 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.jar:git-Spigot-b39373b-60f01ef]
05.03 13:30:45 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:227) [spigot-1.9.jar:git-Spigot-b39373b-60f01ef]
05.03 13:30:45 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:482) [spigot-1.9.jar:git-Spigot-b39373b-60f01ef]
05.03 13:30:45 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:852) [spigot-1.9.jar:git-Spigot-b39373b-60f01ef]
05.03 13:30:45 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:55) [spigot-1.9.jar:git-Spigot-b39373b-60f01ef]
05.03 13:30:45 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:11) [spigot-1.9.jar:git-Spigot-b39373b-60f01ef]
05.03 13:30:45 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-b39373b-60f01ef]
05.03 13:30:45 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
05.03 13:30:45 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
05.03 13:30:45 [Server] INFO at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-b39373b-60f01ef]
05.03 13:30:45 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.jar:git-Spigot-b39373b-60f01ef]
05.03 13:30:45 [Server] INFO at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-b39373b-60f01ef]
05.03 13:30:45 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-b39373b-60f01ef]
05.03 13:30:45 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-b39373b-60f01ef]
05.03 13:30:45 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
05.03 13:30:45 [Server] INFO Caused by: java.lang.IllegalArgumentException: bound must be positive
05.03 13:30:45 [Server] INFO at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_66]
05.03 13:30:45 [Server] INFO at plus.crates.Events.CrateOpenEvent.doBetaGUI(CrateOpenEvent.java:105) ~[?:?]
05.03 13:30:45 [Server] INFO at plus.crates.Events.CrateOpenEvent.doEvent(CrateOpenEvent.java:49) ~[?:?]
05.03 13:30:45 [Server] INFO at plus.crates.Listeners.PlayerInteract.onPlayerInteract(PlayerInteract.java:99) ~[?:?]
05.03 13:30:45 [Server] INFO at sun.reflect.GeneratedMethodAccessor122.invoke(Unknown Source) ~[?:?]
05.03 13:30:45 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
05.03 13:30:45 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
05.03 13:30:45 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-b39373b-60f01ef]
05.03 13:30:45 [Server] INFO ... 17 more`

**Comment by ConnorLinfoot** [comment]
Is this while using the config file I posted earlier? Can't replicate issue with standard config.

**Comment by CaptDarkStar** [comment]
This is the same error log he posted with his messed up config. My guess is the invalid item type threw the error as it couldn't read the rest fo the config file.

**Comment by Sikatsu** [comment]
This error happened after the config fix I guess, maybe I forgot something, seems not to occur anymore today.
