### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Sikatsu** [ConnorLinfoot/CratesPlus#118]
I use CratesPlus for my votes (Probably like many others). However, when you vote with a full inventory the key gets lost. In VoteRoulette there is a way if you vote offline to claim your rewards when you come online.

I'd like to see an option if you vote with a full inventory the keys get stored and when you use /crate claim a GUI will popup to claim any of your keys. Is this possible?

And lol, is this normal: http://prnt.sc/abtqaa

**Comment by ConnorLinfoot** [comment]
Seems like something that would be possible but would maybe take a little bit of work, I'll have a look what I can do if I have the time as I do like the idea.

As for the key on your head I'm guessing you did /hat or something? xD

**Comment by Sikatsu** [comment]
Would be a really nice feature, in the future :)

No lol, I voted and somehow all the keys went in the hat slot.. it was completely random!

**Comment by ConnorLinfoot** [comment]
Just quietly pushing this back again ;) I am going to try my best to get this added in 4.2 :P

**Comment by Sikatsu** [comment]
SHIT. Well, okay ! :)

**Comment by ConnorLinfoot** [comment]
I've added this in 4.2 snapshot 2, give it a try for me and see if you find any bugs :)
