### ISSUE TITLE
WorldGuard blocking use of chests

### ISSUE THREAD

**Issue by ThisInsider** [ConnorLinfoot/CratesPlus#119]
On my server I am using this plugin, and when a chest is placed within a worldguard region, it doesn't allow the key to be used. It doesn't say anything or does anything. Its like right clicking the ground with a stick. On the region flags chest-access, use, and interact are allowed, and still it doesn't work.

EDIT: It works only when you have op. Even for admins with all permissions it doesn't allow the crates to be open.

**Comment by CaptDarkStar** [comment]
What version are you using? I have never run into this issue and I have mine in a world guard region.

**Comment by ConnorLinfoot** [comment]
This will be caused by configuration on your server (as it seems you know?) I haven't personally used WorldGuard so I personally can't advise.
