### ISSUE TITLE
Ability to change chest type

### ISSUE THREAD

**Issue by CaptDarkStar** [ConnorLinfoot/CratesPlus#127]
Instead of having only the regular chest, perhaps let us be able to change it to any block type. I am not sure how easy this can be done, but would be a nice change. Would also help with not being able to place reward chests directly next to each other and having them combine together into a large chest.

**Comment by ConnorLinfoot** [comment]
Different block types was fully added in v4.0 snapshot 8 and should work. Any issues let me know.

**Comment by CaptDarkStar** [comment]
I only see settings to change the key item, nothing for the actual crate. Is there a setting I should be adding for this or something I am missing?? My current config: http://pastebin.com/3vFDbdwf

**Comment by ConnorLinfoot** [comment]
Best place to usually check is in the example config here; https://github.com/ConnorLinfoot/CratesPlus/blob/master/src/main/resources/example_config.yml I will probably add it by default in the future.

You need to add the Block option and use a valid material type https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
