### ISSUE TITLE
Prevent players from putting keys in chests

### ISSUE THREAD

**Issue by CaptDarkStar** [ConnorLinfoot/CratesPlus#128]
This goes along with the option to prevent players from dropping or placing keys. This will keep the keys from being able to be traded/sold among players should you choose to disallow that option.

**Comment by CaptDarkStar** [comment]
Actually, putting other half in separate post.

**Comment by jtrent238** [comment]
need to put in chest, maybe a config option

**Comment by ConnorLinfoot** [comment]
"Disable Key Swapping" now disables dropping of keys including on death and blocks putting them in chests/other inventories.
