### ISSUE TITLE
Prevent key dropping on death.

### ISSUE THREAD

**Issue by CaptDarkStar** [ConnorLinfoot/CratesPlus#129]
Is there a way in general way to keep the key item from dropping on death? Doesn't need a config option, or a message really. Just another thought I had an epiphany about.

**Comment by ConnorLinfoot** [comment]
When they die would you prefer the key to be given on respawn or just removed completely?

**Comment by ConnorLinfoot** [comment]
"Disable Key Swapping" now disables dropping of keys including on death and blocks putting them in chests/other inventories.
