### ISSUE TITLE
Snapshot 15 error exception

### ISSUE THREAD

**Issue by Sikatsu** [ConnorLinfoot/CratesPlus#130]
Using the latest version I'm recieving errors.

`11.03 16:19:58 [Server] WARN Exception in thread "Craft Scheduler Thread - 48" 
11.03 16:19:58 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin CratesPlus v4.0.0-SNAPSHOT-15 generated an exception while executing task 109653
11.03 16:19:58 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
11.03 16:19:58 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
11.03 16:19:58 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
11.03 16:19:58 [Server] INFO at java.lang.Thread.run(Thread.java:745)
11.03 16:19:58 [Server] INFO Caused by: java.lang.NullPointerException
11.03 16:19:58 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaItem.applyEnchantments(CraftMetaItem.java:613)
11.03 16:19:58 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaItem.applyToItem(CraftMetaItem.java:571)
11.03 16:19:58 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftItemStack.setItemMeta(CraftItemStack.java:411)
11.03 16:19:58 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftItemStack.setItemMeta(CraftItemStack.java:390)
11.03 16:19:58 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftItemStack.<init>(CraftItemStack.java:111)
11.03 16:19:58 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftItemStack.<init>(CraftItemStack.java:115)
11.03 16:19:58 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftItemStack.<init>(CraftItemStack.java:104)
11.03 16:19:58 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftItemStack.asCraftCopy(CraftItemStack.java:83)
11.03 16:19:58 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftInventory.firstPartial(CraftInventory.java:260)
11.03 16:19:58 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftInventory.addItem(CraftInventory.java:287)
11.03 16:19:58 [Server] INFO at plus.crates.Winning.runWin(Winning.java:195)
11.03 16:19:58 [Server] INFO at plus.crates.Events.CrateOpenEvent$1.run(CrateOpenEvent.java:160)
11.03 16:19:58 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
11.03 16:19:58 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
11.03 16:19:58 [Server] INFO ... 3 more`

**Comment by ConnorLinfoot** [comment]
Config file?

**Comment by Sikatsu** [comment]
If this again is an issue with my config I really have a ghost on my PC, didn't change a thing within the config.

I believe my admin made one special crate with the in-game editor, but that shouldn't cause strange things in the config.

Config: http://pastebin.com/PcR1tSue

**Comment by ConnorLinfoot** [comment]
Does this happen with any specific crate or just all of them?

**Comment by Sikatsu** [comment]
I only use one. :)

Op vr 11 mrt. 2016 17:55 schreef Connor Linfoot <notifications@github.com>:

**Comment by CaptDarkStar** [comment]
I can confirm that this is an issue with your config file. I am not sure exactly where, but when I use your config on my dev server it works perfectly fine. When I use my config, it works perfectly.

**Comment by Sikatsu** [comment]
But it's really weird. I only used the in-game editor and suddenly it broke?

**Comment by Sikatsu** [comment]
Tried to remove the special crate again because the normal crate was built within the in-game editor on an earlier snapshot, but it's still broken: http://pastebin.com/zWvUQgkv

**Comment by Sikatsu** [comment]
It seems to happen when I close the GUI after winning and when I want to use the in-game editor.

**Comment by CaptDarkStar** [comment]
@Sikatsu - Click reference above for answer on this.
