### ISSUE TITLE
Show message in worldguard region?

### ISSUE THREAD

**Issue by cj89898** [ConnorLinfoot/CratesPlus#132]
It isn't showing my players any message on right click when in a worldguard region.

**Comment by CaptDarkStar** [comment]
This is a setting with world guard, not anything to do with this plugin itself. I have had no issues in world guard regions. I would suggest making sure players can use chests when placing in a world guard region.

**Comment by cj89898** [comment]
Nevermind, completely my fault! Spawn protection :P
