### ISSUE TITLE
Percentages ?

### ISSUE THREAD

**Issue by Meaxx023** [ConnorLinfoot/CratesPlus#133]
When i fill in the percentages for all the items in the crate it just works for like 3-5 items and all the other items just disappear when i look in the chest ? how can i fix this ?

**Comment by CaptDarkStar** [comment]
Are your percent options equaling exactly 100% for all the items together? This is usually a common error that will cause problems with your crate. That and sometimes a typo/spacing issue in the config. Would be really helpful if you showed a copy of your config.
