### ISSUE TITLE
Adding Commands To The New Update

### ISSUE THREAD

**Issue by PvpLegendz** [ConnorLinfoot/CratesPlus#135]

**Comment by PvpLegendz** [comment]
As the new update came out, i had no idea how to add commands. I have tried many methods, can someone send me their config, with a command added like 

      '1':
        Type: ITEM
        Item Type: PAPER
        COMMAND: /eco give %player% 1000
        Item Data: 0
        Name: §2Helmet
        Amount: 1
        Enchantments:
        Lore: []

I Don't know where the "COMMAND" Has to be placed, so can someone help me further?

**Comment by CaptDarkStar** [comment]
This is because you are trying to put a command as an item. This causes it to break as you need to label it as a command not an item. See item 3 in this example config for v3.1: http://pastebin.com/grPRrSXp

Using the 4.0 dev build? See this example config: https://github.com/ConnorLinfoot/CratesPlus/blob/master/src/main/resources/example_config.yml

**Comment by PvpLegendz** [comment]
A big thanks to you=)

**Comment by PvpLegendz** [comment]
I Tried to configurate it and i also tried to paste this in

 Example:
    Knockback: 0.5
    Broadcast: false
    Firework: false
    Color: GREEN
    Winnings:
      '1':
        Type: ITEM
        Item Type: IRON_SWORD
        Item Data: 0
        Percentage: 50
        Name: '&6&lSword of Destiny'
        Amount: 1
        Enchantments:
       - DAMAGE_ALL-3
        Lore:
       - "Testing123"
      '2':
        Type: ITEM
        Item Type: DIAMOND_SWORD
        Name: NONE
        Item Data: 0
        Percentage: 25
        Amount: 1
        Enchantments:
       - DAMAGE_ALL-5
        - DURABILITY-3
        - FIRE_ASPECT-2
      '3':
        Type: COMMAND
        Item Type: MOB_SPAWNER
        Percentage: 25
        Commands:
       - 'spawner give %name% spider'
        - 'say %name% opened a crate'
        Name: '&e&lSpider Spawner'
        Item Data: 0
        Amount: 1
        Enchantments:
       - DAMAGE_ALL-5
        - DURABILITY-3
        - FIRE_ASPECT-2

But it is still not working :/

**Comment by CaptDarkStar** [comment]
I would recommend using pastebin.com to show us your config file. My first guess would be a spacing issue, especially if you copy/pasted right from the v3.1 example config.
