### ISSUE TITLE
Crates not being removed.

### ISSUE THREAD

**Issue by CaptDarkStar** [ConnorLinfoot/CratesPlus#137]
So I have just discovered a rather interesting problem. When I place a crate and everything, it works perfectly. However when I remove a crate it appears to work fine until I place a different block. I was relocated some of my crates when I found that the plugin still holds the location of removed crates. Basically when I place a crate, remove it, and then place any block, that block then acts like it was the crate I just removed from that spot. Completely ignores the data.yml file as well as it shows "votecrate: []" yet still has 3 different ghost locations that I cant get rid of.

**Comment by ConnorLinfoot** [comment]
Seems like I'm not removing the meta data on block break, rebooting should fix it for now but I will sort it today.

**Comment by ConnorLinfoot** [comment]
Should be fixed in Snapshot 18, let me know if it occurs again.

**Comment by CaptDarkStar** [comment]
Fix confirmed. Thanks so much for the really fast updates and fixes! :)
