### ISSUE TITLE
The chest is invisible and wont delete!

### ISSUE THREAD

**Issue by zumiezdude132** [ConnorLinfoot/CratesPlus#14]
I placed a chest at my spawn but now it wont delete. I tried placcing it but i didnt have .f admin on so it put the chest there but it isnt there. I cant delete it i have tried everything!
![2015-07-14_01 23 07](https://cloud.githubusercontent.com/assets/13327746/8667588/4590b9d4-29c7-11e5-89f1-d9e6606ee571.png)

**Comment by oDabz** [comment]
I have the same issue if you got any help on it please message me back?!

**Comment by ConnorLinfoot** [comment]
You can get rid of them using the following command:

/entitydata @e[type=ArmorStand,r3] {Invisible:0}

After running that you will be able to see the armor stand and remove it by punching it. Make sure you are standing next to the hologram you wish to remove.
