### ISSUE TITLE
1.9 crates aren't working 3.1.7 on Spigot 1.9

### ISSUE THREAD

**Issue by 151baccardi** [ConnorLinfoot/CratesPlus#141]
Could not pass event PlayerInteractEvent to CratesPlus v3.1.7

**Comment by ConnorLinfoot** [comment]
Please post more information and use paste bin for errors.

"Issues must have information about your server; Please provide plugin list, /version output, and any other server configuration you may have changed."

**Comment by 151baccardi** [comment]
nothing has changed. Runninglatest build using build-tools of spigot 1.9. Worked fine with 1.8 and I paid real money if I remember correctly!

**Comment by ConnorLinfoot** [comment]
Paid real money?

As said above please post more information.
