### ISSUE TITLE
Holograms remaining, crates invisible

### ISSUE THREAD

**Issue by lordoftime4** [ConnorLinfoot/CratesPlus#142]
Hi,
First i'd like to say that This plugin is really awesome and I'm really thankful for your hard work.

I updated from the last stable build to snapshot 19, And it seemed to work fine but then I noticed the new colors feature. So I changed the color of one of my crates, and both of my crates have become invisible. I tried deleting one of the crates in the settings, but the hologram and unbreakable-invisible chest remained. If there is any other information I can provide, let me know.
Config (before updating) http://pastebin.com/52nSWKxK
Config (after deleting a crate) http://pastebin.com/9EKFseSZ
Config (Updated, before deleting crate) http://pastebin.com/Ref49Qh5

Thank you

![2016-03-16_10 11 49](https://cloud.githubusercontent.com/assets/17883936/13819609/b987cb3e-eb5f-11e5-8378-62394b2a7717.png)

**Comment by lordoftime4** [comment]
Upon further inspection, it appears that the chest is in fact gone, just the armorstands remain. I used a command to make the stand visible and was able to remove them. So, I no longer have a problem, but maybe this will help you out with your development. Thank you again for your hard work!
-lordoftime4

**Comment by ConnorLinfoot** [comment]
This is probably due to many major changes in 4.0 to how crates are handled, I haven't tested the conversion in a while but it's something that will be improved upon/tested this week :)

**Comment by lordoftime4** [comment]
Thank you! I've also run in to some problems with using /crate settings. As in, it tends to delete/change a lot of the data ive written in to the config. Editing crates via the config seems to work perfectly. So just fyi haha.

**Comment by ConnorLinfoot** [comment]
Yeah the in-game editor should really only be used if you've never edited crates in the config just because of how it handles saving of the in-game editor :P
