### ISSUE TITLE
Percents change?

### ISSUE THREAD

**Issue by ryandw11** [ConnorLinfoot/CratesPlus#143]
Maybe instead of making crates percents to add up to 100%. You could make it where it dosn't have to. It's kinda annoying as I want to put in many items in my crates. (Currently have 10). It would be nice as I don't want all things to have a equal chance. I hope this gets added!

**Comment by ConnorLinfoot** [comment]
Due to the way the percentages are being handled this will not be implemented any time soon. Decimal support has already been added.
