### ISSUE TITLE
Cannot stop crate

### ISSUE THREAD

**Issue by lordoftime4** [ConnorLinfoot/CratesPlus#144]
Hi,
No matter what I do, I cannot get the crate to stop running the /give commands that i put in the crate. After i used the key on it, it ran through the animation, gave me a spawner (/silkspawners give %name% <spawnername>) It would not allow me to exit the colorful roulette gui until i quit the game. I've relogged, deleted the crate, removed OP, removed creative, and my inventory continues to fill with spawners. The only thing that stops it is if i have no open spaces in my inventory. And then, when i empty it, the spawners start coming again. Re-starting the server did stop the spawners from coming, after I had deleted this crate from the config.
Config: http://pastebin.com/41RLRmqX
Section of console log: http://pastebin.com/gJjWm6em

![2016-03-16_18 01 18](https://cloud.githubusercontent.com/assets/17883936/13832378/51f16dda-eba1-11e5-8a18-b56b501144c7.png)
![2016-03-16_17 37 10](https://cloud.githubusercontent.com/assets/17883936/13832173/61261c44-eb9f-11e5-870a-07f2e3958f06.png)
![2016-03-16_17 37 24](https://cloud.githubusercontent.com/assets/17883936/13832174/6128066c-eb9f-11e5-991c-137477aa106e.png)
![2016-03-16_17 37 38](https://cloud.githubusercontent.com/assets/17883936/13832172/6123fdc4-eb9f-11e5-8422-5eab7c66a854.png)

**Comment by ConnorLinfoot** [comment]
This error is because of the firework I believe, try disabling that! Will fix in the next snapshot!

**Comment by ConnorLinfoot** [comment]
Try snapshot 22 please, should be fixed.
