### ISSUE TITLE
"COMMAND" Type Broken?

### ISSUE THREAD

**Issue by CloudedKiller** [ConnorLinfoot/CratesPlus#145]
I tried using the example in your pastebin in a crate, but doesnt work. Looked like this:

  command:
    Knockback: 0.0
    Broadcast: false
    Firework: false
    Color: WHITE
    Winnings:
      '1':
        Type: COMMAND
        Item Type: MOB_SPAWNER
        Percentage: 25
        Commands:
       - 'spawner give %name% spider'
        - 'say %name% opened a crate'
        Name: '&e&lSpider Spawner'
        Item Data: 0
        Amount: 1
        Enchantments:
       - DAMAGE_ALL-5
        - DURABILITY-3
        - FIRE_ASPECT-2

Did I do something wrong, or is "command" just not a thing? Thanks beforehand.

**Comment by CaptDarkStar** [comment]
Would help if you posted this on pastebin.com and gave us the link. This way we can see the spacing and such as spacing is very important in yaml files. Have you tried running your config through a yaml parser? (http://yaml-online-parser.appspot.com/)
