### ISSUE TITLE
Click leaves chest

### ISSUE THREAD

**Issue by Noodles0809** [ConnorLinfoot/CratesPlus#148]
When you use a key it opens the chest and starts going through the items

When i leftclick to see what happend it kicked me out of the chest 

I tryed agian if you click at all when you are going though the spin 
it kicks you out

Is this a Bug or does this just happen

V4.0.0
Minecraft 1.9

**Comment by ConnorLinfoot** [comment]
Just some old code from before how the GUI's was handled, not exactly a bug as it doesn't cause any issues. Will change it in a future update.
