### ISSUE TITLE
Holograms not working? I tried /entitydata @e[type=ArmorStand,r3] {Invisible:0} Did not Work

### ISSUE THREAD

**Issue by AwexDoesThings** [ConnorLinfoot/CratesPlus#149]
i cannot remove some holograms 2 of them now I tried /entitydata @e[type=ArmorStand,r3] {Invisible:0} and it did not work?

**Comment by ConnorLinfoot** [comment]
Invalid issue, please follow issue instructions. https://github.com/ConnorLinfoot/CratesPlus
