### ISSUE TITLE
Invisible Crate

### ISSUE THREAD

**Issue by oDabz** [ConnorLinfoot/CratesPlus#15]
I placed down 3 chest and went in console to change color. Reloaded server. Then i couldnt edit those chest. They were deleted and i cant place blocks where the chest used to be.All it shows is a hologram of where the chest used to be. Same as zummiezdude123. If you could please get back to me asap that would be great.

**Comment by ConnorLinfoot** [comment]
You can get rid of them using the following command:

/entitydata @e[type=ArmorStand,r3] {Invisible:0}

After running that you will be able to see the armor stand and remove it by punching it. Make sure you are standing next to the hologram you wish to remove.
