### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by xDEADSNIPERx11** [ConnorLinfoot/CratesPlus#153]
So I love this plugin except for one thing. I want to make in the crate you have a chance to win, 5 diamonds, 15 diamonds, and 20 diamonds. But the second I close the settings GUI it stacks all the items into one big winning. Is there a way you could make that possible? If so that would be great!

**Comment by CaptDarkStar** [comment]
This is already completely possible as seen here: https://gyazo.com/fbc704f8314e84b0fd9b43cc90caa6e9

You have to edit it in via the config file. The in game editor is not designed to moderate everything, and hand writing your config is preferred. The in-game option is designed mainly for those without access to the config file to make some quick adjustments.
