### ISSUE TITLE
Holograms Disappearing

### ISSUE THREAD

**Issue by xDEADSNIPERx11** [ConnorLinfoot/CratesPlus#154]
This is a new issue because it never happened before, when ever clearlagg runs it deletes the armor stands for the holograms on the crates. It's weird because our clearlagg doesn't even effect armor stands. Also some of the ones from before I updated to the newer version are glitched and still there even after the crate is gone and I can't break them at all.

**Comment by xDEADSNIPERx11** [comment]
I have and update, it's not clearlagg apparently, they are just disappearing, i disabled clearlagg and they are just disappearing.

**Comment by CaptDarkStar** [comment]
With regards to your holograms remaining after your crates are removed, please see this issue resolution: https://github.com/ConnorLinfoot/CratesPlus/issues/16

As for the disappearing holograms, what version are you using? Depending on your version, there is a data.yml file in the folder. I would recommend deleting that and then replace all of your crates. That should solve the issue.

**Comment by xDEADSNIPERx11** [comment]
I am running the newest version that was released today, 4.0.0 I think it is. I will give what you suggested a shot for them staying.

**Comment by xDEADSNIPERx11** [comment]
I forgot to reply here sorry. The solution to get rid of the glitched ones worked. but I still am having the issues where the holograms for new ones are just disappearing.

**Comment by ConnorLinfoot** [comment]
Have you tried removing other plugins on your server? Also what version of Spigot are you using?

**Comment by xDEADSNIPERx11** [comment]
We are running spigot 1.9, latest release. I would try that but the issue didn't start until we updated the plugin, and we didn't add or remove any other plugins at the time nor change the configs. So it's in my professional opinion that it was caused by updating your plugin.

**Comment by xDEADSNIPERx11** [comment]
So I was in my spawn, the holograms still weren't there, flew away, came back and they where there. So i talked to some players, and some of them can see it some times, other times they can't.

**Comment by ConnorLinfoot** [comment]
"professional opinion" - Sorry that made me laugh a little.

The plugin has completely changed how it handles the holograms, meaning the new method could be getting altered by other plugins. Just because you've updated a plugin and an issue happens doesn't mean it's always that plugins fault.

**Comment by xDEADSNIPERx11** [comment]
Laugh all you want, not my problem. I tried disabling any and all plugins on my server that I personally believe could have any effect on the armor stands, and had no luck what so ever.
