### ISSUE TITLE
Bypassing the rewards

### ISSUE THREAD

**Issue by Meowzard** [ConnorLinfoot/CratesPlus#155]
I set up my config correctly, but when i open the preview of the crate i can only see few things listed.. other items that i configured the same way as those wich work don't show up!

**Comment by CaptDarkStar** [comment]
Can you post a copy of your config via pastebin.com? Are you using the proper bukkit item names and not the minecraft names? Are there any errors in console? If you are using precentages, do they all add up to exactly 100% ?

**Comment by Meowzard** [comment]
I allready fixed it , the percentages was the problem! :) thanks anyways !
