### ISSUE TITLE
Crate commands without items

### ISSUE THREAD

**Issue by brld** [ConnorLinfoot/CratesPlus#156]
Hey there,

Is it possible to run a command when a prize is won (i.e., have it do 'eco give %name% ' without it actually give the player the item that it is displayed as). Currently I have it as a golden ingot as the display item for the GUI, but I want it to have the player win but the gold ingot is never given. Setting amount to 0 and even removing it completely does not work. Any ideas?

Thanks!

**Comment by CaptDarkStar** [comment]
Follow the example config here: https://github.com/ConnorLinfoot/CratesPlus/blob/master/src/main/resources/example_config.yml

**Comment by brld** [comment]
That only shows how to do it with giving the spawner (i.e. it is still giving an item).

**Comment by Meowzard** [comment]
If you are running the old version below 4.0.0 that is an issue.. atleast it was like that for me

**Comment by brld** [comment]
Alright... assuming that I download the newest version now, how do I run a command without giving an item?

**Comment by Meowzard** [comment]
Just run a command and it shouldnt give you the items... (says in the bugfix nodes)
