### ISSUE TITLE
Not working - I cant figure out why!

### ISSUE THREAD

**Issue by MrP4uli** [ConnorLinfoot/CratesPlus#157]
For some reason whenever I place my config.yml file into the plugins folder for CratesPlus, the plugin stops working. When I type in any /crate command nothing comes up. Ive attached the config file, can someone help me find the issue here please?

[config.txt](https://github.com/ConnorLinfoot/CratesPlus/files/185154/config.txt)

**Comment by MrP4uli** [comment]
I just added all of the percentages to 100, but its still not working, here is my config now:
http://pastebin.com/GNPZ2MHy

**Comment by ConnorLinfoot** [comment]
Running it through a YAML parser (http://yaml-online-parser.appspot.com/) there is some issues in your config file.

Looks like your using ` instead of ' for quite a few of the lines.
