### ISSUE TITLE
Error occurred while enabling CratesPlus v4.0.0

### ISSUE THREAD

**Issue by morsay** [ConnorLinfoot/CratesPlus#158]
`[16:58:19] [Server thread/ERROR]: Error occurred while enabling CratesPlus v4.0.0 (Is it up to date?) java.lang.NullPointerException at org.bukkit.Location.getBlock(Location.java:87) ~[spigotmc-1.9-R0.1.jar:git-Spigot-f04e043-c91d092] at plus.crates.CratesPlus.loadMetaData(CratesPlus.java:541) ~[?:?] at plus.crates.CratesPlus.onEnable(CratesPlus.java:136) ~[?:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigotmc-1.9-R0.1.jar:git-Spigot-f04e043-c91d092] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigotmc-1.9-R0.1.jar:git-Spigot-f04e043-c91d092] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigotmc-1.9-R0.1.jar:git-Spigot-f04e043-c91d092] at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigotmc-1.9-R0.1.jar:git-Spigot-f04e043-c91d092] at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigotmc-1.9-R0.1.jar:git-Spigot-f04e043-c91d092] at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411) [spigotmc-1.9-R0.1.jar:git-Spigot-f04e043-c91d092] at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376) [spigotmc-1.9-R0.1.jar:git-Spigot-f04e043-c91d092] at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [spigotmc-1.9-R0.1.jar:git-Spigot-f04e043-c91d092] at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) [spigotmc-1.9-R0.1.jar:git-Spigot-f04e043-c91d092] at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigotmc-1.9-R0.1.jar:git-Spigot-f04e043-c91d092] at java.lang.Thread.run(Unknown Source) [?:1.7.0_80]`

Im using spigot 1.9, the plugin work but when i restart my server all crate are removed from the world.

Thanks for ur help

**Comment by morsay** [comment]
I removed then reinstalled the plugin and no error, but the error comeback when i place a crate .

**Comment by ConnorLinfoot** [comment]
Remove your data.yml file and see if the issue persists, you'll need to place any crates again.
