### ISSUE TITLE
Holograms glitched when removing chests.

### ISSUE THREAD

**Issue by daniel67423** [ConnorLinfoot/CratesPlus#16]
When i removed the chests that i created, the holograms glitched and will not go away.
<img width="930" alt="untitled" src="https://cloud.githubusercontent.com/assets/13406804/8767075/e0e6e078-2e47-11e5-948e-81369556e194.png">

**Comment by ConnorLinfoot** [comment]
You can get rid of them using the following command:

/entitydata @e[type=ArmorStand,r3] {Invisible:0}

After running that you will be able to see the armor stand and remove it by punching it. Make sure you are standing next to the hologram you wish to remove.

**Comment by ItsWulff** [comment]
Well i dont know why but for some reason non ops cant use my Crates and im pretty sure its a plugin thats blocking it and i dont know which plugin it could be help please? :D
Plugins: Vault, Buycraft, GAListener, EssentialsSpawn, EssentialsProtect, EssentialsChat, Essentials, Group Manager, ScoreboardStats, SilkSpawners, CratesPlus(3.1.2), WorldBorder, CombatLog, ColoredTags, Citizens, Votifier, WorldEdit & WorldGuard

**Comment by RazihelYT** [comment]
The crates hologram is still where I deleted my crates. None of the commands provided on this github page have worked and I demand a fix for this in 1.9.

**Comment by justindancefdsfs** [comment]
i do have the bugg and that command dont work by me

**Comment by mitchyb99** [comment]
When i did /entitydata @e[type=ArmorStand,r3] {Invisible:0}, it deleted all my holograms. How do i get it back?

**Comment by mitchyb99** [comment]
Im rly mad this happend  and would like a responses ASAP!

**Comment by XxMrWolfxX** [comment]
it did not work for me?
