### ISSUE TITLE
Plugin Doesn't work after I changed some names

### ISSUE THREAD

**Issue by amazingbeans** [ConnorLinfoot/CratesPlus#160]
I changed the color of the crates, the name/type of the key, removed the second and third lines of the hologram, set fireworks to appear when you open the crates, set a broadcast message on one of them, and added lore and changed the name of one reward item. Everything I changed fit exactly how it should work, but it doesn't work. Please help!!

**Comment by ConnorLinfoot** [comment]
As stated please post your config, Bukkit/Spigot version, CratesPlus version and console log.
