### ISSUE TITLE
Crates placed on the ground gets chests on reload/restart

### ISSUE THREAD

**Issue by olesien** [ConnorLinfoot/CratesPlus#161]
Hello!
So first off, I want to tell you what a great plugin you have made! It does exactly everything that I want it to.
Now to the a bit annoying issue:
Whenever I restart/reload, the chest & it's hologram disappears.
So let me give you some information:
Plugins:
http://pastebin.com/D8wK4jS6
Config & data.yml:
http://pastebin.com/4Y4wQupg
Error code:
- (there is none)
Server version:
Spigot 1.9
Thanks

**Comment by brld** [comment]
Don't ever use /reload! It is no longer supported and causes tons of bugs and problems. Always /stop and start your server again.

**Comment by olesien** [comment]
I know, but first I just restarted, happened the same thing.. Btw could you read through the config and see what's making the plugin unable to load the data from it? Cuz now it doesn't register the ''Voting'' crate

**Comment by olesien** [comment]
Edit:
I have fixed so that the chests stll works upon restart, but the holograms keeps on disappearing.
Fix?

**Comment by ConnorLinfoot** [comment]
Have you tried removing other plugins and seeing if the issue still happens?

**Comment by olesien** [comment]
I just did that, and the same thing happens even though I don't have any other plugin installed - essentials.

**Comment by ItsWulff** [comment]
Same here no idea why it does remove the holograms when i restart

**Comment by ConnorLinfoot** [comment]
Please post your config, Bukkit/Spigot version, plugins list, CratesPlus version, configuration file, data file and console log.
