### ISSUE TITLE
Chance messages

### ISSUE THREAD

**Issue by elpedriyo** [ConnorLinfoot/CratesPlus#163]
could you please add an option to dissable the chance message: http://prntscr.com/akqbu2
Like you can see, it is a little bit confusing and in previous versions that messsages where not there

**Comment by ConnorLinfoot** [comment]
Chance messages have always been a part of the plugin, it may be added at a later date to hide them by an option.

**Comment by elpedriyo** [comment]
Would you accept a donation for adding this?
