### ISSUE TITLE
Holograms are displayed in all worlds

### ISSUE THREAD

**Issue by Sprunkas** [ConnorLinfoot/CratesPlus#164]
So as title says holograms are displayed in all worlds instead of one even when in other worlds there are no custom crates.
![2016-03-28_17 19 10](https://cloud.githubusercontent.com/assets/3625816/14079819/425bcaca-f509-11e5-8ea2-e0da03a6b3f3.png)

Using 4.0.0 version

**Comment by ConnorLinfoot** [comment]
As stated please post your config, Bukkit/Spigot version, CratesPlus version and console log.

**Comment by Sprunkas** [comment]
Newest spigot 1.9
config:
http://pastebin.com/4PRnbWqx

As mentioned 4.0.0 CratesPlus version. Console log don't send any errors
