### ISSUE TITLE
Labels and holograms

### ISSUE THREAD

**Issue by Poweringg** [ConnorLinfoot/CratesPlus#166]
- Holograms don't disappear when i destroying chest
- Is there any way to disable the holograms?
- Can you add to the config possibility to edit these labels?
![2](https://cloud.githubusercontent.com/assets/15527318/14190014/c265a446-f790-11e5-8d88-7366d4a89dcb.png)
![1](https://cloud.githubusercontent.com/assets/15527318/14190015/c26b4324-f790-11e5-90c5-575b4284a6a8.png)

**Comment by ConnorLinfoot** [comment]
I may add options in the future to change those messages. You should be able to disable holograms by removing all text within the Holograms list. If you're having any issues please check your console for errors and post your config file, Spigot/CraftBukkit version, data file and any errors/console log.
