### ISSUE TITLE
Feature for money? Or another plugin?

### ISSUE THREAD

**Issue by elpedriyo** [ConnorLinfoot/CratesPlus#168]
Would you implement an option to erase the percentage message? Or do I need to search for another plugin? http://prntscr.com/akqbu2

If you want I can pay you some money for it, but I need to have it quickly.

Thanks

**Comment by ConnorLinfoot** [comment]
CratesPlus is a free plugin and I would rather not accept money to add features. This may be implemented at a later date when I have the time to work on it.
