### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by soaringsoul** [ConnorLinfoot/CratesPlus#174]
Hi,
I keep getting a spammy message in my console, and it is from CratesPlus...
`WARN Exception in thread "pool-3-thread-6754" 
11.04 16:46:16 [Server] INFO Caused by: java.lang.NullPointerException
11.04 16:46:16 [Server] INFO at java.lang.Thread.run(Thread.java:745)
11.04 16:46:16 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
11.04 16:46:16 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
11.04 16:46:16 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
11.04 16:46:16 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin CratesPlus v4.0.0 generated an exception while executing task 1181`
This message spams the console approximately every second.

I thank you in advance for your help...

**Comment by ConnorLinfoot** [comment]
As stated please post your config, Bukkit/Spigot version, CratesPlus version, configuration file, data file and console log. And just generally more information about your issue. Also don't post log/config files here. Use something like Pastebin.

**Comment by soaringsoul** [comment]
Sorry I didn't see something that said what to post..
I am currently using ` git-Bukkit-53fac9f (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)`
CratesPlus version 4.0.0
My Configuration file: http://pastebin.com/ecicKci7
Data.yml: http://pastebin.com/hwCBjzas
