### ISSUE TITLE
Unable to retain unbreakable datatag

### ISSUE THREAD

**Issue by jon4397** [ConnorLinfoot/CratesPlus#176]
I am using version CP 4.0.0, and am using Spigot 1.9.2.
When I place a diamond pickaxe with the "Unbreakable" tag on it inside a crate in the Crate Settings GUI, the item does not retain it's unbreakable tag. As this is very easy to reproduce and is an easy-to-understand issue, I will not bother you with screenshots.

**Comment by ConnorLinfoot** [comment]
CratesPlus currently doesn't store/support NBT data at this time.

**Comment by jon4397** [comment]
I see, thank you for the reply. Please consider this a suggestion then,
instead of a bug report. :) Thank you for the amazing plugin, it's the best
out there as of 1.9.2. We at Blue Skyes Server really appreciate your work
in Bukkit.
