### ISSUE TITLE
Holograms dissapearing

### ISSUE THREAD

**Issue by HappyHarm** [ConnorLinfoot/CratesPlus#177]
Hi there,

Somtimes the holograms just dissapear. I'm jusing the latest spigot version of cratesplus. Any idea how that could be?

**Comment by RazihelYT** [comment]
@HappyHarm He is just going to refer you to post #16 and it the commands will end up not working either after deleting all plugins and trying the provided commands. Simply remake the world is what I have done.

**Comment by HappyHarm** [comment]
That's not my problem, my problem is that they dissapear when I don't want them to dissapear. But I created them by hand using Holographic Displays what's a bit more stable for this. So probem solved :)
