### ISSUE TITLE
An internal error occured while attempting this command

### ISSUE THREAD

**Issue by UnNamedAndre** [ConnorLinfoot/CratesPlus#178]
An internal error in every command i do with /crate

Spigot version: PaperSpigot-1.7.10-R0.1-SNAPSHOT-

Plugin Version: CratesPlus 3.1.2
Config: http://pastebin.com/TQmAcU7J
Console Log: http://pastebin.com/8SaEWcgj

**Comment by ConnorLinfoot** [comment]
3.1.2 is no longer support and CratesPlus is not supported on 1.7.

**Comment by UnNamedAndre** [comment]
What version i have to use to put it in 1.7.2?

**Comment by ConnorLinfoot** [comment]
None, it doesn't support 1.7.
