### ISSUE TITLE
percentage glitch

### ISSUE THREAD

**Issue by scrublord9732** [ConnorLinfoot/CratesPlus#179]
For some reason when i am adding multiple percentages like as in one for each item only one of the items are appearing. here is what i have please note any bugs in the code

` Winnings:
      '1':
        Type: ITEM
        Item Type: IRON_HELMET
        Percentage: 65
        Item Data: 0
        Name: "\xa76Reward Armor"
        Amount: 1
        Enchantments:
        - PROTECTION_ENVIRONMENTAL-2
        - DURABILITY-2
        Lore: []
      '2':
        Type: ITEM
        Item Type: IRON_CHESTPLATE
        Percentage: 55.0
        Item Data: 0
        Name: "\xa76Reward Armor"
        Amount: 1
        Enchantments:
        - PROTECTION_ENVIRONMENTAL-2
        - DURABILITY-2
        Lore: []`

**Comment by scrublord9732** [comment]
Anybody?

**Comment by Meowzard** [comment]
all of the percentages must add up to 100 
soo instead of 65 use 0.65 and so on

**Comment by ConnorLinfoot** [comment]
We can only help you if you actually paste your entire config file at somewhere like pastebin.com

**Comment by scrublord9732** [comment]
Meowzard - That makes it 0.65%

Connor - http://pastebin.com/vAZDPHvP

**Comment by scrublord9732** [comment]
And this is what is happening: http://i.imgur.com/Qalp257.png
Only the first item appearing

**Comment by ConnorLinfoot** [comment]
As @Meowzard said above the issue is because your percentages don't add up to 100%. You're first one is 65% which is fine, then you have 55% so 65 + 55 = 120% which makes it invalid so it doesn't load the item.

You can now use decimals in v4.0 so you could have 0.65% and 0.55% and so on.
