### ISSUE TITLE
Default users cant use crates

### ISSUE THREAD

**Issue by Tommytom24** [ConnorLinfoot/CratesPlus#186]
Default users cant open crate keys, there is no factions claim or worldguard claim so I don't know whats wrong
thanks :)

**Comment by TobleroneMC** [comment]
Skype:  TobleroneMC, I might could help you.

**Comment by ConnorLinfoot** [comment]
The plugin uses interact to detect when a player clicks a crate. It could be any plugin interfering with this event including region plugins.
