### ISSUE TITLE
Default users can't open crates

### ISSUE THREAD

**Issue by Crionics** [ConnorLinfoot/CratesPlus#188]
They can open Default crates but when it's a different crate it wont open for them but only operators can. I have chest-access in all of my regions but it could be the warzone but im not 100% sure. Please help me thank you so much if you can reach out to me!

**Comment by ConnorLinfoot** [comment]
The plugin uses interact to detect when a player clicks a crate. I'm personally not familiar with WorldGuard but if there is any flag for interact that's probably the best thing to try.
