### ISSUE TITLE
deoped players cant use crates

### ISSUE THREAD

**Issue by shadow263** [ConnorLinfoot/CratesPlus#189]
hi so deoped players cant use the crates is there are permission or something im not seeing thanks ps i have noticed i few people have asked already bye =D

**Comment by DeezselfiezSD** [comment]
Make sure the crate isn't in a world guarded place

**Comment by shadow263** [comment]
nope its not

**Comment by shadow263** [comment]
bump

**Comment by shadow263** [comment]
bump

**Comment by ConnorLinfoot** [comment]
The plugin uses interact to detect when a player clicks a crate. This issue is usually caused by a plugin similar to WorldGuard or anything simply stopping the interact event working as expected.
