### ISSUE TITLE
money and mcmmo issue

### ISSUE THREAD

**Issue by GrannyTsunade** [ConnorLinfoot/CratesPlus#190]
I'm just wondering is their a way to add money and McMMO points to the Crates as a reward? Or something that needs to be messed with in the config. I have a mate who owns his own server and helped with the crate rewards but it doesn't seem to like what I've put in, although it is the same as my mates. Here is what I've put in, in case it helps.

Type: COMMAND
Item Type: PAPER
Item Data: 0
Name: 500 Coins
Command: 'eco give {uuid} 500'
Amount: 1
Enchantments: []
Lore: []

Type: COMMAND
Item Type: NETHER_STAR
Item Data: 0
Name: 5 mcmmo points
Command: 'givecredits {uuid} 5'
Amount: 1
Enchantments: []
Lore: []

When changing the type and adding the command, the plugin doesn't seem to like it and removes everything that I've changed.

**Comment by LPGamersRob** [comment]
hi, change the {uuid} to %uuid% and try that, if that does not work i dont know what it could be.

**Comment by GrannyTsunade** [comment]
Thanks, I just gave that a try. Had no luck with it.
