### ISSUE TITLE
1.9 Enchanted Books and Spawn eggs

### ISSUE THREAD

**Issue by Dennisxo** [ConnorLinfoot/CratesPlus#193]
Hey,
i use you plugin for my Skyblockserver on 1.9. Your Plugins works fine for me with 1 issue.
all spawneggs and enchanted book are blank :( can you please fix that for this version?

**Comment by ConnorLinfoot** [comment]
Currently the plugin doesn't support 1.9 NBT data, the best bet for this is to use commands instead of just items.
