### ISSUE TITLE
Permission Errors

### ISSUE THREAD

**Issue by Nonnor** [ConnorLinfoot/CratesPlus#195]
Hello. I have 2 problems.
First of all, only OP's can open the crates (Except for the common crate) with the keys. 
Also, when I log out all the names flying over the crates disappear.

**Comment by Nonnor** [comment]
It doesn't say anything when they can't open them. Just doesn't work

**Comment by ConnorLinfoot** [comment]
There is no permission for accessing the crates. Usually a plugin like WorldGuard will be blocking the crates being opened.

**Comment by Nonnor** [comment]
So how should I disable worldguard blocking it?

2016-05-19 9:58 GMT+02:00 Connor Linfoot <notifications@github.com>:

**Comment by ConnorLinfoot** [comment]
I personally don't use WorldGuard so I wouldn't know 100%. I believe it's something like 'chest-access' but I'm not sure.

**Comment by Nonnor** [comment]
Okay. But do you know why it worked with the 'Common' crate for all players
but not for other people?

2016-05-19 15:47 GMT+02:00 Connor Linfoot <notifications@github.com>:

**Comment by ConnorLinfoot** [comment]
I'm not quite sure what you mean?

**Comment by Nonnor** [comment]
So I basically made 3 different types of crates, Common, Rare & Mythical.
I then gave my friend that was non op and the default 'Member' rank one key
for each crate. He could open the Common ones, but not the Rare and
Mythical?🤔

2016-05-19 15:54 GMT+02:00 Connor Linfoot <notifications@github.com>:

**Comment by ConnorLinfoot** [comment]
It would depend on the crates location. If they're in a protected WorldGuard region that could be blocking it. Try removing the common crate and adding a rare in the same place and see what happens.

**Comment by Nonnor** [comment]
They were both in a world guard protected area.

2016-05-19 15:58 GMT+02:00 Connor Linfoot <notifications@github.com>:

**Comment by ConnorLinfoot** [comment]
I'm not 100% sure then. To get a little technical the CratesPlus plugin uses the "PlayerInteractEvent" to listen for people opening chests which are registered as a crate. If any other plugin cancels the "PlayerInteractEvent" then the crate won't open. There's not much I can do about this, you'd just have to find the cause and see if you can fix it somehow.

**Comment by Nonnor** [comment]
Actually this is too buggy and so on. I'd just use another one.
Still thanks for the advice.

2016-05-19 16:02 GMT+02:00 Connor Linfoot <notifications@github.com>:

**Comment by ConnorLinfoot** [comment]
Not exactly "buggy" when it's just people with incorrectly configured servers xD

**Comment by Nonnor** [comment]
My server works very good with all plugins. You've designed a plugin that
doesn't fit with other plugins. That's why. Still a great job making the
plugin.

2016-05-19 16:07 GMT+02:00 Connor Linfoot <notifications@github.com>:

**Comment by MiniCraft12** [comment]
Well said @Nonnor. Your plugin is good, but you as a developer are overall rude and unhelpful to the users of your plugin. I personally think that your somehow not familiar with the plugin that you created and therefore do not have a clue on how to fix the most basic issues that occur.

**Comment by ConnorLinfoot** [comment]
I don't understand how not knowing his specific issue falls down to me not understanding my own plugin. If a user incorrectly configured there server with something like spawn protection what do you expect me to do? Force change the settings? No cause that'd be stupid. 

The plugin is tested to work even with WorldGuard when setup correctly. I can't help it if there is another plugin blocking you opening the crates.

**Comment by Nonnor** [comment]
Not even dealing with minecraft anymore, so please may you be quiet?

torsdag 28 juli 2016 skrev Connor Linfoot <notifications@github.com>:
