### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by DjxSnipezz** [ConnorLinfoot/CratesPlus#196]
Hey, I love your plugin, but I can't seem to get commands working. Could you tell me how to give a player in-game money if he lands on lets say a peice of paper saying 10K?

Thanks!

**Comment by ConnorLinfoot** [comment]
Please provide plugin list, /version output, config.yml, data.yml, and any other server configuration you may have changed.

Issue will be re-opened if the above is provided.
