### ISSUE TITLE
Holograms

### ISSUE THREAD

**Issue by ShinnerMiner** [ConnorLinfoot/CratesPlus#197]
I followed the commands for creating a crate I need to remove the crate and did the /crate delete <Common>.. I did the sneak and removed the crate, however the hologram is not removing. I searched the issues for it and found the following fix for it /entitydata @e[type=ArmorStand,r3] {Invisible:0} from Holograms glitched when removing chests. #16.  I ran the command and I get this
Enity data updated to:invisible:0

(https://cloud.githubusercontent.com/assets/19456766/15382620/c323d1d4-1d59-11e6-9e3a-aedc06215571.png)
![holorgram not removed crates](https://cloud.githubusercontent.com/assets/19456766/15382622/cc3eceae-1d59-11e6-890f-2732a8301053.png)

**Comment by ConnorLinfoot** [comment]
Please provide plugin list, /version output, config.yml, data.yml, and any other server configuration you may have changed.

Issue will be re-opened if the above is provided.

**Comment by CaptDarkStar** [comment]
This is part of the new 1.9 entity changes. Not a problem with the plugin itself, but the changes in minecraft entirely. I have run into this myself and I am running 1.9.4 as of today and ironically needed to use this when my holograms didn't delete when moving my crates. Didn't work at all and did the same thing as above.

**Comment by ConnorLinfoot** [comment]
If you're running 4.0+ the above won't work as holograms use packets.
