### ISSUE TITLE
No giving proper items after second oppening!

### ISSUE THREAD

**Issue by DatSpace** [ConnorLinfoot/CratesPlus#198]
My server is running on 1.9.2-R0.1-SNAPSHOT version of Spigot. The issue is described in the actions to reproduce section! I get no error in console nor the log or anything similar!

**### Link/paste of stack trace**
No error in console/log!

**### Plugin list:**
CratesPlus 4.0.0
ObsidianBreaker1_9 2.3
Essentials TeamCity
ClearLag 2.9.1
PerWorldPlugins 1.9.4.1
AnimalPlague 0.6.0
Votifier 1.9
Multiverse-Core 2.5-b717
NoCheatPlus 3.14.0-SNAPSHOT-sMD5NET-b973
ZavAutoMessager1_9_2 ${project.version}
SkinsRestorer 11.6
FastAsyncWorldEdit 3.5.0-00c685c
EssentialsProtect TeamCity
KitPreview 3.8.0
PermissionsEx 1.23.4
EssentialsAntiBuild TeamCity
AntiJoinBot 5.0
SuperbVote 0.3.1
mcMMO 1.5.05-SNAPSHOT-b136
RandomTp 2.1
Tablist 1.3.0.2
Vault 1.5.6-b49
EssentialsSpawn TeamCity
MassiveCore 2.8.14
WorldEdit 6.1.2,b3fbe8b
Herochat 5.6.7-SNAPSHOT
AuthMe 5.2-SNAPSHOT-b870
Jobs 3.3.6
HolographicDisplays 2.1.12
WorldGuard 6.1
Citizens 2.0.17-SNAPSHOT (build 1362)
Sentinel 0.5 (build 37)
Factions 2.8.14
AuctionHouse 1.3.4
LeaderHeads 10.4
PlayerVaults 3.5.7-b${BUILD_NUMBER}
ServerSigns 4.5.1
CustomEnchantments 2.4c
CombatTagPlus 1.2.3
CreativeControlByKubqoA 2.2.2
WarpPortals 5.6.3
SilkSpawners 3.7.1

**### Actions to reproduce (if known):**
To reproduce you just need to make a crate adding 256x diamonds as an item (at least thats my problem) and then try to win them. At first you get to proper amount of diamonds in all cases. If you have won the diamonds and open the crate again and no matter the trial you select diamonds again you are just going to receive one stack and not the full amount!
PS  In the config file the problem is caused in the Premium Crate!

**### CratesPlus Version:**
I have version 4.0.0

**### CratesPlus config.yml**

http://pastebin.com/mi1g0mjC

**### CratesPlus data.yml**

http://pastebin.com/bVwxCAyL

**Suggestions:**

Regarding this issue I dont know what causes it. But another thing I want to suggest is that each crate to have an option in the config in boolean that if true will hide the items percentages inside the chests, so the players cannot see them!

**Comment by ConnorLinfoot** [comment]
Will look into the bug, the suggestion you made will be in version 4.1 :)

**Comment by ConnorLinfoot** [comment]
Ahhh, fixed it! Seems like after rewarding the item Bukkit would reset the stack to the maximum stack size in vanilla. Will be fixed in 4.1, which is due to release in the next week or less :)
