### ISSUE TITLE
[REQUEST] Run custom commands

### ISSUE THREAD

**Issue by GiansCode** [ConnorLinfoot/CratesPlus#20]
Hello there,

I am writing this to request a feature to be added to the plugin. I was wondering if you'd be willing to add commands that a player could win?

So, like, when they open the crate, and they land on a specific item, they get commands ran on their behalf (either by them, or by the console). I feel this will be a great feature!

Also, I was wondering if you'd add the ability to win more than one item at a time.

I'm not sure if these are already added, I haven't seen them, though.

Thanks,
Gianluca

**Comment by ConnorLinfoot** [comment]
Added in V3.1 (To be fully released soon!)
