### ISSUE TITLE
Holograms on all worlds

### ISSUE THREAD

**Issue by HappyHarm** [ConnorLinfoot/CratesPlus#201]
**Please use one of the issue templates below. Issues not using the templates will likely be closed!**
### CratesPlus Version:
___This can be found by running `/version CratesPlus` on your server.___
4.1.0- SNAPSHOT-1
### CratesPlus config.yml
___Please upload to pastebin.com and provide link___
http://pastebin.com/TW4TbPMg
### CratesPlus data.yml
___Please upload to pastebin.com and provide link___
http://pastebin.com/wpds3UWR
# Suggestion

The problem is the holograms of the crates are displayed on other worlds like the end.
http://prntscr.com/b89jbe
http://prntscr.com/b89j41

**Comment by ConnorLinfoot** [comment]
Was able to replicate this but I'm not going to really look into fixing it. From version 4.1 CratesPlus will try to use other hologram plugins to handle the hologram displays and it will "deprecate" the current handler which will later on be fully removed. I recommend testing the latest snapshot with either holographic displays or individual holograms.

**Comment by ConnorLinfoot** [comment]
@HappyHarm try snapshot 8 :)
