### ISSUE TITLE
adding percentages/commands will crash the plugin and create a new config file.

### ISSUE THREAD

**Issue by FireBlaZeN** [ConnorLinfoot/CratesPlus#205]
**Please use one of the issue templates below. Issues not using the templates will likely be closed!**

# Crash, Stacktrace or Configuration issue

http://pastebin.com/UpKNmkKy

    You can also simply just use code formatting in markdown!

### Plugin list:
cratesplus
protocollib

### Actions to reproduce (if known):
https://www.youtube.com/watch?v=OFOVbCVLF60&feature=youtu.be

### CratesPlus Version:
version 4.1.0

### CratesPlus config.yml
http://pastebin.com/DKB9z6wu

### CratesPlus data.yml
http://pastebin.com/18A5C2Q3
# Suggestion
great plugin, would be nice if commands and persentage would be working aswel.

**Comment by ConnorLinfoot** [comment]
This is not a CratesPlus error, your config file is a invalid YAML.
