### ISSUE TITLE
commands wont work

### ISSUE THREAD

**Issue by FireBlaZeN** [ConnorLinfoot/CratesPlus#206]
**Please use one of the issue templates below. Issues not using the templates will likely be closed!**

# Crash, Stacktrace or Configuration issue

### Link/paste of stack trace

http://pastebin.com/q3miPkD0

### Plugin list:
http://pastebin.com/dH8pkU8y

### CratesPlus Version:
version 4.1.0

### CratesPlus config.yml
http://pastebin.com/dH8pkU8y

### CratesPlus data.yml
http://pastebin.com/QpaTwsGB

**Comment by ConnorLinfoot** [comment]
I'm not sure what your issue is here? The stacktrace errors are not caused by CratesPlus. You also didn't post your config file.

**Comment by FireBlaZeN** [comment]
config file: http://pastebin.com/zbxWEXBX 
 the problem is that the commands dont work.
one of them is the paper wich should give the player 50$ but it just gives  the player the paper.

**Comment by FireBlaZeN** [comment]
also, when reload using this config it removes some items in the voter crate.

**Comment by ConnorLinfoot** [comment]
Which commands are failing? Just tested it with the Voter crate commands and it's working fine for myself.

**Comment by FireBlaZeN** [comment]
i fixed the commands now, by putting it all 1 space further.
the problem now is that in this config the tnt, obsidian, 500$ and the kit disapear. and when running the command "say %player% has won 100$ from the §2VoterCrate" it will say this in the server : https://gyazo.com/eb19b7cd78f01c44ba257fe63de4c355

**Comment by ConnorLinfoot** [comment]
The missing items is caused by you not using a capital 'C' with "Commands" fix that and they work. and %player% is not a placeholder, it literally has a list of placeholders at the top of the config file.

**Comment by FireBlaZeN** [comment]
well, stpd me didnt see that, thanks for helping me out. love this plugin!
