### ISSUE TITLE
Help pls... 

### ISSUE THREAD

**Issue by DeadMasterBG** [ConnorLinfoot/CratesPlus#207]
**Please use one of the issue templates below. Issues not using the templates will likely be closed!**

# Crash, Stacktrace or Configuration issue

### Link/paste of stack trace

    You can also simply just use code formatting in markdown!
___We need all of the stack trace! Do not cut off parts of it.___

### Plugin list:
CratesPlus, 
GlobalMute, 
SkinsRestorer, 
Timber, 
SkinsModule, 
Essentials,
EssentialsSpawn, 
EssentialsChat, 
GroupManager, 
AuthMe
(This is test server...)

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### CratesPlus Version:
___This can be found by running `/version CratesPlus` on your server.___
CratesPlus version 4.1.0

### CratesPlus config.yml
http://pastebin.com/N4jRTxZe

### CratesPlus data.yml
http://pastebin.com/MGCVPHR4

I place this config (http://pastebin.com/N4jRTxZe) and after /reload (http://pastebin.com/NVet2iyZ)
pls help...

**Comment by ConnorLinfoot** [comment]
Your configuration file is invalid, use a YAML parser to check - http://yaml-online-parser.appspot.com/
