### ISSUE TITLE
Crate Example is not going away

### ISSUE THREAD

**Issue by StaticCraft** [ConnorLinfoot/CratesPlus#21]
Hello, 
I have factions installed and when i placed the crate down it only showed the title of the crate not the crate, I think this was because i didnt have /.f admin enabled so i enabled /f admin, and it will not allow me to remove the title i removed the plugin and still had the same problem could you respond asap

Thanks
Steven

**Comment by ConnorLinfoot** [comment]
Duplicate of issue #16

**Comment by StaticCraft** [comment]
Thanks so much i tried to get ride of it with creeper eggs hahaha

**Comment by StaticCraft** [comment]
you sould really consider putting that in the desc of the chest plus plugin
