### ISSUE TITLE
PLugin conflict cause blank info messages to be spammed.

### ISSUE THREAD

**Issue by CaptDarkStar** [ConnorLinfoot/CratesPlus#212]
So I added the plugin CustomOreGen (https://www.spigotmc.org/resources/customoregen.9532/) to my skyblock world. After configuring it for my server I noticed that every time a block is broken, I was getting blank info messages spammed in my console. 

Example:
https://gyazo.com/cb39303b68a741667c3aff25d9d7b563

After a couple hours of plugin testing and searching, I found that this plugin is sending the blank info messages. Is tehre a way we can find this cause and stop it? It seems to happen every time a block is broken in my generator.

**Comment by ConnorLinfoot** [comment]
Can you give other information like in the issue template please? Including CratesPlus/Bukkit version

**Comment by CaptDarkStar** [comment]
Well now I feel like an idiot lol. I found out I was behind and never updated to 4.1.0 and was still on 4.0.0 snapshot 11. Appearently after updating to 4.1.0 this issue no longer occurs. I'll close this now.
