### ISSUE TITLE
ColorCodes for Crates

### ISSUE THREAD

**Issue by Fyriboo** [ConnorLinfoot/CratesPlus#213]
# Suggestion

Could you add the possiblity off editing the crate or key name with color codes please.

**Comment by ConnorLinfoot** [comment]
Adding color codes makes names harder to handle and also just messy as people go over the top with it. There is a single option for changing the overall color of the crate name.

**Comment by CaptDarkStar** [comment]
I just said screw it and stopped using crateplus holograms as they are buggy and kinda unreliable. Just disable the default hologram text for the crates, and then use holographic displays plugin. Much better design, reliability and options for labeling your crates. Can even use multiple colors, animations and even icons.

**Comment by ConnorLinfoot** [comment]
@CaptDarkStar Yeah the holograms were always a pain. The plugin now uses Holographic Displays if you've got it and I'll be removing the built in system in the near future :P
