### ISSUE TITLE
When player dies with key, the key completely disappears.

### ISSUE THREAD

**Issue by CaptDarkStar** [ConnorLinfoot/CratesPlus#214]
As of stable/recommended version 4.1.0 (and latest release), then a player dies with a key in their inventory, it completely disappears. With "Disable Key Swapping: true" it is suppose to keep it in their inventory, but it just deletes it completely.

**Comment by ConnorLinfoot** [comment]
It's supposed to remove it as it was the easiest solution at the time, I may change it in the future but at the moment, it works as intended.

**Comment by CaptDarkStar** [comment]
Well I do hope that gets changed. Being that keys are generally a paid item/prizes, it is bad to have them simply disappear for the player. Just something to consider.

**Comment by ConnorLinfoot** [comment]
Going to look at giving the player the key back on respawn or putting the key in the claim GUI.
