### ISSUE TITLE
Crate Commands.

### ISSUE THREAD

**Issue by NaazeYT** [ConnorLinfoot/CratesPlus#215]
_Before I begin I would like to add a suggestion:
Could you make it so you can add commands in game as well as the config ?

Anyway my issue.
Adding commands to Crateplus items I find really hard.
Ive looked at the pastebin

Link: http://pastebin.com/grPRrSXp

I used crate item 3 for a template guide. I changed it to how I wanted it! Everything was working fine reloaded the plugin and the crate was gone. But it was still in the config!

Screenshots provided below:
Picture of config: http://prntscr.com/bbeu3e
Picture of in game crate settings: http://prntscr.com/bbeuum

At this point I was messing around in the config nothing worked.
Now I'm stuck waiting for a reply...

Thanks

- Naaze_

**Comment by ConnorLinfoot** [comment]
Please actually follow the structure when creating a new issue. Include config files via pastebin as well as data files, plugin list and CratesPlus version.

**Comment by CaptDarkStar** [comment]
Looking at your config that you linked, I see two issues. 

1) Your spacing is off on line 33. You need to add one more space.
2) Your percentages don't add up to 100%. It is only 2.5% 

Fix those two issues and it should be good in theory.
