### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by FireBlaZeN** [ConnorLinfoot/CratesPlus#217]
# Suggestion

adding different kind of gui's whould be cool, also in game percentage adding would make it much easyer to use.

**Comment by ConnorLinfoot** [comment]
**[Openers](https://github.com/ConnorLinfoot/CratesPlus/wiki/Custom-Openers)** for custom GUI's etc ;)

**Comment by FireBlaZeN** [comment]
a build in broadcast is nice aswel

**Comment by ConnorLinfoot** [comment]
Already exists! xD

**Comment by FireBlaZeN** [comment]
how? i didnt know lol

**Comment by FireBlaZeN** [comment]
also im pretty bad with those coding stuff

**Comment by ConnorLinfoot** [comment]
Broadcast is in the config file, if you can't make an opener hire someone to do it for you. Or request one and it may get made.
