### ISSUE TITLE
WorldGuard Support

### ISSUE THREAD

**Issue by lbray101** [ConnorLinfoot/CratesPlus#219]
# Suggestion

I would love for this plugin to be integrated with WorldGuard for better support/ease of use. The reason I ask for this is because I currently have the following flags for WorldGuard on and players are unable to interact: Interact: allow, Use: allow, Chest-Access: Allow, Passthrough: Allow, Build: Allow and people can not interact. It's just something I would really like to see soon! If anyone can help me with the issue let me know. I also have added the proper permission that I set for the crate's access. If you need a copy of my config I can send one. 

Thanks

**Comment by CaptDarkStar** [comment]
I use world guard and have no issues at all within my worldguard region. All you should need is interact allowed and that is it. What other plugins are you using? Can you give the error message it tells players?

**Comment by ConnorLinfoot** [comment]
Sounds like you've added every common flag *except* the one that makes the most sense. The interact flag. Adding that makes the plugin work in a WorldGuard region.

**Comment by ConnorLinfoot** [comment]
The interact flag usually works fine with WorldGuard. Most likely to be another plugin as mentioned above.

**Comment by lbray101** [comment]
I actually figured it out. Thanks for the help! 

Essentials AntiBuild was causing the issue.
