### ISSUE TITLE
Title and info 

### ISSUE THREAD

**Issue by urbea97** [ConnorLinfoot/CratesPlus#22]
The title and info above the crate disapper everytime i do a reload on my server so like i do a reload and lets say the crate name is votingcrate with the info right click to use yea well when i reload my server it all disappers so i have to go /crate crate (cratename) (user) and then replace everycrate i really need this fixed fast plz i cant have this my server is already up and i have to keep it down till this is fixed so plz fix it fast thanks!

**Comment by ConnorLinfoot** [comment]
This is not an issue with the plugin. The plugin use's ArmorStand entity's for the holograms and you most likely have a plugin removing (killing) those ArmorStands.
