### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by bazzernazz** [ConnorLinfoot/CratesPlus#222]
When i had this plugin, Cratesplus i had 5 crates,then when i deleted the .jar file because i wanted to test another crate plugin i then restarted my server, when i logged back into my server the Holograms were still there, i tried using a command to get rid of them '/kill @e[type=ArmorStand]' that didnt work, i searched online about this but i found nothing, can you help fix this because i cannot get rid of the holograms, it would be easier if it was using Holographic displays because you can simply just delete it via holographic displays commands?

I really need some one to help resolve this problem?

- Bailey

**Comment by ConnorLinfoot** [comment]
Please use the format provided when creating an issue.

**Comment by bazzernazz** [comment]
Omi fucking god I dont car e about no fucking forma

**Comment by ConnorLinfoot** [comment]
I can't help you if you don't provide the information needed.

**Comment by ConnorLinfoot** [comment]
As a side note, your point on Holographic Displays. If you read the description you'll see that it does use that plugin if it's installed.
