### ISSUE TITLE
Holograms bug

### ISSUE THREAD

**Issue by bazzernazz** [ConnorLinfoot/CratesPlus#223]
I have a problem with the holograms, they are still in my world even though i dont have the plugin.

My server is running Spigot 1.9.2+

I was using crates plus 4.1.0

I dont have a config, it has nothing to do with config, its the holograms

**Comment by ConnorLinfoot** [comment]
Right, you're still not following the format. I need a list of plugins. I need your config file that you had previously. 

Also, have you tried adding the plugin. Removing the crates. And then removing the plugin.

**Comment by bazzernazz** [comment]
I did try adding the plugin back then try removing the crates but it doesnt do anything

**Comment by bazzernazz** [comment]
am i going to get help or Nah?

**Comment by ConnorLinfoot** [comment]
Please read what I said...

**Comment by bazzernazz** [comment]
about the all my plugins and config

**Comment by bazzernazz** [comment]
Not being mean and all but does it look like i care about the format, all i need is assistance on how to remove the holograms,

**Comment by ConnorLinfoot** [comment]
So provide what information I've requested... I'm not a magician.

**Comment by bazzernazz** [comment]
But i dont have the config because i deleted it

**Comment by bazzernazz** [comment]
and what does my plugins have to do with the holograms?

**Comment by ConnorLinfoot** [comment]
If you don't want to give me a list of your plugins that's fine. Don't expect any help.

**Comment by bazzernazz** [comment]
You are a bad dev

**Comment by bazzernazz** [comment]
i have 44 Plugins

**Comment by bazzernazz** [comment]
actualy 35

**Comment by ConnorLinfoot** [comment]
I'd like to know how I'm a bad developer because you won't provide a list of your plugins.

Considering you just won't give me a list I'll give you a few possible plugins that could be causing issues.

- Holographic Displays - CratesPlus will use this to handle holograms. If you have this then you'll need to look in there for the holograms.
- Individual Holograms - Same as above.
- WorldGuard (or other protection plugins) - Could be disabling the removal of entities.

**Comment by bazzernazz** [comment]
World edit
RankVouchers
Essentials
ClearLag
OreGenerator
WorldGuard
ProtocolLib
NoCheatPlus
LibsDisquises
KitAdder
SwearFilter
EssentialsXMPP
MobStacker
SuperTrails
EssntialsProtect
EssentialsGeoIP
EssentialsChat
PermissionEX
Featherboard
CommandWatcher
CustomCrates - new crate plugin i wanted to test
Vault
EssentialsSpawn
Lores
EnjinMinecraftPlugin
TitleManger
ChestShop
AuctionHouse
ASkyblock
PlayerVaults
Multiverse-core
Mulitverse-Portals
Crates-plus

**Comment by bazzernazz** [comment]
Better
all of the plugins i have because you told me to give them to you

**Comment by ConnorLinfoot** [comment]
Assuming it's WorldGuard or EssentialsProtect. Try removing plugins and then delete the holograms. Or putting the world on a plain server (or single player) and removing the holograms there.

Also that's all the help I'm giving you. I really don't appreciate you have your "friend" create this account https://github.com/Conorkillurself

**Comment by bazzernazz** [comment]
I didnt make him make the account i told him about this and gave him the link to this github page then he must of done that, im serious i didnt make him do that. i really need the help but i didnt know he was going to create an account, i am speaking to him right now about this, and to see if he can change the name of his account.

**Comment by ConnorLinfoot** [comment]
Sorry but I really don't care. I've given you help on how to fix it so try that. Apart from that I'm not supporting yourself in any way. If you've given a link to your friend and he's made an account telling me to "kill myself" then I feel like that's more than a good enough reason not to support yourself.

**Comment by bazzernazz** [comment]
I gave him the link because he asked me to, so i did

**Comment by bazzernazz** [comment]
I didnt know he was going to create an account asking you to kill your self

**Comment by bazzernazz** [comment]
The World Guard and Essentials Protect didnt work so now i am downloading the world file

**Comment by bazzernazz** [comment]
Well i downloaded the world and went onto it and its not there?

**Comment by bazzernazz** [comment]
You made the plugin, you should know how to fix the problem

**Comment by bazzernazz** [comment]
I am happening to delete all files on my server as of now because you cannot simply resolve a problem your plugin created. Just a suggestion make the plugin use Holographic displays if installed on the server instead of a built in one that can break a server

**Comment by bazzernazz** [comment]
I wish i could change the review rating
