### ISSUE TITLE
Issue in "messages.yml"

### ISSUE THREAD

**Issue by Luffyleking** [ConnorLinfoot/CratesPlus#227]
Firstly sorry if i wrote this issue on spigot :)
Anyway i am going to recap my Issue.
I'm french so i wanted all the messages in french obviously.
So i changed them , reload the plugin with the "/crate reload" command then I gone back on my server and no messages has been changed and it stayed the original messages.
So I hope you could help me , or maybe devellop the messages in differents languages , I don't know :)
Let tell me if you didn't understand my issue or if you solve it :) 
Thanks !

**Comment by ConnorLinfoot** [comment]
Have you tried stopping the server, updating the file and then starting it again?

**Comment by ConnorLinfoot** [comment]
Closing this as I've not heard anything back...
