### ISSUE TITLE
Players do not have access to my Vote crate

### ISSUE THREAD

**Issue by Victhetiger** [ConnorLinfoot/CratesPlus#228]
Issue: Default players do not have access to my Vote crate.

### Link/paste of stack trace
Console: No errors whatsoever in console/logs

### Plugin list:
http://prntscr.com/bfiw43

### Actions to reproduce (if known):
Set up a crate

### Bukkit/Spigot Version:
1.9.4

### CratesPlus Version:
4.1.0

### CratesPlus config.yml
http://pastebin.com/QHqraazM

### CratesPlus data.yml
http://pastebin.com/yUxBy5uc

# Suggestion
Ability to modify the "%crate% Possible Wins:" on the chest

___We love suggestions! Suggestions are fairly unstructured, and will be treated as such___

**Comment by ConnorLinfoot** [comment]
Are you using WorldGuard or Essentials to protect the area you have placed the chests? If so you'll need to make sure you allow "interact" for these.

**Comment by Victhetiger** [comment]
Well, I did not block "interact" for WorldGuard but players do say they get a dark smoke particle on top of the block when they click it. I'll try doing that.

**Comment by Victhetiger** [comment]
I believe that worked, thank you very much.

**Comment by ConnorLinfoot** [comment]
Great :smile:
