### ISSUE TITLE
Option to turn off the chest open sound

### ISSUE THREAD

**Issue by JonathanVil** [ConnorLinfoot/CratesPlus#229]
Hey guys! My players are really annoyed that all players can hear a chest open sound, when a player opens a crate. PLEASE ADD A OPTION TO TURN IT OFF!

**Comment by ConnorLinfoot** [comment]
Woah calm down man :heart:

**Comment by ConnorLinfoot** [comment]
4.2 Snapshot 1 now only uses the chest open sound on the NoGUI opener, and it should be quieter.
