### ISSUE TITLE
Config glitch.

### ISSUE THREAD

**Issue by weakwizard** [ConnorLinfoot/CratesPlus#23]
For some reason, when using this config: http://pastebin.com/g495mFvu the plugin is 100% broken. It registers in /pl but doing /crate returns no output. However, using the default config fixes the problem but I can't change it. Can anyone fix the config please?

**Comment by ConnorLinfoot** [comment]
What version of the plugin are you running?

**Comment by ConnorLinfoot** [comment]
Tested it on Snapshot 10 of V3.1 and I edited it to make it work: http://pastebin.com/sHNY2sv2

Don't use the § characters as they can cause issues, use & instead. Also when using these make sure to put the string in quotes.
