### ISSUE TITLE
Rewards not showing up.

### ISSUE THREAD

**Issue by FusionPyro** [ConnorLinfoot/CratesPlus#230]
Hello there, for some weird reason only the first 2 rewards works and the rest don't show up/work. do you know how i could fix this? 

Best Regards,
Callum

http://prntscr.com/bfx0hg

Plugin list: http://prntscr.com/bfwzs7

Spigot version: 1.8.8

Crates Plus version: 4.1.1

Cratesplus Config: http://pastebin.com/uaqqqiuy

Cratesplus data : http://pastebin.com/b8uzvwRj

**Comment by zr120cat** [comment]
Your percentages MUST equal 100% or the prize that goes over 100% and prizes after that will disapear

**Comment by ConnorLinfoot** [comment]
@FusionPyro as said by @zr120cat your rewards can not add up to more than 100% (as that's just not how percentages work) 

This may change in the future but for now you need to change them to be lower. You can use decimals if that helps.
