### ISSUE TITLE
Hologram not going away

### ISSUE THREAD

**Issue by zr120cat** [ConnorLinfoot/CratesPlus#231]
![2016-06-13_23 08 41](https://cloud.githubusercontent.com/assets/19921510/16030970/d3b554f2-31bb-11e6-8a05-96109cfeb1ac.png)
Hello! when I shift left clicked my crate it didn't delete the hologram. In fact, the hologram had black around the letters. If you can find a fix, then please help me! Info: I have these holograms in my spawn which is safe zone (factions) and has a region (world guard)

**Comment by ConnorLinfoot** [comment]
Please follow the issue format.
