### ISSUE TITLE
Better Item Support

### ISSUE THREAD

**Issue by BlackCaptainTR** [ConnorLinfoot/CratesPlus#235]
That ingame editing was super useful. But I noticed something wrong. I am using MythicMobs plugin to create items and give them functionality with Skript. 
**I am hiding item flags(+5 ATTACK DAMAGE) after I hide flag in config then place the item in CratesPlus winnings editor gui. The flag comes visible again when you gain the item or on preview.**
 If you solve this, it will be awesome. And also as you can see Test 'possible winnigs' please add more translation options. Good work, thanks for everything.
![1](https://cloud.githubusercontent.com/assets/6266078/16118347/52b0bb00-33df-11e6-9900-8fe60fa2c217.PNG)
![2](https://cloud.githubusercontent.com/assets/6266078/16118348/52b1e552-33df-11e6-95e1-faf5121b3d11.PNG)

**Comment by ConnorLinfoot** [comment]
I recommend using a command to give items with flags. The current issue is that flags use "NBT Data" which doesn't have any sort of API in Bukkit (yet) so it's tough to do. I do hope to *maybe* do it one day but not guaranteed. 

I'll also be adding more options for translation :P

**Comment by ConnorLinfoot** [comment]
Going to try and look at this for v4.3 but no promises, depends on time really.
