### ISSUE TITLE
No open

### ISSUE THREAD

**Issue by Ula492** [ConnorLinfoot/CratesPlus#237]
My players are not able to open the crates with out OP is their a permission so players can open the crate?

**Comment by ConnorLinfoot** [comment]
Duplicate of #228, issue caused by mis-configuration of other plugins.

**Comment by Ula492** [comment]
did not work

**Comment by Ula492** [comment]
does not say any worldguard msgs

**Comment by ConnorLinfoot** [comment]
It'll be due to another plugin. CratesPlus has no permissions or anything blocking the opening of crates.

**Comment by Ula492** [comment]
http://imgur.com/cKB9gG0

**Comment by Ula492** [comment]
Help?

**Comment by ConnorLinfoot** [comment]
It's not an issue with the plugin. Something isn't configured right with your server.

**Comment by Ula492** [comment]
Like what?

**Comment by ConnorLinfoot** [comment]
I wouldn't know. I don't use your plugins. Maybe also check your spawn protection.
