### ISSUE TITLE
Block type bug

### ISSUE THREAD

**Issue by NotableOsprey92** [ConnorLinfoot/CratesPlus#238]
**Please use one of the issue templates below. Issues not using the templates will likely be closed!**

# Crash, Stacktrace or Configuration issue

When you change the block type of a crate to END_PORTAL_FRAME the plugin dose not work and shows up in red when you do /pl.

### Bukkit/Spigot Version:
Paper Spigot 1.8.8

### CratesPlus Version:
4.1.1
### CratesPlus config.yml
http://pastebin.com/FXRrJRew

**Comment by ConnorLinfoot** [comment]
END_PORTAL_FRAME isn't a valid block material - http://pastebin.com/4Xqn9UaE
