### ISSUE TITLE
Issue's and suggestions!

### ISSUE THREAD

**Issue by ShaneSik** [ConnorLinfoot/CratesPlus#24]
Hello there,

Issue 1: Everytime i delete the example crate it returns later. I'm using this for my vote system but they keep recieving example crate keys again and again.

Issue 2: I'm using Snapshot 10, and when i change this new option:
 - Added config options to be able to change the text shown on holograms
And then reload the hologram text is still the same!

Suggestion: The new beta GUI animation time should be a bit lower or configurable. The waiting time now is a bit to long.

Is this plugin still being updated? The last edit was 26 days ago and that day you also said 3.1 is in final testing state and would be released soon, but it still isn't released haha!

Thanks!

**Comment by ConnorLinfoot** [comment]
Issue 1 is something I will look into.

Issue 2 you will need to replace the Crate. Because it use's Armor Stand's and there's no tracking the plugin wouldn't easily know if they need updating. May fix this in the future.

In response to it been updated check your Spigot review :)

**Comment by ShaneSik** [comment]
Thanks for your reply Connor! 

Would be nice if you are able to fix Issue 1. 
As for issue 2 thanks for letting me know this! 

I forgot to mention my other suggestion i just noticed:

It would be nice if you can add the other options like knockback, firework in the in-game editor. :)

**Comment by ShaneSik** [comment]
Connor, is there any option to make the time of the GUI beta animation less longer (the rolling thing)? Like a quick-fix update? My players start saying after the update to snapshot 10 it's to long aswell haha

**Comment by ConnorLinfoot** [comment]
V3.1 deffo before the end of the week (Sunday) and I'll add an option in the next snapshot. Hopefully that'll be today ;)

**Comment by ShaneSik** [comment]
Wow! That would be so awesome Connor to lower the GUI animation time.
Also, when i delete the example crate, it returns as i mentioned, but just to let you know the problem still exists on Snapshot 10. :)

Looking forward to a snapshot today!

**Comment by ConnorLinfoot** [comment]
I've added the option to change the time but haven't yet tested it because I'm at work. Let me know if it works or not :)

**Comment by ShaneSik** [comment]
I've tested it for you and can confirm it is working now, thanks man! :) Now just the issue with the example key is important, as i have to trade keys with everyone recieving that example crate key. Thanks for the GUI time fix :D

**Comment by ShaneSik** [comment]
Will the next snapshot have the example crate fix? It seems to regenerate with every reload/restart or whatever, it comes back :/

**Comment by ConnorLinfoot** [comment]
I'm hoping it'll be sorted very soon. I'm trying to decide the best way to handle the config. There may just be an empty config with the example one on the Spigot page.

**Comment by ConnorLinfoot** [comment]
Give snapshot 13 a try for me, let me know if you can remove the example crate now.

**Comment by ShaneSik** [comment]
My host seems to have problems currently, when my server is up again i'll try the next snapshot and let you know. It will be today. I'm able to remove the example crate, but it comes back after sometime.

**Comment by ShaneSik** [comment]
I uploaded the new version to FTP, didn't delete the config and restarted my server. Then i deleted the example crate, restarted the version and until now it didn't came back, so it looks good. If it comes back i'll let you know but i think the issue is gone now. :D

**Comment by ConnorLinfoot** [comment]
Great! :D
