### ISSUE TITLE
Suggestion (Opener, Text, color, holographics)

### ISSUE THREAD

**Issue by IRAQIG4MER** [ConnorLinfoot/CratesPlus#242]
Amazing plugin, Thank you
I hope you add some stuff like:
1. HolographicsDisplay per Crate (so we can make our own names)
2. Change "COLOR" to normal colors so we can add like &a&l (with BOLD)
3.give us full custimize on the TEXT like Prize menu text and those things
** and i would like to now how can i make my own "Opener"
and Thank you again. I hope you make a new update with the things i just told you about it will be amazing ♥

**Comment by njstat** [comment]
I like this suggestion. Would love if it was added

**Comment by ConnorLinfoot** [comment]
1. Holograms per plugin have existed since 4.1, it's just a "Holograms" option with a list.
2. The names of crates won't support colours as it just adds more complexity to parts, you can use holograms as mentioned above to have the same feature.
3. More options are going to be in 4.2 for configuring messages, I'll leave this open until that releases :P

**Comment by ConnorLinfoot** [comment]
Also as for openers, there is some docs here - https://github.com/ConnorLinfoot/CratesPlus/wiki/Custom-Openers

**Comment by IRAQIG4MER** [comment]
Thank you for answering me, just one thing..
1. its Holograpics per "Crate" not plugin, i mean i can't use hologram and change the text for each one of them its just like official, when i change it.. it will changed for all of them not for one of them, in my crates warp i'd like to make like this "&e&lVote Crate &7(key)" and for another one.. another color like this "&c&lPickaxe Crate &7(key)", #1 first issue i cant make the crate name "BOLD" and you talked about this and this is ok, but the second thing it will looks like this 



Thank you for answering me, just one thing..
1. i meant Holograpics per "Crate" not per plugin, i mean i can't use holographics and change the text for each one of them its just like official (1 option for all of them), when i change it.. it will change for all of them not for one of them, i can use Holographics by my self above each crate and make my own text colors, but i'd like to depend on your plugin.. that why i hope you make the plugin support Colors for all the text.
2. you said names of Crates won't support Colors.. that why i wanted to make the holographics per crate not on all of them so i can make it like this
- Vote crate:
    Holograpichs:
     - '&e&lVote Crate &7(key)'
     - '&c&lRight-Click to.....'
- Pickaxe Key
   Holograpics:
   - ''&c&lPickaxe Crate &7(key)'
   - '...........'
instead of doing this:
- Vote crate:
    Holograpichs:
     - '%type% &e&lCrate &7(key)'
     - '&c&lRight-Click to.....'
that what i meant.. so i cant make my own style on each crate.
i hope you can make it, And thank you for adding this issue to CratesPlus Version 4.2 and keep it opened ♥
my problem: http://imgur.com/B2CAHxt

**Comment by IRAQIG4MER** [comment]
Thank you for answering me, just one thing..
1. i meant Holograpics per "Crate" not per plugin, i mean i can't use holographics and change the text for each one of them its just like official (1 option for all of them), when i change it.. it will change for all of them not for one of them, i can use Holographics by my self above each crate and make my own text colors, but i'd like to depend on your plugin.. that why i hope you make the plugin support Colors for all the text.
2. you said names of Crates won't support Colors.. that why i wanted to make the holographics per crate not on all of them so i can make it like this
- Vote crate:
    Holograpichs:
     - '&e&lVote Crate &7(key)'
     - '&c&lRight-Click to.....'
- Pickaxe Key
   Holograpics:
   - ''&c&lPickaxe Crate &7(key)'
   - '...........'
instead of doing this:
- Vote crate:
    Holograpichs:
     - '%type% &e&lCrate &7(key)'
     - '&c&lRight-Click to.....'
that what i meant.. so i cant make my own style on each crate.
i hope you can make it, And thank you for adding this issue to CratesPlus Version 4.2 and keep it opened ♥
my problem: http://imgur.com/B2CAHxt

**Comment by ConnorLinfoot** [comment]
Holograms are per crate, that's what I meant xD

They were added from issue #183

**Comment by IRAQIG4MER** [comment]
Oh Nice, but its not showen in my config, i downloaded the latest version.
can you give me example on the new config or something

**Comment by IRAQIG4MER** [comment]
I think you mean, i have to add it by my self like this
Default Hologram Text:
- '   %crate% Crate'
- '&7&lRight-Click to Open!'
- '&c&lLeft-Click to Preview!'
Default Cooldown: 5
Crates:
  Vote:
    Key:
      Item: TRIPWIRE_HOOK
      Name: "\xa7e\xa7lVote Crate \xa77(key)"
      Enchanted: true
    Knockback: 2.0
Default Hologram Text:
- '   %crate% Crate'
- '&7&lRight-Click to Open!'
- '&c&lLeft-Click to Preview!'
    Broadcast: true
    Firework: true
    Preview: true
    Block: CHEST
    Color: YELLOW
    Winnings:

is it right?

**Comment by IRAQIG4MER** [comment]
I copied the same text from http://pastebin.com/grPRrSXp
and its didnt work, btw i changed my Version to 4.1.0 to try it
it didnt work!, I hope you can help me, im sorry i asked a lot

**Comment by ConnorLinfoot** [comment]
Looks like there is an issue that it doesn't work if you have a name with capitals in. I've fixed this in the next 4.2 snapshot.

**Comment by IRAQIG4MER** [comment]
ok, Thank you again for everything.
We all are waiting the Next 4.2 Snapshot
