### ISSUE TITLE
Opening Issue

### ISSUE THREAD

**Issue by King-Aureus** [ConnorLinfoot/CratesPlus#247]
Hello, I am getting only binary (weird symbols) when I open the config file in notepad++.

Pastbin: http://pastebin.com/Makxhbgc

**Comment by ConnorLinfoot** [comment]
You're not trying to open the config file. You're trying to open the jar...

**Comment by KennethDev** [comment]
And may I add that that isn't binary?

**Comment by ConnorLinfoot** [comment]
No you may not add nerd @KennethDev
