### ISSUE TITLE
Can't execute the .jar file.

### ISSUE THREAD

**Issue by King-Aureus** [ConnorLinfoot/CratesPlus#248]
When I try to execute the .jar file, I get this:

http://prntscr.com/bkmjww

**Comment by ConnorLinfoot** [comment]
Nah I'm out.

**Comment by King-Aureus** [comment]
What's that supposed to mean? = / Are you not going to help me? That's quite rude.

**Comment by ConnorLinfoot** [comment]
No cause you clearly don't know how a plugin works fam.
