### ISSUE TITLE
Suggestion for crate winning system.

### ISSUE THREAD

**Issue by dudemanmax49** [ConnorLinfoot/CratesPlus#249]
Amazing plugin, especially for free. Thank you again.

My suggestion is that you make it configurable so that it will slow down as the crate reaches the winning item. So for the roulette style, it would slow down before stopping on the random item, possibly for the csgo opener as well.

Also,

Would it be possible to add a TF2 style crate opening?

Thanks!

**Comment by ConnorLinfoot** [comment]
I'm not currently accepting opener suggestions here. However I will be improving the CSGO opener and adding more openers at a later date.
