### ISSUE TITLE
Item Dupe Glitch

### ISSUE THREAD

**Issue by BlueGoldenKnight** [ConnorLinfoot/CratesPlus#25]
Every Crate Plugin I've gone through, has had the same glitch. I've contacted every author/dev, and they don't respond. So, I'm hoping you would respond back with an easy fix, or update.

When creating a crate, you have to setup the items being won. And when you place it, then you right click to see the items being "won", players are able to click and take them out. And it can be easily duped, and worse if the server is using the plugin for OP items, it can just go on and on. 
Also, when using a crate key and winning, you can take the glass panes with you. This isnt much as a problem then the actual duping from the preview. 

Can you add a way to disable previews? Or Disable a way of haveing the GUI, and giving the items to the player instantly. Or setting up a On Click function ( Crate Key ), of when it is click, it proccedes with custom commands that can be set up with commands or the config.

Thanks! 

-BGK- 
If you want to see the glitch in person, please join mc.blueblix.com:25584, and mail "BlueGoldenKnight" and tell me that you are who you are, and I will enable the plugin to show you. It is currently disabled till fixed.

**Comment by ConnorLinfoot** [comment]
It shouldn't be an issue.

The event in Bukkit (InventoryClickEvent) is being cancelled by the plugin. The issue would be relating to another plugin re-enabling it for some reason.

**Comment by BlueGoldenKnight** [comment]
Heres the list of plugins I have, if you can, can you tell which has the InventoryClickEvent re-enabled?

Plugins: AncientGatesReloaded, AreaShop, Auctions, Backpacks, CasinoSlots, Citizens, Clearlag, CombatTagPlus, Commandspy, CrackShot, CrackshotShop, CratesPlus (Duh), CreativeControl, DrugMeUp, Essentials, EZRanksLite, FactionChat, FamoustLottery, FeatherBoard, FurnitureLib, GAListener, GUIShop, Holographic Displays, ImageOnMap, Jobs, LibsDisguises, MassiveCore, mcMMO, MobCatcher, Multiverse-Core, NameTagEdit, NoCheatPlus, ObsidianBreak, PermissionsEx, PlayerHeads, Plugman, ProtocolLibs, Rape(My Plugin... Doesn't have Click Event), RedeemableMCMMO, ScheduledAnnouncer, ServerSigns, ServerTutorial, SignEdit, Spawner, TitleManager, VIPParticles, Votifier, WorldBoarder, WorldEdit, and WorldGuard.


The plugins I'd believe would be the problem would be GUIShop, VIPParticles, and Backpacks.
These all contain some sort of GUI, where players need to reach and click. Now that I think of it, it could be Backpacks, because GUIShop, players can't take out the items, unless its really laggy and it saves some of the item data taken by the player and it dupes it. VIPParticles sometimes glitches out every time you change your particles around players, the item you clicked on drops, but Backpacks has it where players can take stuff our and place it in, like a backpack. 

Is there anything I can fix this?

**Comment by ConnorLinfoot** [comment]
You'll have to look into it and sort it yourself. Don't have the time to go through all of your plugins to fix an issue for you with your server.
