### ISSUE TITLE
Config issue

### ISSUE THREAD

**Issue by AdamIanMurphy** [ConnorLinfoot/CratesPlus#250]
**Please use the issue template below. Issues not using the templates will likely be closed! If you are suggesting a feature you do not need to follow the template.**

From version 4.2 Snapshot 1 there is a new '/cratesplus debug' command. Running this will give you a single link with all the data I need to help you. If you submit that you won't need to submit your plugin list, version, or any files.

### Link/paste of stack trace (if any)

    You can also simply just use code formatting in markdown!
___We need all of the stack trace! Do not cut off parts of it.___

https://mcdebug.xyz/cratesplus/7

Thanks!

**Comment by ConnorLinfoot** [comment]
You haven't specified a problem..

**Comment by AdamIanMurphy** [comment]
Oh crap, my bad, So basically im getting a YAML issue in the main config, where the crates are. Im not to good with YAML, i cant find the issue.
