### ISSUE TITLE
Config issue w/ Information this time.

### ISSUE THREAD

**Issue by AdamIanMurphy** [ConnorLinfoot/CratesPlus#251]
https://mcdebug.xyz/cratesplus/8

Ill try this again since you never did give me a chance to follow up with your "You have not specified the problem.." comment. Its an issue in the config.yml, I was editing it and when i restarted to see the changes i had made, the crates where empty, im not sure what the issue is. 

Thanks!

Also sorry, your the first plugin ive had to post a issue request for, so im new to this! <3

**Comment by ConnorLinfoot** [comment]
Your config file doesn't have any crates. That's the issue..

**Comment by AdamIanMurphy** [comment]
Ok, then ill send the file its self 
[config.zip](https://github.com/ConnorLinfoot/CratesPlus/files/333084/config.zip)

**Comment by AdamIanMurphy** [comment]
[config.zip](https://github.com/ConnorLinfoot/CratesPlus/files/333087/config.zip)

Not sure what happend, because thats them there

**Comment by ConnorLinfoot** [comment]
It's an invalid YAML - http://yaml-online-parser.appspot.com/

Make sure you're not adding in extra spaces etc
