### ISSUE TITLE
Player not found

### ISSUE THREAD

**Issue by mcbleazz** [ConnorLinfoot/CratesPlus#256]
![xh-5hfk_47m](https://cloud.githubusercontent.com/assets/20269846/16546895/1a06e0be-4162-11e6-8b87-5c9544ecac73.jpg)

I use ChestCommands to sell keys:
crate1cmd:
  COMMAND: 'op: crate key {player} crate1'
  NAME: '&a150'
  LORE:
    - 'Buy key'
  PRICE: 150
  ID: '280'
  KEEP-OPEN: true
  POSITION-X: 1
  POSITION-Y: 1

Sometimes when someone buy keys, your plugin writes player not found. Also tried console: crate key {player} crate1

Help me, please

**Comment by ConnorLinfoot** [comment]
First of all, please follow the format next time. Second of all, actually check the list of placeholders, you're not even entering correct placeholders.
