### ISSUE TITLE
GUI Time in v4.1.0+

### ISSUE THREAD

**Issue by N1CK1238** [ConnorLinfoot/CratesPlus#258]
Hello,

I am wondering if you removed the GUI Time feature in v4.1.0 because I can't normally find it in the config.yml file. In version v4.0.0, it would be near the top of the text file. If you have not removed the feature but simply moved its location, I would like to know its current file location.

Thanks.

**Comment by ConnorLinfoot** [comment]
Read the changelog, options were moved to specific openers - https://www.spigotmc.org/resources/cratesplus-free-crates-plugin-1-8-1-9-1-10.5018/updates
