### ISSUE TITLE
Experiencing deleted rewards when messing with individual item percentages

### ISSUE THREAD

**Issue by Pr0Pancakes** [ConnorLinfoot/CratesPlus#260]
Hello! It seems when I try to edit my reward percentages from the config.yml it causes some of my other rewards to not appear at all. Such as editing the diamond chestplate to have a %10 drop chance may cause half the chest to completely disappear  and unregister as rewards.

Plugin list - https://gyazo.com/de8f3cc50a21c704e8e185aaf5c540d3

Action to reproduce - Edit the percent of an in-game reward and reload using the CratesPlus reload command.

CratesPlus version - Latest, just downloaded from spigot today 7/6/2016

Crates config.yml  https://www.dropbox.com/s/hwbtg1ghaiwh2h9/config.yml?dl=0

Crates data.yml https://www.dropbox.com/s/a7pjwezhwxvexde/data.yml?dl=0

**Comment by ConnorLinfoot** [comment]
Percentages must not add up to more than 100%, if they do some rewards won't display. That's most likely your issue.

**Comment by Pr0Pancakes** [comment]
That was the issue! thanks for the help.
