### ISSUE TITLE
How to make money reward?

### ISSUE THREAD

**Issue by NicoFilippo** [ConnorLinfoot/CratesPlus#261]
### Plugin list:
CratesPlus, WorldEdit, Essentials, CustomItems, ClearLag, PermissionsEx, Friends 2, mcMMO, NametagEdit, Vault, SkinManager, MassiveCore, Multiverse-Core, ProtocolLib, WorldGuard, LibsDisguises, Citizens, Factions, MyPet, SignColors, Chectcommands, MythicMobs, Multiverse-Portals

### CratesPlus Version:
4.1.1

### CratesPlus config.yml
_the same as default, i didn't change it_

### CratesPlus data.yml
_the same as default, i didn't change it_

I simply don't understand this layout :D. I need help - I don't know how to make it so reward is money. I saw his plugin on many servers with money rewards. Command for adding money is /eco give %name% [VALUE etc. 20], but I don't know how to give it to the game! Please, help

**Comment by dado243** [comment]
Same thing here retards don't have time to make wiki.

**Comment by NicoFilippo** [comment]
Chill out, @dado243 , there is no need to be mean...

There's no need for wini, just make a little tutorial on main SPIGOT page.

**Comment by ConnorLinfoot** [comment]
The config is quite simple, I'd recommend just using the example configuration for help.

**Comment by NicoFilippo** [comment]
The example is not working no matter what I do...
