### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by shootcraft** [ConnorLinfoot/CratesPlus#264]
hologram is not working in 1.10.2 spigot, I am using crateplus 4.1.1 and when I perform /crate reload, winning items disappear

**Comment by ConnorLinfoot** [comment]
Follow the template for goodness sake.

**Comment by shootcraft** [comment]
https://mcdebug.xyz/cratesplus/12v please fix hologram is not working

**Comment by ConnorLinfoot** [comment]
You'll need to install HolographicDisplays or IndividualHolograms

**Comment by shootcraft** [comment]
I got installed plugin https://www.spigotmc.org/resources/holograms.4924/

**Comment by ConnorLinfoot** [comment]
It doesn't support that plugin, you have to use one of the one's mentioned above.

**Comment by shootcraft** [comment]
Oh thanks but Holograms plugin dont have dont have the feature to tranfer data to holograpic display so  I unable to use those plugins, if can add holograms compatible

**Comment by ConnorLinfoot** [comment]
There isn't any reason you shouldn't be able to use multiple hologram plugins.

**Comment by shootcraft** [comment]
you are right but I am trying to minimize my server plugin usage

**Comment by ConnorLinfoot** [comment]
Well unfortunately I won't be adding support for more plugins as there really isn't a need. Adding more plugin integration would make it harder to test and keep track of.

**Comment by shootcraft** [comment]
By the way nice plugin it is easy to setup crate I liked it thanks for support
