### ISSUE TITLE
Bugged Config.

### ISSUE THREAD

**Issue by Koncealed** [ConnorLinfoot/CratesPlus#266]
Some some reason sometimes certain things get bugged in my crates. Now its this tester one

Error: http://hastebin.com/arukayarik.avrasm

config.yml http://hastebin.com/ahapolotoh.apache

It also resets my things back to item instead of commands when this happens. This is literally the 4th time I had to redo this config. This is bugged with tester.

**Comment by ConnorLinfoot** [comment]
You have characters not contained in strings which are invalid, in specific the § character.
