### ISSUE TITLE
Crate not opening for normal players, only ops, no error messages, can preview

### ISSUE THREAD

**Issue by Egolfius** [ConnorLinfoot/CratesPlus#267]
**Please use the issue template below. Issues not using the templates will likely be closed! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

From version 4.2 Snapshot 1 there is a new '/cratesplus debug' command. Running this will give you a single link with all the data I need to help you. If you submit that you won't need to submit your plugin list, version, or any files.

### Link/paste of stack trace (if any)

    You can also simply just use code formatting in markdown!

**No stack trace**

### Plugin list:
worldguard, worldedit, worldborder, mcmmo, votifier, vault, ultracosmetics, towny, simple reserve, silkspawners, signshop, removerecipes, pvptoggle, plotsquared, permissionsex, mycommand, multiverse-core, modifyworld, messageannouncer, lwc, holograpic displays, gamemodeinventories, galistener, firstjoinplus, essentials, enjinminecraftplugin, durexp, discordmc, customrecipes, customenderchest, crateplus, coreprotect, commandcooldown, coloredtablist, clearlag, chestcommands, autorank, apply, actionannouncer

### Actions to reproduce (if known):
Previews work for both op and non-op. Only op can open crate with key. There is no error message from this or any other plugin, there is nothing in console.

### CratesPlus Version:
4.1.1

### CratesPlus config.yml
http://pastebin.com/u6R5tvwg

### CratesPlus data.yml
http://pastebin.com/2TzuMkPk

**Comment by Egolfius** [comment]
Additionally:

My main account, Egolfius, can open the crates regardless of if he is op or not. If I deop Egolfius and open a crate, non-ops can open crates. This resets after I do /crate reload

**Comment by ConnorLinfoot** [comment]
This issue seems like it's something to do with another plugin, if there isn't any errors nothing in CratesPlus should be causing this.
