### ISSUE TITLE
Players can preview then steal items from crates

### ISSUE THREAD

**Issue by LogandadLoga** [ConnorLinfoot/CratesPlus#268]
### Problem:

Players are able to preview the items and take them out of the chest then use them and even
get more once they lose them..... I tried resetting the crates, Didn't work so i put it back
I dont know whats wrong with it. Its the latest version

No stack trace at all

### Plugin list:
Worldedit Adminfun Colored signs
Chatcolor2 Essentials BarAPI Groupmanager
PlaceHolderAPI BuycraftX Votifier
TablistPrefix Protocollib
renametool  MassiveCore SimpleBackup
Obsidian breaker trollcommandsplus
hub factions pvpmanger and of course
truly crates plus

### CratesPlus Version:
4.1.1

### CratesPlus config.yml
http://pastebin.com/4WNjMsaV

### CratesPlus data.yml
http://pastebin.com/w6SQ4BL5

### Contact

  Contact me at logandadloga.logandadloga on skype if you
 want me to show you the problem

**Comment by ConnorLinfoot** [comment]
If this is happening and there isn't an error there is likely another plugin causing an issue, if you can't find the plugin you can disable previews of the crates.
