### ISSUE TITLE
hologram stay

### ISSUE THREAD

**Issue by mat41997** [ConnorLinfoot/CratesPlus#269]
### Link/paste of stack trace (if any)
no error in console

![2016-07-17_21 09 25](https://cloud.githubusercontent.com/assets/5884000/16902596/e67a41ca-4c63-11e6-9a47-3b5ff73b94b4.png)

    You can also simply just use code formatting in markdown!
___We need all of the stack trace! Do not cut off parts of it.___

### Plugin list:
___A list of your plugins___
https://timings.aikar.co/v2/?id=0f311282e19f4dccb069636a39c69b77&section=plugins

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
place a crateplus chest
break this chest of the diamond_axe - enchant silk touch

(i know, this is a SilkChests plugin bug)
http://dev.bukkit.org/bukkit-plugins/silkchests/

### CratesPlus Version:
___This can be found by running `/version CratesPlus` on your server.___
4.1.1

### CratesPlus config.yml
___Please upload to pastebin.com and provide link___
http://pastebin.com/Q6Y3gcvc

### CratesPlus data.yml
___Please upload to pastebin.com and provide link___
Crate Locations:
  s1:
  - world|2175|103|-1545

**Comment by ConnorLinfoot** [comment]
Did you try restarting the server? If it's still there please post your latest server.log.

**Comment by mat41997** [comment]
ok, i restart server and hologram faded

**Comment by ConnorLinfoot** [comment]
Try stopping the server, clearing out the data.yml and starting it again.

**Comment by mat41997** [comment]
thx ^^
