### ISSUE TITLE
CratesPlus incompatible with written books and enchanted books

### ISSUE THREAD

**Issue by N1CK1238** [ConnorLinfoot/CratesPlus#270]
Not sure if this is an issue or a feature request, so if this is an issue, then I apologize for not using the template. 

Anyways, I would like the plugin to be compatible with written and enchanted books, as currently up to 4.1.1, it doesn't seem to work with written and enchanted books.

Screenshot of the plugin not compatible with them: http://imgur.com/a/3mRNo

Thank you!

EDIT: It seems that the second and first photo are mixed up. If you are wanting to see the steps I did, the correct order is the second photo, first photo, and then the third photo.

**Comment by ConnorLinfoot** [comment]
Part of #235 really. I'm wanting to wait on Spigot to implement an API for NBT data but they still haven't done so. I plan on looking into support for items like this when I can. The best idea for now is to generate a give command and use the command item type.

**Comment by N1CK1238** [comment]
After doing some research on ID numbers for separate enchanted books, they appear to have the ID of "403" no matter what enchantments it is holding on to. So I'm afraid that the give command will not work, and that we must wait for Spigot to implement an API for NBT data. :(
