### ISSUE TITLE
How do I disable the Holograms feature?

### ISSUE THREAD

**Issue by MitchellJ8** [ConnorLinfoot/CratesPlus#271]
I was just wondering - What would I have to do to the default configuration to remove the Holograms feature. I have my own pre-finished per crate Holograms I made and have no use for the ones that are generated in the plugin. Everything I've tried hasn't worked.

**Comment by ConnorLinfoot** [comment]
Make sure there isn't any holograms per crate then under the default holograms option change it so it looks like the below;

    Default Hologram Text: []

instead of;

    Default Hologram Text:
    - "%crate%"
    - "Right-Click to Open!"
    - "Left-Click to Preview!"

**Comment by MitchellJ8** [comment]
Thank you! I'll pull this soon - just going to leave it until I finish my configuration incase I screw something up!
