### ISSUE TITLE
Silkspawners rewards not working

### ISSUE THREAD

**Issue by NotableOsprey92** [ConnorLinfoot/CratesPlus#272]
### Plugin list:
http://imgur.com/edit

### Actions to reproduce (if known):
when I put a working silk spawner in the crate rewards and a player wins it and when they place the spawner turns into a standard pig spawner even if the item name is cow spawner. The way I put the spawner in the rewards section by /crate settings. Basically spawner rewards arent keeping the the same as when put in I think.

### CratesPlus Version:
4.1.1
### CratesPlus config.yml
http://pastebin.com/W2eLEB0i

### CratesPlus data.yml
http://pastebin.com/j1zNzU79

**Comment by ConnorLinfoot** [comment]
You have to use commands for something like this.
