### ISSUE TITLE
Regular chest when opened???

### ISSUE THREAD

**Issue by Typosch** [ConnorLinfoot/CratesPlus#273]
**Please use the issue template below. Issues not using the templates will likely be closed! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

From version 4.2 Snapshot 1 there is a new '/cratesplus debug' command. Running this will give you a single link with all the data I need to help you. If you submit that you won't need to submit your plugin list, version, or any files.

### Link/paste of stack trace (if any)
???
### Plugin list:
http://pastebin.com/5srzKkNv

### Actions to reproduce (if known):
http://imgur.com/C95i1o3 
It seems to make it a regular chest but with the same name. When I left-click it says "Sneak to break crates"

### CratesPlus Version:
4.1.1

### CratesPlus config.yml
http://pastebin.com/0U7KLHia

### CratesPlus data.yml
http://pastebin.com/eGRHvdXR

**Comment by Typosch** [comment]
The config seemed to get reset after I restarted my server

**Comment by ConnorLinfoot** [comment]
I don't get what your issue is?

**Comment by Typosch** [comment]
When I try to open the chest with a key it opens as a regular chest

**Comment by ConnorLinfoot** [comment]
Well the config file you linked has no crates in it so I can't really help you.
