### ISSUE TITLE
My config is not working

### ISSUE THREAD

**Issue by NotableOsprey92** [ConnorLinfoot/CratesPlus#275]
my config is not working and ive spent 2 hours plus troubleshooting it but nothings working but what I have found out its some thing to do with rewards 22,23,24 and 25 in the vote crate.

### CratesPlus Version:
4.1.1

### CratesPlus config.yml
Link 1: http://pastebin.com/qSJzezaQ
Link 2: http://pastebin.com/eJMhhm6q ( difference is with dash [-] when listing the commands in the  reward has to execute when won)

**Comment by ConnorLinfoot** [comment]
Your config isn't a valid YAML.

**Comment by NotableOsprey92** [comment]
whats invalid with the config thats what im asking i already now its not correct thats why im making this issue

**Comment by NotableOsprey92** [comment]
it said this:

ERROR:

while parsing a block mapping
  in "<unicode string>", line 39, column 7:
          '1':
          ^
expected <block end>, but found '<scalar>'
  in "<unicode string>", line 257, column 8:
          '23':
           ^

wich is no where near the problem.

**Comment by NotableOsprey92** [comment]
oh wait i just noticed something bare with me

**Comment by NotableOsprey92** [comment]
nope its nothing but i dont understand the error because those lines are no different than the others except from the number.

**Comment by ConnorLinfoot** [comment]
Well YAML errors aren't a fault of the plugin so I don't really help with it.

**Comment by NotableOsprey92** [comment]
so what do i do

**Comment by ConnorLinfoot** [comment]
Fix it...

**Comment by NotableOsprey92** [comment]
the problem is with these.

      '22':
        Type: COMMAND
        Item Type: PAPER
        Percentage: 1
        Commands:
        - '/couponsplus give %name% 10k 1
        Item Data: 0
        Name: 10K
        Amount: 1
        Enchantments: []
        Lore: []
      '23':
        Type: COMMAND
        Item Type: PAPER
        Percentage: 1
        Commands:
        - '/couponsplus give %name% 100mcmmo 1
        Item Data: 0
        Name: 100 Mcmmo
        Amount: 1
        Enchantments: []
        Lore: []
      '24':
        Type: COMMAND
        Item Type: PAPER
        Percentage: 1
        Commands:
        - '/couponsplus give %name% 10mcmmo 1
        Item Data: 0
        Name: 10 mcmmo credits
        Amount: 1
        Enchantments: []
        Lore: []
      '25':
        Type: COMMAND
        Item Type: PAPER
        Percentage: 1
        Commands:
        - '/couponsplus give %name% rookie_tag 1
        Item Data: 0
        Name: ROOKIE [TAG]
        Amount: 1
        Enchantments: []
        Lore: []
      '26':
        Type: COMMAND
        Item Type: MOB_SPAWNER
        Percentage: 1
        Commands:
        - 'ss give %name% spider'
        Name: '&e&lSpider Spawner'
        Item Data: 0
        Amount: 1
        Enchantments: []
        Lore: []

**Comment by NotableOsprey92** [comment]
they are all command rewards adn i havent been able to get a single reward work before the problem happend

**Comment by NotableOsprey92** [comment]
ive rememoved those rewards and added the default command reward from the default config on the plugin thread the the issue happens so the bug that when you have command rewards in your config it dose make the plugin glitch out.

**Comment by ConnorLinfoot** [comment]
There isn't an issue with the plugin, you're making the YAML invalid.

**Comment by ConnorLinfoot** [comment]
Post the config file you are trying.

**Comment by NotableOsprey92** [comment]
http://pastebin.com/EhxSRSFM

**Comment by ConnorLinfoot** [comment]
It's still invalid YAML, try this tool instead (seems more helpful) http://codebeautify.org/yaml-validator

Also as stated here https://github.com/ConnorLinfoot/CratesPlus/wiki/Configuration it's best not to use characters such as §

**Comment by NotableOsprey92** [comment]
my error but im not sure about it?

**Comment by NotableOsprey92** [comment]
Error : Malformed inline YAML string ('/couponsplus give %name% 10k 1) at line 251 (near "- '/couponsplus give %name% 10k 1").
Line : 251  - '/couponsplus give %name% 10k 1

**Comment by NotableOsprey92** [comment]
its with all 22-26

**Comment by NotableOsprey92** [comment]
it its always with the command listing section even with the one from the default config

**Comment by ConnorLinfoot** [comment]
They're not indented correctly. It literally tells you that.

Locking this because you're asking trying to get basic support just for writing a file and I don't have time to help someone that literally hasn't even taken the time to read the basic wiki on YAML and configuration files.
