### ISSUE TITLE
I don't understand how to set percentages on getting a certain item from a crate.

### ISSUE THREAD

**Issue by TexTex** [ConnorLinfoot/CratesPlus#276]
QUICK NOTE: I see in the config that you can setup the %percentage% but I don't know how to use it

**Please use the issue template below. Issues not using the templates will likely be closed! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

From version 4.2 Snapshot 1 there is a new '/cratesplus debug' command. Running this will give you a single link with all the data I need to help you. If you submit that you won't need to submit your plugin list, version, or any files.

### Link/paste of stack trace (if any)

    You can also simply just use code formatting in markdown!
___We need all of the stack trace! Do not cut off parts of it.___
???

### Plugin list:
___A list of your plugins___
Just started server, only CratePlus and Essentials and Pex

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### CratesPlus Version:
___This can be found by running `/version CratesPlus` on your server.___
4.1.1

### CratesPlus config.yml
___Please upload to pastebin.com and provide link___
http://pastebin.com/gTFZDed3

### CratesPlus data.yml
___Please upload to pastebin.com and provide link___
http://pastebin.com/AstYksRF

**Comment by ConnorLinfoot** [comment]
https://github.com/ConnorLinfoot/CratesPlus/wiki/Configuration
