### ISSUE TITLE
Suggestion + Issue: Broadcast Outline & Dyed Leather Armour

### ISSUE THREAD

**Issue by DumplingsWithToads** [ConnorLinfoot/CratesPlus#278]
Option to remove or change broadcast outline.
https://i.gyazo.com/794c0b8d43578bacc2ab827e771908b6.png

Dye on leather armor gets removed when put into crate.
http://obviousprison.com/assets/vid/CratesPlus.mp4

Plugin Version: 4.1.1
Server Version: 1.8.8

Sorry for not following the template, here is a puppy image in case you are angry at me: http://obviousprison.com/assets/img/misc/puppy.jpg

**Comment by ConnorLinfoot** [comment]
Dyed leather armour falls into issue #235 and will be done one day. For now I'd recommend using commands. As for the broadcast outline I'll remove it in 4.2 and then you can add it back yourself and customize it :)
