### ISSUE TITLE
SilkSpawners not working with CratesPlus

### ISSUE THREAD

**Issue by star6122** [ConnorLinfoot/CratesPlus#279]
**Please use the issue template below. Issues not using the templates will likely be closed! If you are suggesting a feature you do not need to follow the template.**
Hello!
I am trying to use silkspawners to set rewards in CratesPlus. Everytime I try to do, I place down the spawner I get and it says "Placing Default Spawner (either this spawner is invalid or disabled).

Plugin list:
McGroovy
WorldEdit
PerWorldChat
WorldManager
Essentials
ClearLag
AdvancedSideBarBukkit
TNTFill
Multiverse-Core
Multiverse-SignPortals
EssentialsChat
PermissionsEx
PerWorldTablist
Vault
EssentialsSpawn
MassiveCore
MassiveTickets
MassiveHats
CreativeGates
HolographicDisplays
Factions
MassiveBooks
Vampire
CratesPlus
SilkSpawners
InfoBoardReborn

An Image:
![2016-07-22_12 30 44](https://cloud.githubusercontent.com/assets/8398301/17064000/35d2897e-5008-11e6-8b24-fb1fb0837e09.png)

CratesPlus Version:
4.1.1

CratesPlus config.yml
http://pastebin.com/6kWpCfvF

CratesPlus data.yml
http://pastebin.com/20sbWig0

Thanks!!

**Comment by ConnorLinfoot** [comment]
You should use commands, not give it as an item.
