### ISSUE TITLE
Playerheads and or Permissions through crates

### ISSUE THREAD

**Issue by Kulenful** [ConnorLinfoot/CratesPlus#280]
I Have tried to add so i could get my own skin head through crates, but it just doesnt work, nor can i give permissions through crates, I changed it to be a Command but it just doesn't work. 

Video Crate test: 
https://youtu.be/47NxCvVQKAM

### Plugin list:
CoreProtect, VoteCommand, Wild, Beast-XpWithDraw, WorldEdit, Chatcolor2, Essentials, ClearChat, iConomy_Recreation, GroupManager, Broadcast, HolographicDisplays, BuycraftX, Broadcaster, Lockette, Votifier, SimplePets (Inactive), WorldGuard, aAntiSpam, ImageOnMap, EssentialsChat, mcMMO, SuperVanish, AdminShop, Vault, GAListener, ChairStairs, MyCommand, EssentialsSpawn, CustomEnchantments, CratesPlus, ChestShop, AreaShop, CombatLog, ArmorStandTools, Jobs, Banknotes, Silkspawners, Auctioneer. CSGO-CratesPlus, Citizens, AuctionHouse, Ontime, CommandNPC, Towny, TownyChat

### CratesPlus Version:
4.1.1

### CratesPlus config.yml
http://pastebin.com/ZFnVckBC

### CratesPlus data.yml
http://pastebin.com/2g2iMUsZ

**Comment by ConnorLinfoot** [comment]
It's probably a good idea to read the top of the config file with the list of placeholders...
