### ISSUE TITLE
Players Cant Open Crates

### ISSUE THREAD

**Issue by ItsThatGamer** [ConnorLinfoot/CratesPlus#281]
Hello everyone who is not OP on my server can not open the crates in the CratePlus V4.1.1 I don't know what permissions to add to the groups

**Comment by Kulenful** [comment]
are you using WorldGuard?

**Comment by Kulenful** [comment]
Or some kind of claim plugin

**Comment by ItsThatGamer** [comment]
yes worldgaurd

**Comment by ItsThatGamer** [comment]
but I have interact on

**Comment by Kulenful** [comment]
do /region setpriority (Region) 1 (Or higher than __Global__ atleast)

**Comment by ItsThatGamer** [comment]
ok

**Comment by Kulenful** [comment]
does it work?

**Comment by ItsThatGamer** [comment]
no

**Comment by Kulenful** [comment]
can i get ip so i could check it out?

**Comment by ItsThatGamer** [comment]
it still doesn't work

**Comment by DumplingsWithToads** [comment]
try adding the flag to the __global__ region?

**Comment by ItsThatGamer** [comment]
how do I do that?

**Comment by DumplingsWithToads** [comment]
/rg flag __ _global_ __ chest-access allow

**Comment by ItsThatGamer** [comment]
i don't have a global region

**Comment by DumplingsWithToads** [comment]
did you add the underscores?

**Comment by ItsThatGamer** [comment]
yeah?

**Comment by ItsThatGamer** [comment]
didn't work

**Comment by DumplingsWithToads** [comment]
Just to verify because you should have a global region.
\/ Is this the command you uses? \/
https://i.gyazo.com/8423d54561b7804bf9ba0f934ce700a1.png

**Comment by ItsThatGamer** [comment]
ok i did the command but it stil doesn't work do you have skype?

**Comment by DumplingsWithToads** [comment]
I only have Discord, sorry.

**Comment by ItsThatGamer** [comment]
ok is there a discord i could meet you in?

**Comment by DumplingsWithToads** [comment]
Yeah! https://discord.gg/JUJ5D

**Comment by ItsThatGamer** [comment]
ok I'm in you see me

**Comment by DumplingsWithToads** [comment]
Issue solved!
spawn-protection in server.properties was default but was unneeded because of another protection plugin so spawn-protection was set to 0.

Now, almighty developer close this Issue!

**Comment by ConnorLinfoot** [comment]
@DumplingsWithToads thanks for helping him out :) I'm aware quite a few people have this issue, there's a wiki in-progress for the plugin and I'll make sure to add this to it
