### ISSUE TITLE
Crates are not openable/usable by default users

### ISSUE THREAD

**Issue by MiniCraft12** [ConnorLinfoot/CratesPlus#282]
**Please use the issue template below. Issues not using the templates will likely be closed! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

From version 4.2 Snapshot 1 there is a new '/cratesplus debug' command. Running this will give you a single link with all the data I need to help you. If you submit that you won't need to submit your plugin list, version, or any files.

### Link/paste of stack trace (if any)

Don't know what a stack trace is.

### Plugin list:
Worldedit, TitleMotd,Essentials, Groupmanager, BuyCraftX, ProtocolLib, WorldGuard, iDisguise, NoFall, EssentialsChat, Rename, iConomy, Vault, EssentialsSpawn, MassiveCore, ChestShop, SkyWars, Citizens, Factions, ASkyBlock, Multiverse-Core, Multiverse-Portals, GiantTrees, HolographicDisplays, CratesPlus

### Actions to reproduce (if known):
1. /mandemote (playerusername) Default (In my case demotion from Owner to Default)
2. give crate key through console
3. Right-click crate with correct key
4. No message is displayed in chat and crate does not open or give prize.

### CratesPlus Version:
Version 4.1.1

### CratesPlus config.yml
[CratesPlus data and config.zip](https://github.com/ConnorLinfoot/CratesPlus/files/389248/CratesPlus.data.and.config.zip)
 *this zip includes both config.yml and data.ml

### CratesPlus data.yml
Look above

**Comment by ConnorLinfoot** [comment]
Considering your comment on #195 you are already aware this isn't an issue with the plugin. Probably read https://github.com/ConnorLinfoot/CratesPlus/wiki/Debugging-Issues

**Comment by MiniCraft12** [comment]
ok I removed the world guard from the area

**Comment by MiniCraft12** [comment]
and I works.
