### ISSUE TITLE
Can't upload more than 9 items

### ISSUE THREAD

**Issue by TheWitherinRiser** [ConnorLinfoot/CratesPlus#284]
**Please use the issue template below. Issues not using the templates will likely be closed! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

From version 4.2 Snapshot 1 there is a new '/cratesplus debug' command. Running this will give you a single link with all the data I need to help you. If you submit that you won't need to submit your plugin list, version, or any files.

### Plugin list:
http://imgur.com/a/6GeAx

### Actions to reproduce (if known):
I contacted you earlier of my issue with the item names and enchantment  names of the winnings in my crates, and I changed them all to the proper name. However, whenever I add more than 9 items, they don't show up in the crate when you right click with the crate key or in the preview when you left click. My guess is that the preview area only has enough space for 9 because it's the max amount of boxes that will show, but when you right click it with the key, the other items I have don't show up either. Can you help me add all 21 of my items? Below is an image of the preview with 9 items.
http://imgur.com/a/EO5N8

### CratesPlus Version:
4.1.1

### CratesPlus config.yml
http://pastebin.com/XMnCscnt

### CratesPlus data.yml
Data Version: 2
Crate Locations:
  old:
  - UhcFactions|-86|76|117

**Comment by ConnorLinfoot** [comment]
Probably a good idea if your 10th item wasn't DIAMON_LEGGINGS...
