### ISSUE TITLE
Bruh

### ISSUE THREAD

**Issue by THEggIshao** [ConnorLinfoot/CratesPlus#285]
So i got this problem it never happend before [CratesPlus] CratesPlus does NOT support "1.10-R0.1-SNAPSHOT" if you believe this is an error please let me know!

I dont know if this is an Error [10:35:05 ERROR]: Error occurred while enabling CratesPlus v4.1.0 (Is it up to date?)

**Comment by ConnorLinfoot** [comment]
Lol the error tells you the issue...
