### ISSUE TITLE
Feature Request: Ability to put non-waterbottle potions in crates

### ISSUE THREAD

**Issue by MiniCraft12** [ConnorLinfoot/CratesPlus#286]
Every time I try to put potions from the creative menu into crates they change back to water bottle potions when I preview the crate. This also occurs with various tipped arrows. It would be great if you could add support for all potion and tipped arrow types.

**Comment by ConnorLinfoot** [comment]
It's been requested already, not going to happen any time soon if at all. Use commands instead for now.
