### ISSUE TITLE
Add support for 1.9/1.10 Potion tag and CustomPotionEffects tag.

### ISSUE THREAD

**Issue by Ryan778** [ConnorLinfoot/CratesPlus#287]
In Minecraft 1.9/1.10, the way potions work were changed, and potions are now stored via a Potion tag or CustomPotionEffects tag instead of a data value. Because of this, potions (as well as splash potions, lingering potions, and tipped arrows) are also broken now as well, so it would be nice to have support for these two knew tags.

How to Reproduce: 
Take any spigot client running 1.9 or 1.10 (NOT 1.8)
Create a loot crate with a potion
The potion turns into a water bottle (potion tags not stored)

(currently I'm using the commands tool to run a command to give the potion instead)

**Comment by ConnorLinfoot** [comment]
It's been requested already, not going to happen any time soon if at all. Use commands instead for now.
