### ISSUE TITLE
If I add in all the percentages and commands and reload it only 2 items show up in the crates

### ISSUE THREAD

**Issue by lavainminecraft** [ConnorLinfoot/CratesPlus#288]
If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

From version 4.2 Snapshot 1 there is a new '/cratesplus debug' command. Running this will give you a single link with all the data I need to help you. If you submit that you won't need to submit your plugin list, version, or any files.

### Link/paste of stack trace (if any)

    You can also simply just use code formatting in markdown!
___We need all of the stack trace! Do not cut off parts of it.___

### Plugin list:
coreprotect playerheads worldedit installer adminfun cF_Wild veinminer_for_bukkit barapi quickboard placeholdersapi groupmanager buycraftx votifier ironelevators multiverse-core protocollib worldguard killsplus guiredeemmcmmo mcmmo galistener vault massivecore customtab simplebroadcast essentials epicrename trading banknotes holographicsdisplays whatisit auctionhouse essentialschat playervaults supplycrates essentialsspawn cratesplus factions randompackage obsidiandestroyer silkspawners

### Actions to reproduce (if known):
what you need to do is put any item in one of the crates, go into the config fill in all of the percentages and the commands if any then when done save it and either do /crate reload or reload the server then when you check the crate you edited there's only two crate items there with everything

### CratesPlus Version:
4.1.1

### CratesPlus config.yml
http://pastebin.com/DtCY3WqV

### CratesPlus data.yml
http://pastebin.com/Jmz1rXUX

**Comment by DumplingsWithToads** [comment]
The percentages must NOT add up to more than 100% - Even says it in console when reloading the plugin.

**Comment by lavainminecraft** [comment]
Is there a way to set it to more?

**Comment by DumplingsWithToads** [comment]
Wouldn't think so. Just make all the percentages add up to 100.

**Example**
```
Winnings:
  '1':
    Percentage: 60.0
  '2':
    Percentage: 30.0
  '3':
    Percentage: 10.0
```

**Comment by ConnorLinfoot** [comment]
Best way is to use decimals. For example if you had 3 50% you could just use 3 0.5%
