### ISSUE TITLE
Only being able to recieve 1 item at a time?

### ISSUE THREAD

**Issue by Spazty** [ConnorLinfoot/CratesPlus#289]
Hello, I was wondering if you could add it where players could use multiple keys at once to get items without some of them bugging out when using the crate? Example: I spammed around 25 keys and the crate gave me 1 item, by pressing E they can cancel out of the menu and try and spam and it only gives 1 item in return, I would like it if you could possibly make it where it can handle people spamming the keys?

(I do understand it keeps the keys with you but for some people they are impatient and want to get straight to the items without delay.

**Comment by ConnorLinfoot** [comment]
I don't really think this would benefit too many people and would take more work than it's worth with how openers work. If there issues with people spamming it you can use the Cooldown option to limit how quickly they can open a crate.
