### ISSUE TITLE
Command Ideas.

### ISSUE THREAD

**Issue by GiansCode** [ConnorLinfoot/CratesPlus#29]
Basically,

/crate key <player> <type> <amount> - Give a player more than one key at a time
/crate give all <type> <amount> - Gives everyone online crate key

**Comment by AcesGamingUK** [comment]
i believe "/crate key all [key] " is already a working feature, or at least it works on my server XD

**Comment by ConnorLinfoot** [comment]
"/crate key all [key]" does already exist, "/crate key <player/all> [key] [amount]" has been added in 4.0 (Snapshot 1)
