### ISSUE TITLE
[Feature] Kit Support/Multiple Item Support

### ISSUE THREAD

**Issue by ProXx123** [ConnorLinfoot/CratesPlus#290]
Hi, I'm using thr plugin on my factions server and my friends love it. But one feature that we all wanted was to be able to get a kit. I could add a plugin that would let me assign a command to an item, and add /kit <kitname> then nake it delete itself afterwards, but I am not sure of a plugin to do that nor how to do it myself. So if you could add essentials kits/grouped items/multiple item support that would be fantastic! I am not sure if it is hard or not but if you could possible implement it into the plugin me and my friends would very much appreciate it and I bet other people using this on a factions server would too. Thanks!

**Comment by ProXx123** [comment]
Sorry if some sort of feature like this is already in the plugin, it's just that I'm not good with config files and adding things in manually.

**Comment by ConnorLinfoot** [comment]
This isn't really something that I think should be added, it should be done using a command really.

**Comment by ProXx123** [comment]
What command should I do? I am not sure how to do this and I am new to this kinda stuff :(

**Comment by DumplingsWithToads** [comment]
You can add a command to a winning via the config. Here's a example:

```json
CrateName:
  ...
  Winnings:
    '1':
      Type: ITEM
      Item Type: IRON_SWORD
      Item Data: 0
      Percentage: 25
      **Commands:
        - 'kit <kitname> %name%'**
      Name '&6&lExample Sword'
      Amount: 1
      Enchantments:
       - 'DAMAGE_ALL-3'
      Lore:
       - 'The greatest sword!'
```

**Comment by ProXx123** [comment]
Thanks man :)

**Comment by ProXx123** [comment]
The commands line breaks the connfig... Could you make an example config for me? :(

**Comment by gappleburst** [comment]
Hey um. Idk if anyone is still having trouble with this but I REALLY am. I've tried so many things and I've tired exactly what you said ProXx123, however the command just won't work for me in game. This is my exact config file. I tried to copy it exactly as said in the example and NOTHING is working D; Please help me someone!

 Winnings:
      '1':
        Type: ITEM
        Item Type: IRON_SWORD
        Percentage: 25
        Item Data: 0
        Name: NONE
        Amount: 1
        Enchantments: []
        Lore: []
      '2':
        Type: COMMAND
        Item Type: MOB_SPAWNER
        Percentage: 50
        Commands:
          - ‘kit vippvp %name%’
        Name: '&e&lSpider Spawner'
        Item Data: 0
        Amount: 1
        Enchantments:
        - DURABILITY-1

**Comment by gappleburst** [comment]
I'll make a new post nvm
