### ISSUE TITLE
Various Issues (Including an Issue with /crates debug!)

### ISSUE THREAD

**Issue by AnthonyGriffith** [ConnorLinfoot/CratesPlus#291]
**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

From version 4.2 there is a new '/crates debug' command. Running this will give you a single link with all the data I need to help you.

### Link/paste of stack trace/error (if any)

    You can also simply just use code formatting in markdown!
___We need all of the stack trace! Do not cut off parts of it.___

### Debug Link
http://pastebin.com/YKdPtQdx

### Actions to reproduce (if known):
On my server, this happens when a user uses a crate (in which they won't get their items) and when using /crates debug

**Comment by ConnorLinfoot** [comment]
Should be fixed now, broke the DNS xD
