### ISSUE TITLE
Chests not opening and throwing an exception

### ISSUE THREAD

**Issue by Ryguyl21** [ConnorLinfoot/CratesPlus#292]
Hey, I'm currently using Cauldron 1.7.10 and the plugins working perfectly fine, until I go to open up a crate and it just leaves an empty chest. I have the configuration and items set up, and it says that the rewards are there but when I try to open a crate with a key it does nothing but open the chest.

Config: http://hastebin.com/bonilivunu.coffee

Errors: http://hastebin.com/zetewizitu.avrasm

I've made everything nice and neat and easy for you to debug. Hope you can figure it out/Help!

**Comment by ConnorLinfoot** [comment]
Are you using the latest holographic displays? That may fix the startup error. I'll look at the other errors when I can, they just seem like issues with it being 1.7.

**Comment by ConnorLinfoot** [comment]
https://www.dropbox.com/s/eb9bm8kaggze1fd/CratesPlus-4.2.1.jar?dl=0

Does this fix the errors apart from the ones for the holograms?

**Comment by Ryguyl21** [comment]
I'll test it out now. I updated holographic displays. I guess I forgot to do that when I was working on my dev server. The initilization error is now fixed I'll try that jar and see how it works.
 If you need to I recorded a video of what's happening to help you out. 
Date: Wed, 3 Aug 2016 12:07:21 -0700

**Comment by Ryguyl21** [comment]
The errors gone now. Thanks for the help. :)

Date: Wed, 3 Aug 2016 12:07:21 -0700

**Comment by ConnorLinfoot** [comment]
Great! I'll push it out on Spigot also but it'll be the exact same file I just linked you :)
