### ISSUE TITLE
Crate Rename broken (4.2.1) Throwing exceptions and dropping item

### ISSUE THREAD

**Issue by Ryguyl21** [ConnorLinfoot/CratesPlus#293]
When you rename a crate using the ingame gui editor it throws this exception:
http://hastebin.com/citirujumo.avrasm

Looks like it's throwing null and it's not passing inventoryclick

Once the rename item is clicked it's then removed from the gui and can be freely moved

**Comment by ConnorLinfoot** [comment]
Yeah it's another issue with 1.7, will either fix it or disable it on 1.7.

**Comment by Ryguyl21** [comment]
Ok. Should I just not use the GUI and stick to config?


Sent via the Samsung Galaxy Alpha™, an AT&T 4G LTE smartphone

-------- Original message --------

**Comment by ConnorLinfoot** [comment]
Probably best as I know it's had issues with 1.7 in the past also.
