### ISSUE TITLE
Cant add more than 5 command items in each crate

### ISSUE THREAD

**Issue by PixelPlayzzz** [ConnorLinfoot/CratesPlus#294]
I cant add more than 5 command items in each crate.
Here is my config:
http://pastebin.com/GjXkBjme

**Comment by ConnorLinfoot** [comment]
https://github.com/ConnorLinfoot/CratesPlus/wiki/Debugging-Issues

**Comment by PixelPlayzzz** [comment]
I still cant seem to solve the issue.
i still cant add more than 5 items in the crate.

**Comment by DumplingsWithToads** [comment]
Make sure all your percentages add up to 100%.
See #288 for more information.

**Comment by PixelPlayzzz** [comment]
Oh now i get it, thanks
