### ISSUE TITLE
3 Issues with this plugin

### ISSUE THREAD

**Issue by mehboss** [ConnorLinfoot/CratesPlus#299]
**EXPLANATION:**
1st: There doesn't seem to be support for silkspawners, I have spawners as a crate winnings and when players win it and they place down the spawner it just turns to a pig so I have to give them one manually. 

2nd: I also have creeper eggs as a winning and after a restart they change to an all white egg that is name "Spawn Egg" and they become not placeable.

3rdly: I have enchantment books as a winning and when I restart they turn into an empty enchantment book with no lore and not anvilable,

### Link/paste of stack trace/error (if any)
N/A

### Debug Link
https://mcdebug.xyz/cratesplus/149

### Actions to reproduce (if known):
N/A

**Comment by ConnorLinfoot** [comment]
1) You should use commands for rewards like this.

2) Remove the "Entity Type" option for the winning, seems like this causes issues with 1.8.

3) Similar to 1, you should use commands to give enchantment books as the plugin currently doesn't support additional data.
