### ISSUE TITLE
Redo to my last problem

### ISSUE THREAD

**Issue by marioandluigi878** [ConnorLinfoot/CratesPlus#30]
I guess the owner didnt read the other comment but ill say it again Whenever pepole that are on that are opped so if I came on my server as an opped other people cant use the crates if there is no answer then ill just have to try to figure this out myself

**Comment by SharkDice** [comment]
I don't understand the issue. I could try and help, however.

**Comment by ConnorLinfoot** [comment]
The issue you reported really doesn't seem like it's something caused by the plugin (at least the plugin alone)

I've not had this issue and neither has anyone else reported it. I would advise removing your plugins and adding them back 1 by 1 until the issue occurs again.

**Comment by marioandluigi878** [comment]
ok thanks for making it more clearler
