### ISSUE TITLE
Items not stackable with rewards from crates [HELP]

### ISSUE THREAD

**Issue by MandiKro** [ConnorLinfoot/CratesPlus#302]
**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

From version 4.2 there is a new '/crates debug' command. Running this will give you a single link with all the data I need to help you.

### Link/paste of stack trace/error (if any)

    You can also simply just use code formatting in markdown!
___We need all of the stack trace! Do not cut off parts of it.___

### Debug Link
https://mcdebug.xyz/cratesplus/255

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

**Hey, I hope I have filled out the format correctly, I have included debug link, not sure what stack trace is? Sorry.

Issue: Hey, I am planning on givign you 5*, however only one thing holding me back. Say, for example, one of my players open the vote crate to obtain 8 diamonds, these diamonds are not stackable with normal diamonds mined. This is the same for iron and gold. Can you please help me?**

**Comment by ConnorLinfoot** [comment]
The issue will likely be the "Name", items stack by name and not always type.

If you set name to NONE it should make them stack.
