### ISSUE TITLE
Issue with empty crate rewards

### ISSUE THREAD

**Issue by Mineleague** [ConnorLinfoot/CratesPlus#303]
I am having the issue that I make command rewards for hub gadgets plugin, and I preview the crate and there are no rewards. I used the key but it just unlocks the crate and lets me place and remove items from it. I would be very glad if you gave me a quick response. Thank you for reading!

I have a valid yaml (I think)

https://mcdebug.xyz/cratesplus/271

No actions except use my config for example crate.

Config link here: http://pastebin.com/HfvmhtBc

**Comment by ConnorLinfoot** [comment]
You're not using valid item types. https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
