### ISSUE TITLE
Crate error, can't do more than what seems like 3 crates. No errors either

### ISSUE THREAD

**Issue by UnrealisticBeing** [ConnorLinfoot/CratesPlus#306]
From version 4.2 there is a new '/crates debug' command. Running this will give you a single link with all the data I need to help you.

config: http://pastebin.com/pytH8E5w
### Link/paste of stack trace/error (if any)

```
You can also simply just use code formatting in markdown!
```

**_We need all of the stack trace! Do not cut off parts of it.**_
### Debug Link

https://mcdebug.xyz/cratesplus/314
### Actions to reproduce (if known):

Not sure what's causing this.

what's happening is it seems like I can't do more than 3 rewards. I have all of the percentages 

I'd prefer you contacted me via spigot, at UnrealisticBeing, as I get emails from that and im not active on here.

**Comment by ConnorLinfoot** [comment]
Are you able to run the debug command again? The info on the current link is expired. Just reopen this once you submit it.
