### ISSUE TITLE
PaperSpigot Support?

### ISSUE THREAD

**Issue by mehboss** [ConnorLinfoot/CratesPlus#308]
Why doesn't this work on paper spigot 1.8.8?

MAYBE BELOW BUT WHEN I DO /PL THE PLUGIN IS RED
http://pastebin.com/WBtT3cLF
### Debug Link

**_Enter your debug link from /crates debug**_
Sorry forgot to, this is kind of a question though.
### Actions to reproduce (if known):

N/A

**Comment by AlwaysCandr** [comment]
Still happens even with 4.4.1 :(
