### ISSUE TITLE
Player Head Support

### ISSUE THREAD

**Issue by a662** [ConnorLinfoot/CratesPlus#309]
If this is already possible I haven't been able to find anything on it. I would like to see support for Player heads, so that if I were to add a notch head to a crate it will remains as Notch and not the default Head item.

**Comment by Greenfoot5** [comment]
You should be able to do it via command. I think it goes something like /give %player skull _3_ {player=Notch}. Try that but look it up on the Internet for how to get player heads.
If you have essentials you could just do /skull Notch I think.

**Comment by a662** [comment]
I'll try it. Thanks.

**Comment by Greenfoot5** [comment]
No problem

**Comment by a662** [comment]
Tried both of them, /give only handles direct usernames and not %name% or %player. and /skull can only be run from in-game.

**Comment by Kulenful** [comment]
You can give heads with %name% i think, It should work with cratesplus, i made it work ._. I can find it in my config and send it to you
