### ISSUE TITLE
Can you prevent from duping?

### ISSUE THREAD

**Issue by Alexei17** [ConnorLinfoot/CratesPlus#310]
Hi! Is it possible to prevent from duping keys? They could be duped with the command  /more or in creative by middle mouse clicking

**Comment by Greenfoot5** [comment]
Don't give them the permission? Or don't put them in creative? Or if you are doing a plots server you could use multiverse to add another world, put the crates in that and set the world game mode to not creative

**Comment by Alexei17** [comment]
Multiverse is actually a good idea, but no, I am running a dupe server where everybody has access to /more , is there any other way? Because I already built the "case room" in my main world

**Comment by Greenfoot5** [comment]
You could use world edit to move it into another world and get a per world permissions maybe?

**Comment by Alexei17** [comment]
Okay, one more problem. I have the Daily Bonus plugin and sometimes it gives crate keys, which could be duped in the main world. Any solutions to that? Forcing players to collect their rewards in another worlds seems kind of odd, and removing them... No :/

**Comment by Greenfoot5** [comment]
I don't think it's possible.
