### ISSUE TITLE
Problem with Commands (Not working even with example)

### ISSUE THREAD

**Issue by gappleburst** [ConnorLinfoot/CratesPlus#312]
Hey um. Idk if anyone is still having trouble with this but I REALLY am. I've tried so many things and even with the example and typing it exactly as put, the command just won't work for me in game. This is my exact config file. I tried to copy it exactly as said in the example and NOTHING is working D; Please help me someone!

Winnings:
'1':
Type: ITEM
Item Type: IRON_SWORD
Percentage: 25
Item Data: 0
Name: NONE
Amount: 1
Enchantments: []
Lore: []
'2':
Type: COMMAND
Item Type: MOB_SPAWNER
Percentage: 50
Commands:
- ‘kit vippvp %name%’
  Name: '&e&lSpider Spawner'
  Item Data: 0
  Amount: 1
  Enchantments:
- DURABILITY-1

**Comment by gappleburst** [comment]
Oops. Posting this glitched up a little bit. Here's my exact file.. 
https://gyazo.com/e9f78f9e3fb59a62e839a5f7a40c6aa7

**Comment by Greenfoot5** [comment]
What does the console say when you try the command?

**Comment by gappleburst** [comment]
The console doesn't say anything. Just when I give myself a crate key to test it. The item shows in the GUI with percentage and everything except it's like it doesn't even exist. I've tried it multiple times and all I get are non-command crate items.

**Comment by ConnorLinfoot** [comment]
Are you using any sort of weird quotes? They look slightly angled which could mean they're a different format thus causing issues with the YAML file. Have a look at https://github.com/ConnorLinfoot/CratesPlus/wiki/Debugging-Issues

**Comment by gappleburst** [comment]
No I don't think i'm using any sort of weird quotes. It's just that i'm on
a Mac computer and it looks a little weird. Quotes have never been a
problem for me and I've used quotes for many other configuration files for
other plugins.

**Comment by Greenfoot5** [comment]
Only two of your quotes are slanted:
Slanted - [‘kit vippvp %name%’]
Not slanted - [Name: '&e&lSpider Spawner']
I have a mac and it's fine. I believe the slanted quotes are backticks.

**Comment by gappleburst** [comment]
Ah. So the Slanted quotes are wrong/bad? When I try to configure this
plugin next time, I'll take this in to mind. Until then, thank you all very
much for your help.
