### ISSUE TITLE
Player can't claim their key in Claim GUI, can't move their key if it's in their inventory.

### ISSUE THREAD

**Issue by awsqed** [ConnorLinfoot/CratesPlus#313]
Player can't drag out key from their inventory to their hotbar when I give them using "/crate key <player> <type> 1". However, they can move the key anywhere if it's in their hotbar. They also can't claim the key using "/crate claim".
### Link/paste of stack trace/error (if any)

http://pastebin.com/wvA3YNAU
### Debug Link

https://mcdebug.xyz/cratesplus/1126
### Actions to reproduce (if known):

None

**Comment by ConnorLinfoot** [comment]
Are you able to run the debug link again? Seems like hastebin has cleared the data stored.

**Comment by awsqed** [comment]
The second problem was solved (wrong configuration), but I have no idea with the first one. I will send you the debug link soon.

**Comment by ConnorLinfoot** [comment]
Are you still having issues with this?
