### ISSUE TITLE
1.6.4 Support?

### ISSUE THREAD

**Issue by Zilacon** [ConnorLinfoot/CratesPlus#314]
Is there a version that would work for MC 1.6.4? I have 9 1.6.4 servers and want to use this on my entire network (1.6.4/1.7.10/1.10.2) i know GUI is not compatible on 1.6.4 but is there any way to simply disable GUI for 1.6.4 and still run it through the chatbox or maybe within the gui of a chest itself?

Thanks for your time.

**Comment by ConnorLinfoot** [comment]
Have you tried it on 1.6.4? It should work with 1.7, I'm not really willing to test or make it work with 1.6 just because of the age. Sorry.
