### ISSUE TITLE
Winning Calculation

### ISSUE THREAD

**Issue by acidbyt3** [ConnorLinfoot/CratesPlus#315]
It appears that each reward with a percentage is calculated individually one at a time as opposed to a single roll. Is this true? If so, this becomes problematic when there is certain number of items in a crate, or a considerable difference in the percentage ranges.

After extensive testing, this was our conclusion: the first reward is calculated before moving on to the next one.
This would mean that it isn't a single dice throw with the reward being calculated based on a single result - it rolls the dice for the first reward; if that fails THEN it rolls the dice for the third reward, and so on.

If this is how the rewards are processed, then the system is somewhat ineffective and will render the user-provided percentages extremely inaccurate after a few dice rolls, and this becomes very noticeable especially at higher percentage values/lower amounts of items in the crates

Exemplifying is easier to understand than explaining this type of thing through text, so I made a spreadsheet to show what I mean:
https://docs.google.com/spreadsheets/d/1n2_rqRVVPONjPC98ZMkQMHa4rfIDCJ4Ub7ItkZ93i7U/edit#gid=9805799
There is a second page on the sheet with a different scenario (only two items on the crate, both 50% chance) to exemplify what I mean, and how this would mean subsequent rewards have a much lower chance that will not correspond to the value provided on the config.yml.
Hopefully I didn't overcomplicate it.

We concluded that this is how the rewards are being processed because the values we input don't seem to represent the real values being awarded (we've used hundreds of keys, dare I say probably over a thousand across whoever helped us test it)

Even if this is not how the rewards are processed, they still don't seem to be put into a single poll and the dice rolled just once. Either way, the winnings for crates with lower amounts of items definitely seems off. The rewarded items do not remotely correspond to the percentages provided in the file.

I don't know for sure if this is even how the plugin is coded to calculate the rewards since we're dealing with statistics. There's always the chance that this is all just a matter of statistical improbability, I understand that.
However if this is the case, or if there's any way the reward calculation code could possibly be improved, perhaps to rolling a single number and calculating the reward based on the number that came up (if it's not like that already).

Thank you for reading this and, if our research is incorrect (the rewards not calculated individually), then I apologise in advance for this lengthy message.

**Comment by PixelLeader** [comment]
If this is happening to you, please make sure your total amount of rewards and their win chances in total are not more than 100%

So if I have 5 items which would be 100 : 5 = 20 so if I'd make the win chances of all 5 items 25% the winrate will start to bug out, you can go below the 100% but do NOT in any possible way go over that 100%
