### ISSUE TITLE
/rename Bug - ConradHD

### ISSUE THREAD

**Issue by ConradHD** [ConnorLinfoot/CratesPlus#316]
Debug link - https://mcdebug.xyz/cratesplus/1405

Hello there i'm a follow server owner of a mid size server. I've tried to find my bugs before i release it to the public. One problem i found is that i have a /rename plugin that allows players to rename the item. So the problem is when they rename a item to exactly what a crate key looks like it'll work (This only works if the crate is the same color as well), One way i thought would solve this problem is adding its own special Custom ID so no matter what the name or lore is it won't work.

Kind regards

ConradHD

**Comment by Greenfoot5** [comment]
Will this still work if they are enchanted?

**Comment by ConradHD** [comment]
Yes the enchanted item doesn't fix it, could be a apple if you wanted it to. Lets say the crate key is a golden apple. all you would have to do it color rename any items other title of the crate and it would work

**Comment by ConnorLinfoot** [comment]
I think this is something that's going to need a bit of thought. I'm not that active on developing CratesPlus at the minute because of other things but I would like to get a solution to this at some point. Custom ID's can work but can be problematic from past experiences. I'd probably have to look into NBT or some way to store data along with the item.

I'll keep this updated when there is a solution out for it.

**Comment by nitewing76** [comment]
Consider coding the plugin to  check and verify the lore of the key (ofc server owners would have to disallow players access to changing the lore of an item).

In the mean time, I'm using a Nether Star as the crate key...along with disabling spawning of the Whither in WorldGuard, beacons are un-craftable (using the plugin: UnCrafter), and I just sell beacons at /shop (which I probably would have done anyway).

**Comment by ConnorLinfoot** [comment]
I've decided to do this using the above method of checking the lore, this will of course mean you can't allow players to set the lore on items but renaming the item will be fine.

This will be included in the next update, 4.2.5.
