### ISSUE TITLE
Invalid Enchantments

### ISSUE THREAD

**Issue by RcExtract** [ConnorLinfoot/CratesPlus#320]
_This issue is not about bugs. Instead I am wondering what I should type in the enchantment properties._

I attempt to add enchantments to a winning item, but i have problem on typing the correct enchantment name, because i cannot type SHARPNESS. Instead, i need to type DAMAGE_ALL. That means i cannot follow the official minecraft wiki enchantment names. And I am wondering what to type into the config.yml to represent enchantments excluded from the config sample.

SHARPNESS = DAMAGE_ALL
UNBREAKING = DURABILITY
FIRE_ASPECT = FIRE_ASPECT
SMITE = ?
BANE OF ARTHROPODS = ?
...

**Comment by Greenfoot5** [comment]
It'S using the essentials names. Or the bukkit names.

**Comment by ConnorLinfoot** [comment]
You can see a list of enchantments here - https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html
