### ISSUE TITLE
Player not found issue with galistener and cratesplus

### ISSUE THREAD

**Issue by allinyo** [ConnorLinfoot/CratesPlus#321]
I am trying to enter the command' /crate key playeruseridkhere? Crate 1' in my ga listener for votifier and have tried <player> (username) [player] player %player% all with no success and I'm about to give up does anyone know the command that would give the specific key to the player voting and how to put it in the listener I'm not sure what I'm doing incorrectly

**Comment by ConnorLinfoot** [comment]
Did you ever solve this? If you still need a hand feel free to re-open the issue. Just closing it because it's quite an old one.
