### ISSUE TITLE
Crate Broadcast?

### ISSUE THREAD

**Issue by ctechh** [ConnorLinfoot/CratesPlus#322]
### Debug Link
https://mcdebug.xyz/cratesplus/2735

### Actions to reproduce (if known):
-

I need to know how to broadcast what somebody has just got from the crate.  Say someone got a diamond then I would want the chat to say "[Servername] {PLAYERNAME} has just got a diamond from {Crate}

How would I do this

**Comment by ConnorLinfoot** [comment]
There is an option and messages for broadcasting wins. If you need more customisation I'd recommend looking at a announcer plugin.
