### ISSUE TITLE
Only displaying 2 items in Crate

### ISSUE THREAD

**Issue by Brushes** [ConnorLinfoot/CratesPlus#324]
### Debug Link
https://mcdebug.xyz/cratesplus/2921

Hiya,

I have a Vote Crate (as shown in Config) and when I go to left click on the crate to show its contents it only shows the first 2 items that are listed in the config.

Please help,
Thanks.

**Comment by ConnorLinfoot** [comment]
You're using invalid item type - EXPERIENCE_BOTTLE See https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html#EXP_BOTTLE

Also your percentages must not add up to more than 100% https://github.com/ConnorLinfoot/CratesPlus/wiki/Debugging-Issues#itemswinnings-arent-showing-in-my-crate
