### ISSUE TITLE
I cant use NBT tags in crates

### ISSUE THREAD

**Issue by Rodrigo178** [ConnorLinfoot/CratesPlus#327]
When I try to put a chest with NBT, a potion with more than 2 effects, a item with a command or an enchanted book when I use my crate it doesnt work.

**Comment by ConnorLinfoot** [comment]
The plugin doesn't support NBT data at this moment in time.

**Comment by Rodrigo178** [comment]
When does the plugin will allow NBT?

**Comment by Eufranio** [comment]
You could write the NBT to base64 and store it in somewhere, then load in the crates.
