### ISSUE TITLE
Crates are not displaying all items.

### ISSUE THREAD

**Issue by svmstyle** [ConnorLinfoot/CratesPlus#328]
Crates only display 4 items out of the many in the config.

### Debug Link
https://mcdebug.xyz/cratesplus/3317

### Config Link
http://pastebin.com/ZJb8k4fy

###Pictures
http://prntscr.com/dlz520
http://prntscr.com/dlz567
http://prntscr.com/dlz58r

**Comment by ConnorLinfoot** [comment]
Your percentages add up to more than 100%, please read the wiki.
