### ISSUE TITLE
I don't know how to add the keys to make a essentials Kit

### ISSUE THREAD

**Issue by triggmysta** [ConnorLinfoot/CratesPlus#331]
Basically the title saids it. I need help to know how to add the keys into a essentials kit so the lay out basically i would need.

Please help me ASAP 

Kind regards Triggmysta

**Comment by goldfish2000** [comment]
Hey there,
I recommend using a plugin called "kit adder" to create kits from just the items in your inventory. So after you have installed the plugin you want to just put the key(s) you want in your inventory then create the kit using the command /createkit (name).(i believe that is the command if not look on spigot page for the plugin) hope this helps if you have any trouble(for some reason, its very straight forward) just reply to me ill get back asap
