### ISSUE TITLE
Item missing Bug

### ISSUE THREAD

**Issue by jakovkacan** [ConnorLinfoot/CratesPlus#332]
### Link/paste of stack trace/error (if any) 
No

### Debug Link
https://mcdebug.xyz/cratesplus/3503

### Actions to reproduce (if known):
No.

There is an problem when I try to add Percentage to Item. On some items works and on some plugin just doesn't show them.

**Comment by ConnorLinfoot** [comment]
Please post a link to your config as the debug command seems to be having issues.

**Comment by jakovkacan** [comment]
`# [][][][][][][][][][][][][][][][][][][][][]
#  CratesPlus V4.2.4 Config
# [][][][][][][][][][][][][][][][][][][][][]
# ------------------------------------------
# There are many placeholders that can now be used withing the config and messages file, placeholders are as followed:
# - %name% - Replaces with the players name, Example: "Notch".
# - %displayname% - Replaces with the players display name, Example: "[Owner] Notch".
# - %uuid% - Replaces with the players UUID.
# - %crate% - The crate types name.
# - %prize% - The name of the winning.
# - %percentage% - Percentage of the winning, useful for "Chance Message".
# ------------------------------------------
# Don't change the config version!

Config Version: 6
Update Checks: true
Update Branch: spigot
Metrics: true
Default Opener: BasicGUI
Default Cooldown: 5
Crate Protection: false
Disable Key Swapping: false
Default Hologram Text:
- '%crate%'
- Desni-Klik kako bi otvorio!
- Lijevi-Klik da bi pregledao nagrade!
Crates:
  Voting:
    Key:
      Item: TRIPWIRE_HOOK
      Name: '%type% Crate Key'
      Enchanted: true
    Knockback: 0.0
    Broadcast: false
    Firework: false
    Preview: true
    Block: CHEST
    Color: RED
    Winnings:
      '1':
        Type: ITEM
        Item Type: DIAMOND
        Item Data: 0
        Percentage: 2
        Name: NONE
        Amount: 1
        Enchantments: []
        Lore: []
      '2':
        Type: ITEM
        Item Type: OBSIDIAN
        Item Data: 0
        Percentage: 15
        Name: NONE
        Amount: 10
        Enchantments: []
        Lore: []
      '3':
        Type: COMMAND
        Item Type: NAME_TAG
        Percentage: 0.1
        Commands:
        - pex user %name% group set Warrior
        Name: '&c&lWarrior Rank'
        Item Data: 0
        Amount: 1
        Enchantments: []
      '4':
        Type: ITEM
        Item Type: EMPTY_MAP
        Item Data: 0
        Percentage: 20
        Name: NONE
        Amount: 1
        Enchantments: []
        Lore: []
      '5':
        Type: ITEM
        Item Type: EXP_BOTTLE
        Item Data: 0
        Percentage: 30
        Name: NONE
        Amount: 6
        Enchantments: []
        Lore: []
      '6':
        Type: ITEM
        Item Type: DIAMOND_SWORD
        Item Data: 0
        Percentage: 2
        Name: The King's Sword
        Amount: 1
        Enchantments:
        - DAMAGE_ALL-2
        - ARROW_KNOCKBACK-2
        - DURABILITY-1
        - LOOT_BONUS_MOBS-2
        Lore: []
      '7':
        Type: ITEM
        Item Type: COOKED_BEEF
        Item Data: 0
        Percentage: 50
        Name: NONE
        Amount: 10
        Enchantments: []
        Lore: []
      '8':
        Type: ITEM
        Item Type: IRON_INGOT
        Item Data: 0
        Percentage: 50
        Name: NONE
        Amount: 5
        Enchantments: []
        Lore: []
      '9':
        Type: COMMAND
        Item Type: TRIPWIRE_HOOK
        Commands:
        - crate key %player% Common 3
        Name: '&a&lCommon Keys'
        Item Data: 0
        Amount: 3
        Enchantments: []
  Common:
    Key:
      Item: TRIPWIRE_HOOK
      Name: '%type% Crate Key'
      Enchanted: true
    Knockback: 0.0
    Broadcast: false
    Firework: false
    Preview: true
    Block: CHEST
    Color: GREEN
    Winnings:
      '1':
        Type: ITEM
        Item Type: DIAMOND
        Item Data: 0
        Name: NONE
        Amount: 2
        Enchantments: []
        Lore: []
      '2':
        Type: ITEM
        Item Type: IRON_PICKAXE
        Item Data: 0
        Name: NONE
        Amount: 1
        Enchantments: []
        Lore: []
      '3':
        Type: ITEM
        Item Type: SHIELD
        Item Data: 0
        Name: NONE
        Amount: 1
        Enchantments: []
        Lore: []
      '4':
        Type: ITEM
        Item Type: IRON_LEGGINGS
        Item Data: 0
        Name: NONE
        Amount: 1
        Enchantments: []
        Lore: []
      '5':
        Type: ITEM
        Item Type: IRON_CHESTPLATE
        Item Data: 0
        Name: NONE
        Amount: 1
        Enchantments: []
        Lore: []
      '6':
        Type: ITEM
        Item Type: IRON_HELMET
        Item Data: 0
        Name: NONE
        Amount: 1
        Enchantments: []
        Lore: []
      '7':
        Type: ITEM
        Item Type: IRON_SWORD
        Item Data: 0
        Name: NONE
        Amount: 1
        Enchantments: []
        Lore: []
      '8':
        Type: ITEM
        Item Type: IRON_BOOTS
        Item Data: 0
        Name: NONE
        Amount: 1
        Enchantments: []
        Lore: []
  Diamond:
    Winnings:
      '1':
        Type: ITEM
        Item Type: IRON_SWORD
        Item Data: 0
        Percentage: 0
        Name: '&6&lExample Sword'
        Amount: 1
    Key:
      Item: TRIPWIRE_HOOK
      Name: '%type% Crate Key'
      Enchanted: true
    Knockback: 0.0
    Broadcast: false
    Firework: false
    Preview: true
    Block: CHEST
    Color: WHITE
  Epic:
    Key:
      Item: TRIPWIRE_HOOK
      Name: '%type% Crate Key'
      Enchanted: true
    Knockback: 0.0
    Broadcast: false
    Firework: false
    Preview: true
    Block: CHEST
    Color: DARK_PURPLE
    Winnings:
      '1':
        Type: ITEM
        Item Type: DIAMOND_BLOCK
        Item Data: 0
        Percentage: 10
        Name: NONE
        Amount: 16
        Enchantments: []
        Lore: []
      '2':
        Type: COMMAND
        Item Type: NAME_TAG
        Percentage: 0.1
        Commands:
        - pex user %name% group set Ninja
        Name: '&f&lNinja Rank'
        Item Data: 0
        Amount: 1
        Enchantments: []
      '3':
        Type: ITEM
        Item Type: DIAMOND_CHESTPLATE
        Item Data: 0
        Percentage: 20
        Name: NONE
        Amount: 1
        Enchantments:
        - PROTECTION_ENVIRONMENTAL-7
        - PROTECTION_FIRE-7
        - DURABILITY-7
        - PROTECTION_EXPLOSIONS-7
        - PROTECTION_PROJECTILE-7
        Lore: []
      '4':
        Type: ITEM
        Item Type: DIAMOND_HELMET
        Item Data: 0
        Percentage: 20
        Name: NONE
        Amount: 1
        Enchantments:
        - PROTECTION_ENVIRONMENTAL-7
        - PROTECTION_FIRE-7
        - DURABILITY-7
        - MENDING-7
        - THORNS-7
        Lore: []
      '5':
        Type: ITEM
        Item Type: DIAMOND_LEGGINGS
        Item Data: 0
        Percentage: 20
        Name: NONE
        Amount: 1
        Enchantments:
        - PROTECTION_ENVIRONMENTAL-7
        - PROTECTION_FIRE-7
        - DURABILITY-7
        - PROTECTION_EXPLOSIONS-7
        - PROTECTION_PROJECTILE-7
        Lore: []
      '6':
        Type: ITEM
        Item Type: DIAMOND_BOOTS
        Item Data: 0
        Percentage: 20
        Name: NONE
        Amount: 1
        Enchantments:
        - PROTECTION_ENVIRONMENTAL-7
        - PROTECTION_FIRE-7
        - DURABILITY-7
        - PROTECTION_EXPLOSIONS-7
        - PROTECTION_PROJECTILE-7
        Lore: []
      '7':
        Type: ITEM
        Item Type: OBSIDIAN
        Item Data: 0
        Percentage: 30
        Name: NONE
        Amount: 64
        Enchantments: []
        Lore: []
      '8':
        Type: COMMAND
        Item Type: TRIPWIRE_HOOK
        Percentage: 5
        Commands:
        - crate key %name% Common 20
        Name: '&a&lCommon Crate Keys'
        Item Data: 0
        Amount: 20
        Enchantments: []
      '9':
        Type: COMMAND
        Item Type: TRIPWIRE_HOOK
        Percentage: 0.5
        Commands:
        - crate key %name% Epic 1
        Name: '&5&lEpic Crate Key'
        Item Data: 0
        Amount: 1
        Enchantments: []
  Legendary:
    Key:
      Item: TRIPWIRE_HOOK
      Name: '%type% Crate Key'
      Enchanted: true
    Knockback: 1
    Broadcast: true
    Firework: true
    Preview: true
    Block: CHEST
    Color: GOLD
    Winnings:
      '1':
        Type: ITEM
        Item Type: DIAMOND_SWORD
        Item Data: 0
        Name: '&6&lLegendary Sword'
        Amount: 1
        Enchantments:
        - DAMAGE_ALL-15
        - ARROW_KNOCKBACK-15
        - DURABILITY-15
        - KNOCKBACK-15
        - LOOT_BONUS_MOBS-15
        Lore:
        - §e§lGod Item
      '2':
        Type: ITEM
        Item Type: OBSIDIAN
        Item Data: 0
        Name: NONE
        Amount: 64
        Enchantments: []
        Lore: []
      '3':
        Type: ITEM
        Item Type: DIAMOND_BLOCK
        Item Data: 0
        Name: NONE
        Amount: 32
        Enchantments: []
        Lore: []
      '4':
        Type: ITEM
        Item Type: DIAMOND_PICKAXE
        Item Data: 0
        Name: '&6&lLegendary Pickaxe'
        Amount: 1
        Enchantments:
        - DIG_SPEED-15
        - DURABILITY-15
        - MENDING-15
        Lore:
        - §e§lGod Item
      '5':
        Type: ITEM
        Item Type: DIAMOND_AXE
        Item Data: 0
        Name: '&6&lLegendary Axe'
        Amount: 1
        Enchantments:
        - DIG_SPEED-15
        - DURABILITY-15
        - MENDING-15
        Lore:
        - §e§lGod Item
      '6':
        Type: ITEM
        Item Type: DIAMOND_LEGGINGS
        Item Data: 0
        Name: '&6&lLegendary Leggings'
        Amount: 1
        Enchantments:
        - PROTECTION_ENVIRONMENTAL-15
        - PROTECTION_FIRE-15
        - DURABILITY-15
        - PROTECTION_PROJECTILE-15
        - MENDING-15
        - THORNS-15
        Lore:
        - §e§lGod Item
      '7':
        Type: ITEM
        Item Type: DIAMOND_BOOTS
        Item Data: 0
        Name: '&6&lLegendary Boots'
        Amount: 1
        Enchantments:
        - PROTECTION_ENVIRONMENTAL-15
        - PROTECTION_FIRE-15
        - DURABILITY-15
        - PROTECTION_PROJECTILE-15
        - MENDING-15
        - THORNS-15
        Lore:
        - §e§lGod Item
      '8':
        Type: ITEM
        Item Type: DIAMOND_CHESTPLATE
        Item Data: 0
        Name: '&6&lLegendary Chestplate'
        Amount: 1
        Enchantments:
        - PROTECTION_ENVIRONMENTAL-15
        - PROTECTION_FIRE-15
        - DURABILITY-15
        - PROTECTION_PROJECTILE-15
        - MENDING-15
        - THORNS-15
        Lore:
        - §e§lGod Item
      '9':
        Type: ITEM
        Item Type: DIAMOND_HELMET
        Item Data: 0
        Name: '&6&lLegendary Helmet'
        Amount: 1
        Enchantments:
        - PROTECTION_ENVIRONMENTAL-15
        - PROTECTION_FIRE-15
        - DURABILITY-15
        - PROTECTION_PROJECTILE-15
        - MENDING-15
        - THORNS-15
        Lore:
        - §e§lGod Item
      '10':
        Type: COMMAND
        Item Type: TRIPWIRE_HOOK
        Commands:
        - crate key %name% Common 30
        Name: '&a&lCommon Crate Keys'
        Item Data: 0
        Amount: 30
        Enchantments: []
      '12':
        Type: ITEM
        Item Type: MONSTER_EGG
        Item Data: 0
        Name: NONE
        Amount: 1
        Enchantments: []
        Lore: []
        Entity Type: CREEPER
      '13':
        Type: ITEM
        Item Type: EXPERIENCE_BOTTLE
        Item Data: 0
        Percentage: 30
        Name: NONE
        Amount: 64
        Enchantments: []
        Lore: []
`
This is my config.yml

**Comment by ConnorLinfoot** [comment]
https://github.com/ConnorLinfoot/CratesPlus/wiki/Debugging-Issues
