### ISSUE TITLE
Crates Claim Command Error

### ISSUE THREAD

**Issue by svmstyle** [ConnorLinfoot/CratesPlus#334]
I don't think the config is required for this, but when players do "/crates claim" including op, it doesn't allow them to move the keys from the claim inventory.

### Debug Link
https://mcdebug.xyz/cratesplus/3780

### Actions to reproduce (if known):
none

**Comment by ConnorLinfoot** [comment]
Did you ever manage to fix this? I imagine it's an issue of permissions or another plugin causing the event to be cancelled?
