### ISSUE TITLE
Crates not reflecting what is in config.

### ISSUE THREAD

**Issue by Azuraxe** [ConnorLinfoot/CratesPlus#34]
Hey,
Whenever I restart the server with my config > http://pastebin.com/bXhHQ4pz
 
I only see a few items in each crate even when my config has 15+ items:

Crate 1: http://prntscr.com/8jf7rq
Crate 2: http://prntscr.com/8jf8hf
Crate 3 (hasn't been configured at all): http://prntscr.com/8jf8mi

The last crate is fine as it has not been setup with percentages etc.

Any ideas?

Thanks

**Comment by Alexmoo742** [comment]
Im Having The Same Problem Too :(
Hopefully They Fix It Soon...

**Comment by Azuraxe** [comment]
Yeah hopefully :) @Alexmoo742

**Comment by Alexmoo742** [comment]
Right Now,There's No Ways To Fix Them Whatsoever....
The Percentages For Items And Commands Often Don't Work :(
@Azuraxe

**Comment by Alexmoo742** [comment]
I Think I Found The Problem,It's The Percentages!
The Maximum Percentages Are 100%
Each Crate Has It's Own Percentage...
Like For Example:
Coins Has Commands/Items!
They Must Be All Sum up To 100% not over it!
So To Fix This,Well It's Hard Cause You Need To Re-set all your percentages!
like 5%+75%+20%=100%
if you add more percentages like 25%,the item with the 25%will not appear as it will be over 100% if sum!

So Hopefully,Conor Will Add Over 100% Percentages Not Only Under 100% :(!
@Azuraxe

**Comment by Azuraxe** [comment]
Cheers man! fingers crossed, if not use Archon crates, they can be over 100

**Comment by Alexmoo742** [comment]
Cheers mate glad to fix it but he should give us the option to add percentages over 100% :(
@Azuraxe

**Comment by csorrows** [comment]
Why would it allow over 100% That makes no sense. It should however, throw a command to console.

**Comment by ConnorLinfoot** [comment]
My thoughts was that over 100% wouldn't make any sense as said above. I will try and add a message to warn people of this in a future update.

**Comment by NothingClassy** [comment]
It would be better if you could go over a 100% and then the percentage on each item was based on the chance of getting it over the other items rather than the chance of getting it out of 100%

**Comment by ConnorLinfoot** [comment]
Adding up to 100% makes more sense to the players from my experience. The limit will stay at 100%

**Comment by csorrows** [comment]
Sorry, I grew up with actual math. 100% = the whole thing. As it is makes more sense to me.
