### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by Crumps** [ConnorLinfoot/CratesPlus#341]
Nothing To Big Is Wrong But When I Add percentages into the items in the config, there is no way (I could figure out) to turn the percentages showing up in the chests off. I only want the people who have access to the config being able to see the percentages. Thank You For Your Time

**Comment by goldfish2000** [comment]
If you look hard enough on the cratesplus page there should be some example crate configs where you will eventually find something thats like nopercentage or something around that. Hope this helps

**Comment by ConnorLinfoot** [comment]
You should be able to clear the "Chance Message" in the messages.yml
