### ISSUE TITLE
Have the line Percentage auto added.

### ISSUE THREAD

**Issue by Poinball** [ConnorLinfoot/CratesPlus#345]
Hey, When I add Items in a Crate and I go in the yml file, I dont see the Percentage Line on thier options. I have to add this Line manually to Each of them each Time I change the items in the crate. Can you fixe this please ??

**Comment by ConnorLinfoot** [comment]
This is intentional, not everybody wants percentages. If you're using percentages you're expected to manage crates via the config file and not in-game currently.
