### ISSUE TITLE
Back with the same promblem

### ISSUE THREAD

**Issue by Shootingisgood9** [ConnorLinfoot/CratesPlus#347]
I have looked into the worldguard,FactionsOne,and on worldguard fourms it said they checked your code and it was an issue on your side so I have comeback.If you don't remember me,I had a problem with players not being able to use the crates and now they can only preview them but not use them even with the key in there hand.Please help and if you can't I will have to find a new crates plugin :(

**Comment by ConnorLinfoot** [comment]
https://github.com/ConnorLinfoot/CratesPlus/wiki/Debugging-Issues#players-cant-open-crates

**Comment by Shootingisgood9** [comment]
Sir I have already checked the link and disabled worldguard but it seems not to be opening but they can only preview
