### ISSUE TITLE
How do i give players money in the CratePlus config.yml ?

### ISSUE THREAD

**Issue by KungFuPandu** [ConnorLinfoot/CratesPlus#348]
**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

Please post a link to your config file and any other information on your server such as plugins and server version. Currently the /creates debug link does not work as intended and will not help.

### Link/paste of stack trace/error (if any)

    You can also simply just use code formatting in markdown!
___We need all of the stack trace! Do not cut off parts of it.___

### Config Link and Other Info
___Enter your config link and other info___

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

- I have no idea what this is ^ but all i want to know is how do i give players money in the CratesPlus config? -

**Comment by KungFuPandu** [comment]
Hello? - Could anyone help?

**Comment by Greenfoot5** [comment]
CrateName:
  ...
  Winnings:
    '1':
      Type: ITEM
      Item Type: IRON_SWORD
      Item Data: 0
      Percentage: 25
      Name '&6&lExample Sword'
      Amount: 1
      Enchantments:
       - 'DAMAGE_ALL-3'
      Lore:
       - 'The greatest sword!'
    '2':
      Type: COMMAND
      Item Type: PAPER
      Percentage: 25
      Commands:
      #Money command here (I used essentials)
       - 'eco give %name% [amount]'
      Name: '&6Money!'
      Item Data: 0
      Amount: 1
      Enchantments:
       - 'DURABILITY-1'
