### ISSUE TITLE
Config not registering in-game

### ISSUE THREAD

**Issue by DLiebov** [ConnorLinfoot/CratesPlus#349]
Hello!

 I have been working on this for about 10 minutes... I put it into my server and it doesn't show that this key is a thing...
Here is my config

> http://pastebin.com/tFam40ym

Thanks PLEASE HELP

**Comment by ConnorLinfoot** [comment]
Please use a [YAML Parser](http://yaml-online-parser.appspot.com/), you're also using the winning "2" twice.
