### ISSUE TITLE
Players can shift+rightclick stuff out of crates

### ISSUE THREAD

**Issue by N3cr0Nightmare** [ConnorLinfoot/CratesPlus#350]
Hey,
One of my alpha testers brought to my attention that he and other players can check crate winnings,shift and rightclick winnings out of the chest. 
https://youtu.be/S3o3qRXfCa8

[config.txt](https://github.com/ConnorLinfoot/CratesPlus/files/784810/config.txt)
I hope  helped and this can be resolved soon!

**Comment by ConnorLinfoot** [comment]
I'm unable to replicate this myself, I feel that something else could be intercepting the events and causing the issue.

**Comment by N3cr0Nightmare** [comment]
Nevermind, it turns out when people try to use the stuff, it disappears.
