### ISSUE TITLE
REQUEST: Ability to use colored glass blocks/panes as vote crates.

### ISSUE THREAD

**Issue by unsivilaudio** [ConnorLinfoot/CratesPlus#355]
After posting in the discussion thread on SpigotMC, I realized it was not possible to set a color to a block such as Glass, Pane, Wool, or Clay.  As I've seen it done on other servers, I thought making a request seemed like the next logical step instead of looking for another resource.  Really appreciate the work gone into this plugin and would like to stick with it.

### Config Link and Other Info
`Crates:
  Monthly:
    Winnings:
      '1':
        Type: ITEM
        Item Type: IRON_SWORD
        Item Data: 0
        Percentage: 0
        Name: '&6&lExample Sword'
        Amount: 1
    Key:
      Item: TRIPWIRE_HOOK
      Name: '%type% Crate Key'
      Enchanted: true
    Knockback: 0.0
    Broadcast: true
    Firework: true
    Preview: true
    Block: STAINED_GLASS 
    Color: DARK_PURPLE`

### Actions to reproduce (if known):
N/A

**Comment by TheSenseiNL** [comment]
Please, when you add a feature like this, make a possibility to have 'any' item be a vote chest for anything by defining the item ID in the config.yml


So let say I wanna create a 'Donor crate' PLEASE give me a change to define a crate item for that in the config.yml by defining an item ID for it.

Would so much LOVE that posibility :-)
