### ISSUE TITLE
Cant Use Multiple of Same Crate

### ISSUE THREAD

**Issue by DovahKaal1** [ConnorLinfoot/CratesPlus#356]
**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

Please post a link to your config file and any other information on your server such as plugins and server version. Currently the /creates debug link does not work as intended and will not help.

### Link/paste of stack trace/error (if any)

    You can also simply just use code formatting in markdown!
___We need all of the stack trace! Do not cut off parts of it.___

### Config Link and Other Info
http://pastebin.com/B5M9twUB

### Actions to reproduce (if known):
I am trying to place a second one of my Vote crates in a different world so players are able to use it there as well. The player is only able to preview the contents. The tripwire hook does not work. There is no message given and no knockback. Only OPs are able to use the additional crate.

**Comment by Greenfoot5** [comment]
Is the crate near spawn? Or in a world guard region?

**Comment by DovahKaal1** [comment]
The working crate is in a world guard region. The 2nd crate is also in a
world guard region with the same exact flags. However it's near a
multiverse set spawn. Could that be the problem?

**Comment by Greenfoot5** [comment]
https://github.com/ConnorLinfoot/CratesPlus/wiki/Debugging-Issues

**Comment by ConnorLinfoot** [comment]
Did this issue get resolved?

**Comment by DovahKaal1** [comment]
Yes, it was too close to a spawn protection. Thanks.
