### ISSUE TITLE
My Vote Crate Is Bugged

### ISSUE THREAD

**Issue by Freakingchichickenbones** [ConnorLinfoot/CratesPlus#359]
**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

Please post a link to your config file and any other information on your server such as plugins and server version. Currently the /creates debug link does not work as intended and will not help.

### Link/paste of stack trace/error (if any)
No errors
    You can also simply just use code formatting in markdown!
___We need all of the stack trace! Do not cut off parts of it.___

### Config Link and Other Info
___Enter your config link and other info___
https://paste.ofcode.org/8Re2AMybUYivHPVbYJQw3H

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
https://i.gyazo.com/7a099bd0d06dc7059914842255556493 it will look like this.
Keep deleting and putting the crate back and then it will be bugged.

**Comment by ConnorLinfoot** [comment]
Did you fix this issue? Usually a server restart fixes it.
