### ISSUE TITLE
Crates are not removing.

### ISSUE THREAD

**Issue by SharkDice** [ConnorLinfoot/CratesPlus#36]
Hey, so I ran into a problem where players could take items from my crates (which I fixed personally), but now however crates are not removing themselves or the bar that appears above the crates. There is also an entity or something right under the bar because I can no longer place blocks where my chest used to be. I have tried deleting the crate but nothing will work.

**Comment by ConnorLinfoot** [comment]
Check issue #16

**Comment by RazihelYT** [comment]
@ConnorLinfoot No help at all for 1.9. The commands provided do not work.
