### ISSUE TITLE
World Flag issues

### ISSUE THREAD

**Issue by Solo98** [ConnorLinfoot/CratesPlus#365]
Hey, so I am having trouble allowing players to access the crates I have crated in my spawn, because my crates are in spawn they are obviously protected. I have allowed the chest-access and use flags however players still can't use the crates. Any help with this?

**Comment by Greenfoot5** [comment]
Change spawn protection in server-config. You also might want to check
essentials if you have it just in case but the first should do it.

On 01/04/2017, Solo98 <notifications@github.com> wrote:
> Hey, so I am having trouble allowing players to access the crates I have
> crated in my spawn, because my crates are in spawn they are obviously
> protected. I have allowed the chest-access and use flags however players
> still can't use the crates. Any help with this?
>
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ConnorLinfoot/CratesPlus/issues/365


-- 
hfor
