### ISSUE TITLE
How do I change the Default Opener.

### ISSUE THREAD

**Issue by Solo98** [ConnorLinfoot/CratesPlus#366]
Hey, so I downloaded the CSGO Opener and now in my openers folder I see CSGO.yml however when I change the Default Opener in config to "CSGO" or "NoGui" I crashes the plugin and I receive this error
https://pastebin.com/8pa9yjM5

**Comment by Solo98** [comment]
I also am unsure on how to enable bounce back for players that have no key, I set chest protection to true in the config but they still don't bounce back however they do receive the message "You must be holding a voting key to open this" so I know I'm doing it right xD

**Comment by ConnorLinfoot** [comment]
You're using a plugin manager, this is not supported by Spigot or myself.

As for bounce back that's the knockback option.

**Comment by Solo98** [comment]
So how should I reload the plugin since /crates reload isn't fully supported.

**Comment by Solo98** [comment]
Also why does this not work (https://pastebin.com/22J15KK7) The sword and spawner show but not the money.
