### ISSUE TITLE
Can i change the Description of the Keys?

### ISSUE THREAD

**Issue by KlenerTeufel96** [ConnorLinfoot/CratesPlus#369]
So, I downloaded the Plugin CratePlus, it´s a very nice Plugin! Now my question is:
Can i change the description of the Key? By default, is there this Text: "Right-klick on a "Vote"Chest to win" or something and this is what i will change, is it possible?

**Comment by Greenfoot5** [comment]
You could change the lore of the item and it will still function as a key but I don't think there is a way to change the Loren of the item given to the player.

**Comment by ConnorLinfoot** [comment]
Unfortunately you can not currently change the lore/description of keys. If you do try @Greenfoot5's approach that won't work in version 4.3+ as it now checks the lore before allowing it to be used as a key.

It's something that should be quite simple to implement so I'll take a look at it for the next update.

**Comment by KlenerTeufel96** [comment]
Oh nice, thank you very much :)
