### ISSUE TITLE
Can't use keys that don't have lore

### ISSUE THREAD

**Issue by prizoner15** [ConnorLinfoot/CratesPlus#370]
https://mcdebug.xyz/cratesplus/share/tcJnyX3dRf

All i did was give myself a key (Opped) but half the time the keys don't work that don't spawn with the lore.

**Comment by ConnorLinfoot** [comment]
Key's that don't have lore won't work anymore due to how the plugin checks keys. You need to be using the "/crate key" command which includes the lore.

**Comment by prizoner15** [comment]
Sorry i forgot to clarify i am using the /crate key command but the problem still persists
