### ISSUE TITLE
Same Item for different winnings

### ISSUE THREAD

**Issue by VorstrifeEdits** [ConnorLinfoot/CratesPlus#372]
Using the same item type in different winning on the same crate does not work and will only display one in the possible winnings. Any reason or fixes?

**Comment by ConnorLinfoot** [comment]
There wouldn't be a point, just use percentages.

**Comment by VorstrifeEdits** [comment]
I have set different percentages, all the possible winnings shows is one of the command items that I have set and none of the others that have different percentages
