### ISSUE TITLE
PlayerInteractEvent

### ISSUE THREAD

**Issue by PixelatedHighDef** [ConnorLinfoot/CratesPlus#375]
**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

From version 4.3 there is a new '/crates debug' command. Running this will give you a single link with all the data I need to help you. Please run this and submit the share link with your issue.

### Link/paste of stack trace/error (if any)
`12.04 08:48:41 [Server] ERROR Could not pass event PlayerInteractEvent to CratesPlus v4.3.3
12.04 08:48:41 [Server] INFO org.bukkit.event.EventException
12.04 08:48:41 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot45.jar:git-Spigot-21fe707-e1ebe52]
12.04 08:48:41 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot45.jar:git-Spigot-21fe707-e1ebe52]
12.04 08:48:41 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot45.jar:git-Spigot-21fe707-e1ebe52]
12.04 08:48:41 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot45.jar:git-Spigot-21fe707-e1ebe52]
12.04 08:48:41 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [spigot45.jar:git-Spigot-21fe707-e1ebe52]
12.04 08:48:41 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463) [spigot45.jar:git-Spigot-21fe707-e1ebe52]
12.04 08:48:41 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:759) [spigot45.jar:git-Spigot-21fe707-e1ebe52]
12.04 08:48:41 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [spigot45.jar:git-Spigot-21fe707-e1ebe52]
12.04 08:48:41 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot45.jar:git-Spigot-21fe707-e1ebe52]
12.04 08:48:41 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot45.jar:git-Spigot-21fe707-e1ebe52]
12.04 08:48:41 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
12.04 08:48:41 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
12.04 08:48:41 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot45.jar:git-Spigot-21fe707-e1ebe52]
12.04 08:48:41 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot45.jar:git-Spigot-21fe707-e1ebe52]
12.04 08:48:41 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot45.jar:git-Spigot-21fe707-e1ebe52]
12.04 08:48:41 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot45.jar:git-Spigot-21fe707-e1ebe52]
12.04 08:48:41 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot45.jar:git-Spigot-21fe707-e1ebe52]
12.04 08:48:41 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
12.04 08:48:41 [Server] INFO Caused by: java.lang.NullPointerException
12.04 08:48:41 [Server] INFO at plus.crates.Listeners.PlayerInteract.onPlayerInteract(PlayerInteract.java:77) ~[?:?]
12.04 08:48:41 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
12.04 08:48:41 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
12.04 08:48:41 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
12.04 08:48:41 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
12.04 08:48:41 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot45.jar:git-Spigot-21fe707-e1ebe52]`
    You can also simply just use code formatting in markdown!
___We need all of the stack trace! Do not cut off parts of it.___

### Debug Link
https://mcdebug.xyz/cratesplus/share/MTdhQlUbdu
### Actions to reproduce (if known):
When right clicking with a "key" on a crate, namely chests, it just opens the chest like any other but has the "crate name in the chest", and fires an error in console

**Comment by TheTomTom3901** [comment]
I am having the exact same issue. Any help would be great :D

**Comment by RazerCortex** [comment]
https://mcdebug.xyz/cratesplus/share/HdF7WY9vJ6
