### ISSUE TITLE
Cratesplus Issue (Chests Opening) 

### ISSUE THREAD

**Issue by JTGgamer** [ConnorLinfoot/CratesPlus#378]
**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

From version 4.3 there is a new '/crates debug' command. Running this will give you a single link with all the data I need to help you. Please run this and submit the share link with your issue.

### Link/paste of stack trace/error (if any)
15.04 10:47:51 [Server] INFO Could not pass event PlayerInteractEvent to CratesPlus v4.3.3
15.04 10:47:51 [Server] INFO org.bukkit.event.EventException
15.04 10:47:51 [Server] INFO at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:122) ~[?:?]
15.04 10:47:51 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot46.jar:git-Spigot-21fe707-e1ebe52]
15.04 10:47:51 [Server] INFO at us.Myles.PWP.TransparentListeners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:30) [PerWorldPlugins%20(1).jar:?]
15.04 10:47:51 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
15.04 10:47:51 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
15.04 10:47:51 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
15.04 10:47:51 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
15.04 10:47:51 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:759) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
15.04 10:47:51 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
15.04 10:47:51 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
15.04 10:47:51 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
15.04 10:47:51 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
15.04 10:47:51 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
15.04 10:47:51 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
15.04 10:47:51 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
15.04 10:47:51 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
15.04 10:47:51 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
15.04 10:47:51 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
15.04 10:47:51 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
15.04 10:47:51 [Server] INFO Caused by: java.lang.NullPointerException
15.04 10:47:51 [Server] INFO at plus.crates.Listeners.PlayerInteract.onPlayerInteract(PlayerInteract.java:77) ~[?:?]
15.04 10:47:51 [Server] INFO at sun.reflect.GeneratedMethodAccessor131.invoke(Unknown Source) ~[?:?]
15.04 10:47:51 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
15.04 10:47:51 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
15.04 10:47:51 [Server] INFO at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:120) ~[?:?]
15.04 10:47:51 [Server] INFO ... 18 more
    You can also simply just use code formatting in markdown!
___We need all of the stack trace! Do not cut off parts of it.___

### Debug Link
___Enter your debug link from /crates debug___
Managing data:
https://mcdebug.xyz/cratesplus/admin/FKGFzk2ev8
Share Your Data:
https://mcdebug.xyz/cratesplus/share/M1Rl3UwM4Q
### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
The crates open like regular chests and not crates (left clicking works) and it doesn't take the key or give any items or anything it just opens the chest and you can use it as a chest. all other features seem to be working.

**Comment by ConnorLinfoot** [comment]
Duplicate #375

**Comment by JTGgamer** [comment]
what?

**Comment by JTGgamer** [comment]
how do i fix it?
