### ISSUE TITLE
I dont know how to sell keys.

### ISSUE THREAD

**Issue by nickylmbo** [ConnorLinfoot/CratesPlus#379]
Hi, i just want to sell the keys of crates in someway ,i dont know how i have signshop but if i need another plugin o another way please tell me which, i just want a way to sell keys

**Comment by ConnorLinfoot** [comment]
This is for bugs/suggestions. To give keys you use the commands so you'd use a plugin that can run commands.

**Comment by nickylmbo** [comment]
Can you please give me a suggest plugin?

**Comment by Greenfoot5** [comment]
Use magicsigns it allows you to have a sign with an overlay on top.

**Comment by nickylmbo** [comment]
Thank you so much!!!! Very gently!!!

Il 17 Apr 2017 21:03, "Greenfoot5" <notifications@github.com> ha scritto:

> Use magicsigns it allows you to have a sign with an overlay on top.
>

**Comment by nickylmbo** [comment]
But if i want to permit a specific player run the command, like /crate key
@p commonkey , i cant because the uses its just all or (name of specific
player), how can i do it?

Il 17 Apr 2017 21:03, "Greenfoot5" <notifications@github.com> ha scritto:

> Use magicsigns it allows you to have a sign with an overlay on top.
>

**Comment by Greenfoot5** [comment]
Read the magic signs wiki. I think they use %player% instead of @p

**Comment by nickylmbo** [comment]
Thank you!!!!

Il 17 Apr 2017 10:41 PM, "Greenfoot5" <notifications@github.com> ha scritto:

> Read the magic signs wiki. I think they use %player% instead of @p
>
