### ISSUE TITLE
Config not working?

### ISSUE THREAD

**Issue by skiingrocks111** [ConnorLinfoot/CratesPlus#38]
Hello! I'm not intirley sure why, but my config has no option to set whats in the crates! D: I have version 3.1.2, and here is a screenshot of my config:
https://gyazo.com/69a8e587f2b36b1413e524e633498af7
Thanks for your help!

**Comment by Alexmoo742** [comment]
Hi,You Seemed To Not Had Read The Updates!
Default config no longer contains any crates, see example config on Spigot page!
An example config with notes can be found here: http://pastebin.com/grPRrSXp
You Can Make A Crate By /crate create [name] like /crate create test and boom the crate will appear in the config file!Hope This Helps
@skiingrocks111
