### ISSUE TITLE
Sorry, just the last question.

### ISSUE THREAD

**Issue by nickylmbo** [ConnorLinfoot/CratesPlus#380]
Sorry, if i want to get that the user that push the sign get the key i have to use the command : /crate key @p Commonkey(name created by me) but the command doesnt work because the user @p (that indicate a specific player that do the command) doesnt exist, how i use it ? /crate key all commonkey work, but i cant put an specific username..i have to put generally text like @p or <player>..

**Comment by ConnorLinfoot** [comment]
Again, this is for suggestions/bugs.
