### ISSUE TITLE
I cannot open my crates

### ISSUE THREAD

**Issue by CrackerzMC** [ConnorLinfoot/CratesPlus#382]
**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

From version 4.3 there is a new '/crates debug' command. Running this will give you a single link with all the data I need to help you. Please run this and submit the share link with your issue.

### Link/paste of stack trace/error [https://www.youtube.com/watch?v=m4HUHDwaEl0&feature=youtu.be](url)

    You can also simply just use code formatting in markdown!
___We need all of the stack trace! Do not cut off parts of it.___ [https://www.youtube.com/watch?v=m4HUHDwaEl0&feature=youtu.be](url)

### Debug Link
___Enter your debug link from /crates debug___ [https://www.youtube.com/watch?v=m4HUHDwaEl0&feature=youtu.be](url)

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___  Yes I have a video.
[https://www.youtube.com/watch?v=m4HUHDwaEl0&feature=youtu.be](url)
[https://www.youtube.com/watch?v=m4HUHDwaEl0&feature=youtu.be](url)
[https://www.youtube.com/watch?v=m4HUHDwaEl0&feature=youtu.be](url)
[https://www.youtube.com/watch?v=m4HUHDwaEl0&feature=youtu.be](url)
[https://www.youtube.com/watch?v=m4HUHDwaEl0&feature=youtu.be](url)
[https://www.youtube.com/watch?v=m4HUHDwaEl0&feature=youtu.be](url)
[https://www.youtube.com/watch?v=m4HUHDwaEl0&feature=youtu.be](url)
[https://www.youtube.com/watch?v=m4HUHDwaEl0&feature=youtu.be](url)
[https://www.youtube.com/watch?v=m4HUHDwaEl0&feature=youtu.be](url)

**Comment by CrackerzMC** [comment]
UPDATE! I went somewhere random in wilderness and still same problem, just opens the chest!

**Comment by CrackerzMC** [comment]
??????? @ConnorLinfoot Why did you do that?

**Comment by ConnorLinfoot** [comment]
Actually follow the instructions given.
