### ISSUE TITLE
How to edit the lore of the key or add key to a kit

### ISSUE THREAD

**Issue by porkypine47** [ConnorLinfoot/CratesPlus#384]
I am needing desperate help for my server i'm trying to add the key to a kit but i tried the command in the kit and it did not work and i keep trying different things so i believe changing the lore will fix it so how can i do that please respond asap or tell me how to add the key to a kit because the description in the key when using the command has a space but when in the kit it has no space and does not work

**Comment by Greenfoot5** [comment]
If you are using essentials kits you can use the kit adder plugin add the item in your hand to a kit or create a new kit based on the items in your inventory.

**Comment by porkypine47** [comment]
But That Does not work

**Comment by Greenfoot5** [comment]
If you are using essentials kits use the plugin kit adder. It will add or create kits in your inventory.
