### ISSUE TITLE
Holograms above crates are disappearing randomly

### ISSUE THREAD

**Issue by Pspman345** [ConnorLinfoot/CratesPlus#386]
https://mcdebug.xyz/cratesplus/share/zXE5DDNeLZ

*I am not getting any error messages in console.*

Here are a few screenshots of what I mean:
![image](https://cloud.githubusercontent.com/assets/27712813/25199445/e47aaa34-2518-11e7-86c7-5ce1dad09cf3.png)
Notice how the crate on the right keeps the hologram but the other crates don't.

 As you can see from my mcdebug link, my config.yml is configured to have the holograms appear by default, and while they do, they randomly disappear after the player moves around. From what I've seen it seems to be a client-side issue, as I've discussed with my staff team about this issue, some report that they see holograms for some crates, while others don't.

 Anyways, from a little bit of testing, the holograms for some crates disappear after the player moves away from the crate's location. I don't believe this is from Holographic Displays, because we use the crate holograms and the plugin separately, while HolographicDisplays has never had an issue with this happening.

Here are some more screenshots:
![image](https://cloud.githubusercontent.com/assets/27712813/25199685/9cd29b78-2519-11e7-8eee-eb8d559a880b.png)
![image](https://cloud.githubusercontent.com/assets/27712813/25199691/a09cd8f4-2519-11e7-996d-9f323d6ed7b5.png)
(This crate is being modified by BlockParticles, with a Gem Fountain appearing from it. I have had this hologram issue even before I installed BlockParticles.)

The issue is sometimes fixed by the user relogging.

**Comment by ConnorLinfoot** [comment]
I honestly can't see any reason why this would be a bug with CratesPlus itself, I'll do some checks when I can but all the holograms are handled by other plugins now.

**Comment by Pspman345** [comment]
@ConnorLinfoot 
Here's where it gets interesting however.
In the console whenever I start CratesPlus, it says that it found HD and has hooked into it.
However, when you do /hd reload, you see holograms flicker for a fraction of a second. Whenever I do it, I see holograms created by our staff flicker, however the holograms on top of the chests don't.

**Comment by ConnorLinfoot** [comment]
Can you try the following version of the plugin - https://www.dropbox.com/s/a096ona3falo4xo/CratesPlus-4.4-HOLOGRAM-DEBUG.jar?dl=1

It should broadcast what it's using to actually handle the holograms, just run it once and let me know what it says please :)

**Comment by Pspman345** [comment]
@ConnorLinfoot 
https://mcdebug.xyz/cratesplus/share/YOVMbDT7H0

Upon startup of the plugin:
https://pastebin.com/mJcEun9h

**Comment by Pspman345** [comment]
A response would be great, this issue is urgent for me, thanks.

**Comment by ConnorLinfoot** [comment]
I will update this issue once I get round to looking into it.

**Comment by ConnorLinfoot** [comment]
I did some extensive testing and personally can't replicate any issues. Due to this I can't really do anything further as it's hard to investigate an issue that I can't replicate.
