### ISSUE TITLE
My Keys In Kits Are Not Working Please Fix This Bug

### ISSUE THREAD

**Issue by porkypine47** [ConnorLinfoot/CratesPlus#387]
In The First Photo You See The Keys Lore With A Gap
![error](https://cloud.githubusercontent.com/assets/27755007/25217721/505ea7a0-25eb-11e7-802c-0debeac9038c.PNG)
In The Second Photo I Make The Key Into A Test Kit
![error 2](https://cloud.githubusercontent.com/assets/27755007/25217753/69c67042-25eb-11e7-9b6c-69fd535976a1.PNG)
In The Third Photo You See Me Getting The Kit
![error 3](https://cloud.githubusercontent.com/assets/27755007/25217778/8f23215a-25eb-11e7-81c2-4cb7741f97ea.PNG)
In The Fourth Photo you see the kit keys lore and it shows No Gap in The Lore And It Does Not Stack With The Other Key
![error 4](https://cloud.githubusercontent.com/assets/27755007/25217816/a950732a-25eb-11e7-956c-0a368ec4b4fc.PNG)
And In The Fifth Photo you see the key does not work
![error 5](https://cloud.githubusercontent.com/assets/27755007/25217824/b4290d0c-25eb-11e7-808e-ad623fdf2d2c.PNG)

**Comment by ConnorLinfoot** [comment]
This isn't a bug with CratesPlus, the plugin you're using is removing the additional line.

**Comment by porkypine47** [comment]
Do you have any plugin suggestions?
or can you remove the line

**Comment by ConnorLinfoot** [comment]
Just modify the lore in the config file.

**Comment by porkypine47** [comment]
it does not work i tried

**Comment by porkypine47** [comment]
im just getting a new plugin i will test

**Comment by ConnorLinfoot** [comment]
You tried changing the lore of the key in your CratesPlus config?

**Comment by porkypine47** [comment]
i does not show
anywhere for the keys

**Comment by ConnorLinfoot** [comment]
It does, add lore to the key section. Check the example config.

**Comment by porkypine47** [comment]
![wdawdwa](https://cloud.githubusercontent.com/assets/27755007/25221378/483286de-25f8-11e7-9b06-91ee80053e82.PNG)
Okay can i have a link because i checked that a bit ago and it was outdated

**Comment by porkypine47** [comment]
Don't worry i found it btw fantastic plugin i got the CSGO type opener sorry about this it just didnt show up

**Comment by ConnorLinfoot** [comment]
The one on the Spigot page was updated the other day.

**Comment by porkypine47** [comment]
thanks for the active support

**Comment by porkypine47** [comment]
ughh it still did not work? the lore is not showing up
![awdwadww](https://cloud.githubusercontent.com/assets/27755007/25221879/01e976b8-25fa-11e7-9c9d-6304de848bf3.PNG)
