### ISSUE TITLE
Non Ops cannot open crates!

### ISSUE THREAD

**Issue by aidennish** [ConnorLinfoot/CratesPlus#391]
Hello! I need a permission node to give my players on my server so that they can open their crates. Only players who are op can use the crate keys.

Debug:
https://mcdebug.xyz/cratesplus/share/b9PoBf1Lmz

**Comment by ConnorLinfoot** [comment]
Please read the wiki.

**Comment by renderx** [comment]
Same to me but,the crate from older version players can open
