### ISSUE TITLE
Spawneggs and SplashPotions not working

### ISSUE THREAD

**Issue by TheSilverSpade** [ConnorLinfoot/CratesPlus#394]
Hello Good Sir. Your Plugin is Absolutly Amazing, With a few problems. It's not a error but more like missing features. Spawneggs revert to the original useless egg, Also splashpotions turn into regular potions, Also unopped players can't open crates

**Comment by Greenfoot5** [comment]
First, you need to either use the data tag or use commands to get certain items. Secondly, if your crates are in spawn or in a protected area then unopped player can't open them. To fix the spawn protection you just have to remove it (instructions in the wiki). If you still want the protection but want players to be able to use the crates I would suggest using world guard.

**Comment by TheSilverSpade** [comment]
I use items with datatags. Spawneggs go in with data tags and your plugin takes off the data tags. I use world guard but still unopped players can't open them

**Comment by TheSilverSpade** [comment]
Why did you close it without fixing

**Comment by Greenfoot5** [comment]
Firstly, data tags have been discussed in another issue and crates not opening solutions are in the wiki
