### ISSUE TITLE
Bug caused by 4.4

### ISSUE THREAD

**Issue by Kainzo** [ConnorLinfoot/CratesPlus#398]
Greetings, I was using Version 4.2.4 of your plugin. When I updated to 4.4 my crate keys that I create manually no longer work. 

I want a universal key to work for all crates and I create it through MythicMobs it appears that on this update you now require the item name LORE and enchant to be the same when opening crates.... can you help me out by adding the ability for a SKELETON key OR the toggle to have it ONLY match item-type and name?

**Comment by ConnorLinfoot** [comment]
Just change the lore to match the configuration file.

**Comment by Kainzo** [comment]
I'm a little confused what this actually means.   The below is my current config, it doesnt work with keys.  
`Crates:
  Crate-I:
    Key:
      Item: TRIPWIRE_HOOK
      Name: §6§lGolden Crate Key`
