### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by BytedByte** [ConnorLinfoot/CratesPlus#399]
Tried following format but couldn't seemed like its more for errors. 

My question is: Is there a way to sell the crate keys on a sign? If so, how? 

Trying to use this http://wiki.mc-ess.net/wiki/Sign_Tutorial#Trade_Sign

and trade an item for a crate key but can't figure out how.

Great plugin btw, love it. Thanks :)

**Comment by xGoldi** [comment]
Is there a way to set up a winning of a full item set? and is it possible to set up a winning such as
ITEM - Paper
COmmand - /give @player <#monies>?
hope that makes sense.

**Comment by PixelLeader** [comment]
`      'EnchantedDiamondSet':
        Type: COMMAND
        Item Type: DIAMOND_CHESTPLATE
        Item Data: 0
        Percentage: 10
        Commands:
        - give %name% 310 1 {ench:[{id:0,lvl:2},{id:34,lvl:1}]}
        - give %name% 311 1 {ench:[{id:0,lvl:2},{id:34,lvl:1]}
        - give %name% 312 1 {ench:[{id:0,lvl:2},{id:34,lvl:1}]}
        - give %name% 313 1 {ench:[{id:0,lvl:2},{id:34,lvl:1}]}
        Name: '&b&lDiamond Set!'
        Amount: 1
        Enchantments:
        - DURABILITY-1
        Lore:
        - '&7Full set of diamond armor with:'
        - '&bUnbreaking I'
        - '&bProtection II'`

More information about the /give command with enchantments can be found [here](http://www.minecraftforum.net/forums/minecraft-discussion/redstone-discussion-and/2154825-how-to-give-players-enchanted-items).
More information about enchantments and their id's can be found [here](http://minecraft.gamepedia.com/Enchanting/ID).

No problem
