### ISSUE TITLE
Problem With Colored Chests/ShulkerBoxes

### ISSUE THREAD

**Issue by tomasmessing** [ConnorLinfoot/CratesPlus#400]
### Issue: 
All players (operators too) are unable to interact **with items** in renamed Chests/ShulkerBoxes **with COLORS**. This is problem because lot of plugins are using chest as menu (for example: ArmorStandTools, ShopKeepers, ...).

I discovered that I set _Possible Wins Title: ''_ (without message) in messages.yml. Maybe you have to create another container check.

### A suggested solution:
Check inventory name with _getName()_ and then cancel _playerInteractEvent_ of item from chest.

**Comment by tomasmessing** [comment]
I discovered that I set **_Possible Wins Title: ''_** (without message) in messages.yml. Maybe you have to create another container check.

**Comment by ConnorLinfoot** [comment]
If you edited the string to be empty then that sort of behavior is expected to occur. Just don't use empty strings for inventory titles xD
