### ISSUE TITLE
Bug/Problem

### ISSUE THREAD

**Issue by monste3** [ConnorLinfoot/CratesPlus#401]
Hello! The Bug/Problem is users without OP can open crate 'GoD' but they can't open crate 'Normal' .

**Comment by Greenfoot5** [comment]
Is it within your spawn chunks?

**Comment by monste3** [comment]
yes

**Comment by Greenfoot5** [comment]
Now go and read the wiki.

**Comment by PixelLeader** [comment]
`  Permission: cratesplus.crate.cratename`
