### ISSUE TITLE
New Feature request.

### ISSUE THREAD

**Issue by joshua31177** [ConnorLinfoot/CratesPlus#402]
![2017-05-13_11 40 57](https://cloud.githubusercontent.com/assets/12284394/26027299/3b07b91c-37d1-11e7-8094-0ac9bc253e87.png)
Could it Be possible for multiple pages for crates to be implemented something like picture above so we could add a lot more items to crates.

**Comment by ConnorLinfoot** [comment]
I'll look into this for version 5.
