### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by dentoffe** [ConnorLinfoot/CratesPlus#41]
hi
I really love the plugin 
so can you make it possible to get a key with /kit so donors can get one everyday for example and make it possible to sell it so give it a name when you do /item info
If you do this i will use it for my server and donate :)

**Comment by ConnorLinfoot** [comment]
More information on your plugin would be helpful.

You could clearly just give an item of the same type and name as the Key's and they should work fine I believe.

**Comment by dentoffe** [comment]
how do i do that i use essentials for kit but then people still can't buy and sell it in a chest shop can they?

**Comment by AcesGamingUK** [comment]
i already use this in kits (essentials)
just add this to the kit config
- 131 1 name:&bDonor_Crate_Key lore:&7Right-Click_on_a_"&bDonor&7"_crate|&7to_win_an_item! arrow_damage:1

131 is the item id you chose for the key (131 = tripwire hook)
1 amount of keys
name:[name and color code of the key you want to give]
lore:[is the lore you put on your key]
arrow_damage:1 is the enchantment (if you chose to use that option)
