### ISSUE TITLE
java.lang.NullPointerException Error

### ISSUE THREAD

**Issue by emanh1** [ConnorLinfoot/CratesPlus#410]
I got this error while starting the server

https://pastebin.com/Se4SP2ia

Can you help me fix this please?

**Comment by PixelLeader** [comment]
Get your config through a yml parser for me please, if any errors appear in that yml parser fix them, if that did not help let me know

**Comment by emanh1** [comment]
I've parsed it like 15 times and still no errors show up, help meh plz

**Comment by ConnorLinfoot** [comment]
Try clearing out your data.yml and see if that helps

**Comment by emanh1** [comment]
I did and that error is still there :/

**Comment by UnrealPixel** [comment]
Mind updating the plugin?
