### ISSUE TITLE
Pick rewards without rolling

### ISSUE THREAD

**Issue by Jackieeex143** [ConnorLinfoot/CratesPlus#411]
This is just a feature suggestion. My server uses crates often. Each user gets a key everytime they vote. The biggest complaint has been that the rolling process takes a while, especially when users save up their keys and go to user 30+ of them. Thanks for reading :)

**Comment by PixelLeader** [comment]
Use CrazyCrates

**Comment by PixelLeader** [comment]
Or reduce the roll length, go to openers, open the opener you are using and set the length to a lower amount, length is in seconds

**Comment by ConnorLinfoot** [comment]
You can also change the opener to "NoGUI" to remove the rolling GUI completely.
