### ISSUE TITLE
Plugin fails after restarting server (every time)

### ISSUE THREAD

**Issue by jakichan77** [ConnorLinfoot/CratesPlus#412]
StackTrace: https://pastebin.com/V7CwSwDw

Can't link /Crates Debug since the plugin will not enable

### Actions to reproduce (if known):
I add my crates to the file and restart the server, everything works. Once I place crates and restart the server, the plugin fails to start. I've tried deleting data.yml and the whole folder, neither works (at least not after I put back the crates and restart the server).

Crates config: https://pastebin.com/TVSEgd1X

Please tell me if I can offer any more information, this is all I could really find from the template.

**Comment by ConnorLinfoot** [comment]
It looks like you're using a plugin loader. Unfortunately CratesPlus and Spigot itself does not support this.
