### ISSUE TITLE
Unable to get the crate inventory bigger than 9 slots

### ISSUE THREAD

**Issue by Keo1711** [ConnorLinfoot/CratesPlus#413]
Hello,
I have just installed this plugin and started setting it up, firstly i want to ask, am i able to use item ID's in the config to determine the item in the crate instead of "DIAMOND_SWORD", I didn't seem to be able to get this to work

Secondly, I am unable to get the crate inventory bigger than 9 slots. I have added a '10'th item to the config but the slots stay at 9 and do not increase into another line of inventory.

You can find my Config here: https://git.io/vHM9r

Thanks
Keo1711

**Comment by Keo1711** [comment]
![vote](https://user-images.githubusercontent.com/17345948/26992541-fea8265a-4d56-11e7-87e6-dcc632daa9a5.png)

**Comment by ConnorLinfoot** [comment]
The config file you've linked only has 9 items...

**Comment by Keo1711** [comment]
I got that config using the /crates debug but its actually different to the actual config. The actual config i have is here https://hastebin.com/taqisojoda.php

**Comment by ConnorLinfoot** [comment]
Just tested and works fine for myself with the file linked.

![screenshot_65](https://user-images.githubusercontent.com/540942/26995600-86475758-4d65-11e7-879f-7a12d0f1e0b2.png)
