### ISSUE TITLE
PaperSpigot on CratesPlus 4.4.1

### ISSUE THREAD

**Issue by AlwaysCandr** [ConnorLinfoot/CratesPlus#415]
Hello, I have trouble on PaperSpigot 1.8.8. (It works perfectly on Spigot 1.8.8). Is this a bug?

### Link/paste of stack trace/error (if any)
`15.06 01:30:34 [Server] INFO Enabling CratesPlus v4.4.1
15.06 01:30:34 [Server] ERROR Error occurred while enabling CratesPlus v4.4.1 (Is it up to date?)
15.06 01:30:34 [Server] INFO java.lang.NullPointerException
15.06 01:30:34 [Server] INFO at org.bukkit.Location.getBlock(Location.java:87) ~[paperspigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
15.06 01:30:34 [Server] INFO at plus.crates.CratesPlus.loadMetaData(CratesPlus.java:443) ~[?:?]
15.06 01:30:34 [Server] INFO at plus.crates.CratesPlus.onEnable(CratesPlus.java:212) ~[?:?]
15.06 01:30:34 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[paperspigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
15.06 01:30:34 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [paperspigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
15.06 01:30:34 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [paperspigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
15.06 01:30:34 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [paperspigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
15.06 01:30:34 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [paperspigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
15.06 01:30:34 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [paperspigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
15.06 01:30:34 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [paperspigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
15.06 01:30:34 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [paperspigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
15.06 01:30:34 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [paperspigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
15.06 01:30:34 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [paperspigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
15.06 01:30:34 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
15.06 01:30:34 [Server] INFO Disabling CratesPlus v4.4.1`

### Debug Link
___The Plugin does not even run. Not able to do this part___

**Comment by ConnorLinfoot** [comment]
I'm not testing with PaperSpigot, the plugin is for Bukkit and Spigot.

**Comment by AlwaysCandr** [comment]
I have to decide between functional crates or functional cannons now :( Would be great if you added support for it!
If you need free hosting service for plugin testing, let me know.

**Comment by ConnorLinfoot** [comment]
Just in case, is there a data.yml? If so try deleting it.

**Comment by ConnorLinfoot** [comment]
I just quickly tested PaperSpigot 1.8.8 (Latest build) and it seems fine for myself.

**Comment by AlwaysCandr** [comment]
I deleted it. It seemed to fix the problem. Thank you very much for the tip!

**Comment by ConnorLinfoot** [comment]
Strange, the plugin is supposed to handle broken data in there but it must not work correctly in some versions of PaperSpigot, glad it's sorted! :D
