### ISSUE TITLE
Problem when using more than 1 of the same crate

### ISSUE THREAD

**Issue by Fluxty** [ConnorLinfoot/CratesPlus#417]
In the latest version of CratesPlus, 4.4.1, or rather any version, Using more than 1 of the same crate causes them to bug out.

ex. Say you have a crate named "common", If you have the "common" crate at 3 different locations it will randomly bug out and become a normal chest, which requires a new one to be placed. I do not know how to reproduce the issue, just that it is present on all of our servers across all of our dedicated machines ONLY on crates that have more than 1 location

**Comment by ConnorLinfoot** [comment]
Can you please submit a debug link with this? Wasn't able to replicate myself. Also does this happen on restart or randomly? Any stack traces or similar in the console?
