### ISSUE TITLE
Hidden NBT Data for identify keys

### ISSUE THREAD

**Issue by Leomixer17** [ConnorLinfoot/CratesPlus#419]
Maybe I was not well explained, in this issue https://github.com/ConnorLinfoot/CratesPlus/issues/418
I meant that if the keys were identified by an hidden string in nbt data which does not change (for example an UUID), you could change the lore to your liking without having to think that the old keys would break.

**Comment by ConnorLinfoot** [comment]
I closed the issue as the current way of handling the keys will not be changed.
