### ISSUE TITLE
RewardCodes versus CratesPlus, How to make reward that contain to give specific player ?

### ISSUE THREAD

**Issue by Kuroyabumozu** [ConnorLinfoot/CratesPlus#420]
Reward Codes 1.2.0 Link
https://www.spigotmc.org/resources/reward-codes.23226/

CratesPlus  [1.7 - 1.12] 4.4.1 Link
https://www.spigotmc.org/resources/cratesplus-free-crates-plugin-1-7-1-12.5018/

as title .. How to make reward that contain to give specify player ? 
I've tried these: 
> `/redeem edit 1362482721 addcommand /crate key %name% facebook活動 1`
and
> `/redeem edit 1362482721 addcommand /crate key %player% facebook活動 1`
and
> `/redeem edit 1362482721 addcommand /crate key <player> facebook活動 1`
and
> `/redeem edit 1362482721 addcommand /crate key <name> facebook活動 1`

but still can't give player key when they typed /redeem 1362482721

**Comment by ConnorLinfoot** [comment]
Sorry but I don't support issues occurred with other plugins.
