### ISSUE TITLE
Issue: Crate missing items

### ISSUE THREAD

**Issue by Loonyy** [ConnorLinfoot/CratesPlus#423]
### Link/paste of stack trace/error (if any)
I'm not getting any errors.

### Debug Link
https://mcdebug.xyz/cratesplus/share/uWMhYGUgol

### Actions to reproduce (if known):
I'm trying to set this plugin up;
I'm putting all the items in with /crate settings, then I'm going into the config just to add the percentages. Once I add them and restart the server, only the first three items are shown in the crate, however they're still appearing in the config.

### What I've tried
- Checked with Yamlint, everything is fine.
- Deleting the config, starting again
- Deleting the crate and re-making it

**Comment by ConnorLinfoot** [comment]
Percentages must add up to 100%, once reached other items will be ignored.

**Comment by Loonyy** [comment]
Hm.. Is there anyway to disable it so it doesn't have to add up to 100%?
I saw on another server they had loads of items with like 30% and it didn't add up to 100..
