### ISSUE TITLE
Issue with WorldGuard 6.2.1 & CratesPlus

### ISSUE THREAD

**Issue by Jav0330** [ConnorLinfoot/CratesPlus#425]
Crates Debug Link: https://mcdebug.xyz/cratesplus/share/j4nQcpZ0qp
Manage Data Link: https://mcdebug.xyz/cratesplus/admin/c6HHrHF6b3

Been ripping my hair out for 2 days now.    :/

I have read about problems with essentials build, or not having the "Interact" allow flag set in a WorldGuard Region.

Crates work perfectly if NOT placed in my WorldGuard region defined as the server spawn. I even tested in a players claim made by GriefProtection. Works fine. Placed on unprotected terrain,  crates work like a champ.

The WorldGuard region in question has the "use" & "interact" flags are set to allow. Players can access vanilla chests and enderchests  in the region with no issue. However crates do not seem to be seen as crates. 

For example, no dialog or knockback occurs if a player tries to open or break a crate. (With or without holding a key.)

Hopefully someone knows of a fix or a workaround, I do love the plugin.

Thanks in advance for all your time and attention,

-Jav0330

**Comment by ConnorLinfoot** [comment]
There is a section on the wiki to help with this https://github.com/ConnorLinfoot/CratesPlus/wiki/Debugging-Issues#players-cant-open-crates

If that doesn't help I'm not sure what the issue could be. Personally I don't use WorldGuard so I don't have much experience with this.
