### ISSUE TITLE
Crates not loading when it gets to load a COMMAND item

### ISSUE THREAD

**Issue by Hunterherobrine** [ConnorLinfoot/CratesPlus#426]
**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

From version 4.3 there is a new '/crates debug' command. Running this will give you a single link with all the data I need to help you. Please run this and submit the share link with your issue.

### Link/paste of stack trace/error (if any)

    You can also simply just use code formatting in markdown!
___We need all of the stack trace! Do not cut off parts of it.___

### Debug Link
___Enter your debug link from /crates debug___

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

Hello My config doesnot save whenEver I try to there is no console errors at all as well

the commands parts should be
Commands: 
- 'Command here'
it always becomes :
Commands:
- commands here

if that is not an issue still the COMMAND parts doesnot load the crate just stop loading when it faces those
Paste bin of what it goes into : https://pastebin.com/EqMAv9Ct
What it should be : https://pastebin.com/FdJTuBzZ

All the parts are loading expect the ones with commands sadly
All the YAML parts are correct 

/crates debug : https://mcdebug.xyz/cratesplus/share/PogOcurlrj

**Comment by ConnorLinfoot** [comment]
Not sure what your issue is? They seem to be loading commands correctly for myself. Some items appear not to be showing because the type needs to be all uppercase. Will change something in the next patch to force uppercase.
