### ISSUE TITLE
Need Crate command help

### ISSUE THREAD

**Issue by MicahJinkerson** [ConnorLinfoot/CratesPlus#429]
**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).
Ran that already, no errors.

From version 4.3 there is a new '/crates debug' command. Running this will give you a single link with all the data I need to help you. Please run this and submit the share link with your issue.

### Link/paste of stack trace/error (if any)

    You can also simply just use code formatting in markdown!
___We need all of the stack trace! Do not cut off parts of it.___
What is stack trace? (Skipped)

### Debug Link
https://mcdebug.xyz/cratesplus/share/DkO5Iuwz0J

### Actions to reproduce (if known):
When using a key to right click on the crate, it scams you and does nothing and it takes away your key.
The main problem is the '2' winning. The plugin does not like command types. Sooo. I need help.

**Comment by ConnorLinfoot** [comment]
Will likely need a stack trace for this, a stack trace is an error in the console usually. Try and open the crate and if a bunch of text appears in the console (similar to this https://pastebin.com/NpgcGPM0) post that here.

If you don't get any sort of stack trace it's more likely that the configuration is incorrect.
