### ISSUE TITLE
Holograms Not Disapearing

### ISSUE THREAD

**Issue by Shane1928** [ConnorLinfoot/CratesPlus#43]
Hello, for some reason when I tried destroying a crate the hologram did not disappear a long with it and I would like to know how to fix this issue, thank you.

**Comment by Shane1928** [comment]
I fixed the issue, just type:
/entitydata @e[type=ArmorStand,r3] {Invisible:0}

**Comment by ConnorLinfoot** [comment]
Duplicate of issue #16 (Resolved anyway)
