### ISSUE TITLE
Opening Certain Crates with Permissions (I really need this)

### ISSUE THREAD

**Issue by WitherRanger** [ConnorLinfoot/CratesPlus#431]
I have no idea if this is already a feature and I'm just an idiot, but I really need you to add this. Let me explain.

I am using your plugin in conjunction with buycraft and I want certain ranks to be able to get certain keys, but not others. e.g. VIP rank would be able to get VIP keys, but default rank would not. This is not a feature in buycraft, so if possible, could you add permissions that allow you to open specific chests? something like: cratesplus.open.[cratename], that would make it so that the group with that permission could open that crate. This would help me out so much and I think it would be a great addition to your already-amazing plugin.

*facepalm* I'm an idiot. This was already in the plugin, you just have to set it up in config. Could you put it on the main spigot page though? I'm sure other people will get confused like me. For anybody that was wondering, here's the page showing you how to do it.

https://github.com/ConnorLinfoot/CratesPlus/wiki/Configuration

**Comment by ConnorLinfoot** [comment]
There is a link on the Spigot page to the wiki as it's much easier to maintain the wiki on Github rather than doing it all on a single Spigot resource page.
