### ISSUE TITLE
Rewards Given Time [Request]

### ISSUE THREAD

**Issue by Loonyy** [ConnorLinfoot/CratesPlus#433]
One thing that kinda annoys me is how long you're in the GUI for before it gives you your rewards.  10 seconds is a long time if you have like 30 keys to open.

Can I request that there's an option of how long you're in the GUI for? I'd prefer to shorten it to 3 or 5 seconds. Thanks!

**Comment by ConnorLinfoot** [comment]
There is an option in the opener config.yml file that allows you to change the time.
