### ISSUE TITLE
Default players can't open crates, while OPs can

### ISSUE THREAD

**Issue by zombieknifer223** [ConnorLinfoot/CratesPlus#434]
### Link/paste of stack trace/error (if any)

None

### Debug Link
https://mcdebug.xyz/cratesplus/share/tvQnaWuKlN

### Actions to reproduce (if known):

1. Make a Crate (I did it in a WorldGuard region)
2. Make sure you don't have CratesPlus admin permission or * as a permission or is OP.
3. Try to open the crate with no key.

### Gif Image

![GIF Image](https://user-images.githubusercontent.com/11689362/28199484-f7fa5c18-6833-11e7-9bb7-7261f2fbb451.gif)

**Comment by ConnorLinfoot** [comment]
There is a section on the wiki for this - https://github.com/ConnorLinfoot/CratesPlus/wiki/Debugging-Issues#players-cant-open-crates It will be some option relating to WorldGuard (or other plugin).
