### ISSUE TITLE
Holograms issue 2

### ISSUE THREAD

**Issue by Kirrasio** [ConnorLinfoot/CratesPlus#439]
**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

From version 4.3 there is a new '/crates debug' command. Running this will give you a single link with all the data I need to help you. Please run this and submit the share link with your issue.

Updated holograms is not working with cratesplus.

### Link/paste of stack trace/error (if any)

    You can also simply just use code formatting in markdown!
___We need all of the stack trace! Do not cut off parts of it.___

### Debug Link
___Enter your debug link from /crates debug___
https://mcdebug.xyz/cratesplus/share/YcG75EJ47J

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

**Comment by ConnorLinfoot** [comment]
CratesPlus does not support the Holograms plugin.

**Comment by Kirrasio** [comment]
Why in your plugin description does it say it works with holograms?

IE:
Holographic titles above crates, uses either Individual Holograms plugin or Holographic Displays.

**Comment by ConnorLinfoot** [comment]
It stats you can either use the Individual Holograms plugin or Holographic Displays? No where does it state you can use the Holograms plugin.

**Comment by Kirrasio** [comment]
What is the individual Holograms plugin? I believe I am a bit lost. Would
you consider making Holograms Plugin compatible with crates?

**Comment by ConnorLinfoot** [comment]
At this time I will not be adding support for other plugins.
