### ISSUE TITLE
Question (Version)

### ISSUE THREAD

**Issue by Supachi** [ConnorLinfoot/CratesPlus#441]
I have used this plugin on many of mc MC servers but would also use to love it on my modded MC server, however, modded minecraft is very outdated in terms of server versions, I was wondering if i was able to have this plugin to work for 1.2.5 minecraft? I am willing to pay as its a paid commission If you could do this for me to use on my modded server that would be great!

Best regards,
Jacko

**Comment by ConnorLinfoot** [comment]
I won't be adding support for older Minecraft versions at this time.
