### ISSUE TITLE
[Request] Getting Item from KeyCrateOpenEvent.java

### ISSUE THREAD

**Issue by Cobwebster** [ConnorLinfoot/CratesPlus#450]
Is it possible to add API for getting the item rewarded from the crate opened? 

I didn't see it anywhere, It could already be a thing though.

**Comment by ConnorLinfoot** [comment]
KeyCrateOpenEvent is fired before the crate actually opens and the winning is chosen. If you want to get the Winning you'd be best creating a custom opener.

**Comment by Cobwebster** [comment]
How would I go about doing that? Is it a easy thing?
