### ISSUE TITLE
Command to give playerheads?

### ISSUE THREAD

**Issue by DragaoNimhe** [ConnorLinfoot/CratesPlus#452]
Running the most recent version of CratesPlus, and I can't seem to figure out the proper syntax for including custom or playerheads in our crates. This was a big part of our planned reward system, I'd appreciate any help with this if it's even possible. I figure it would be Command as opposed to Item but nothing I've tried seems to work.

**Comment by ConnorLinfoot** [comment]
Sorry but I don't support with actually configuring the plugin. GitHub is for issues.
