### ISSUE TITLE
Adding To Crates

### ISSUE THREAD

**Issue by gappleburst** [ConnorLinfoot/CratesPlus#458]
**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

From version 4.3 there is a new '/crates debug' command. Running this will give you a single link with all the data I need to help you. Please run this and submit the share link with your issue.

### Link/paste of stack trace/error (if any)

    You can also simply just use code formatting in markdown!
___We need all of the stack trace! Do not cut off parts of it.___

### Debug Link
___Enter your debug link from /crates debug___

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

Ok, listen dude. I've posted here like twice before and my issues were always closed without solving my issue. I go into the config to add a "Winning" to a crate but it NEVER works. I've tried so many things and I've even tried copying exactly from your examples to add a winning. I restart my server and either the crate I created is now gone for some reason, or the new winning never loads. (Just example sword) I can't add any items to crates or commands and I've tried both many times. Please help me understand what I am doing wrong. I've even tried copying/pasting the example sword but just slightly changing it to see if it will add. I honestly am so confused and I'm sick and tired of not getting answers. Please just help me and don't close this post without a solution!

**Comment by ConnorLinfoot** [comment]
I can't help without any debug information.
