### ISSUE TITLE
Error, after restart

### ISSUE THREAD

**Issue by FyFou57** [ConnorLinfoot/CratesPlus#460]
**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

From version 4.3 there is a new '/crates debug' command. Running this will give you a single link with all the data I need to help you. Please run this and submit the share link with your issue.

### Debug Link
02.09 21:06:41 [Server] INFO AliHaine issued server command: /crate debug
02.09 21:06:41 [Server] WARN Exception in thread "Craft Scheduler Thread - 200" 
02.09 21:06:41 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin CratesPlus v4.4.2 generated an exception while executing task 1177677
02.09 21:06:41 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
02.09 21:06:41 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
02.09 21:06:41 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
02.09 21:06:41 [Server] INFO at java.lang.Thread.run(Thread.java:748)
02.09 21:06:41 [Server] INFO Caused by: java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
02.09 21:06:41 [Server] INFO at plus.crates.CratesPlus.uploadFile(CratesPlus.java:298)
02.09 21:06:41 [Server] INFO at plus.crates.CratesPlus.uploadConfig(CratesPlus.java:280)
02.09 21:06:41 [Server] INFO at plus.crates.Commands.CrateCommand$1.run(CrateCommand.java:114)
02.09 21:06:41 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
02.09 21:06:41 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
02.09 21:06:41 [Server] INFO ... 3 more
02.09 21:06:41 [Server] INFO Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.FileUtils
02.09 21:06:41 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
02.09 21:06:41 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
02.09 21:06:41 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
02.09 21:06:41 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
02.09 21:06:41 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
02.09 21:06:41 [Server] INFO ... 8 more

### Link/paste of stack trace/error (if any)

    You can also simply just use code formatting in markdown!
___We need all of the stack trace! Do not cut off parts of it.___

### Actions to reproduce (if known):
After restart serveur, i need too replace all crate box.... and percentage chance dont work.

**Comment by ConnorLinfoot** [comment]
You still haven't submitted the requested debug info.
