### ISSUE TITLE
Kit error

### ISSUE THREAD

**Issue by Gewoonlars773** [ConnorLinfoot/CratesPlus#461]
Hi i have problem with crateplus and essentials kits i want a kit with a crate key but it is not working when i have the kit i get the error 
(that kit is improperly defined. Contact an administrator.)

Can someone help me?

  Factions:
    delay: 86400
    items:
    - TRIPWIRE_HOOK 1 name:&dFactions_Crate_Key lore:&7Right-Click_on_a_"&dFactions&7"_crate_&7to_win_an_item!
      durability:1kits:1

**Comment by ConnorLinfoot** [comment]
You shouldn't be attempting to give the item as that could change at anytime. You should be running the key command.
