### ISSUE TITLE
keys breaking

### ISSUE THREAD

**Issue by cooklover** [ConnorLinfoot/CratesPlus#463]
so i use essentials for kits and if i add the key to crates it breaks but it use to not i use to have V4.2.4 but then i updated to V4.4.3 when i seen skulls got fixed but now the keys are not working in kits there away to fix this?

**Comment by ConnorLinfoot** [comment]
You should be using commands to give the key.

**Comment by cooklover** [comment]
what how would i make a comnand to give a key ever 24h with the plugin?
