### ISSUE TITLE
Some Enchanted Books not working, You only receive and see "Enchanted Book"

### ISSUE THREAD

**Issue by thomasdaley2** [ConnorLinfoot/CratesPlus#464]
Currently Trialing 4.4.2 but this was an issue in 4.4.3 also.  Version 5.0 doesnt let me create a chest so couldnt test.

### Debug Link
https://mcdebug.xyz/cratesplus/share/JpZuUOZzeX

### Link/paste of stack trace/error (if any)

WORKS:
      '2':
        Type: ITEM
        Item Type: ENCHANTED_BOOK
        Item Data: 0
        Name: NONE
        Percentage: 10        
        Amount: 1
        Enchantments: [MENDING-1]

DOESNT WORK:
      '3':
        Type: ITEM
        Item Type: ENCHANTED_BOOK
        Item Data: 0
        Name: NONE
        Percentage: 30
        Amount: 1
        Enchantments: [INFINITY-1]

**Comment by ConnorLinfoot** [comment]
"INFINITY" is not a valid enchantment, "ARROW_INFINITE" is the correct one. These can be found by looking up the enchantment java doc for your version.

**Comment by thomasdaley2** [comment]
where does one find the "Enchantment Java Doc?

**Comment by ConnorLinfoot** [comment]
Google, it can depend on your version.

**Comment by thomasdaley2** [comment]
thanks.  Putting it on your own webpage would help to stop similar question in future.. I have googled but have failed to find it so far. Thanks anyway.

**Comment by ConnorLinfoot** [comment]
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html is the link for 1.12.1. Other versions can be hard to find due to Spigot no longer hosting them when they update.

**Comment by thomasdaley2** [comment]
Legend... I thought you meant "Enchantment Java Doc" for Cratesplus and googling that..... got me nowhere.  You meant Spigot!   Thanks again

**Comment by thomasdaley2** [comment]
It doesnt make a proper Enchanted book.  Dam.  (not able to enchant anything) Back to the drawing board for this idea then.
