### ISSUE TITLE
Spawn Egg not appearing in crate

### ISSUE THREAD

**Issue by Luke1702** [ConnorLinfoot/CratesPlus#465]
For whatever reason I put in a spawnegg for example a pig spawn egg in the config file to put into one of my crates but whenever I restart it just deletes it and doesnt show up in the crate. This is what I typed for a pig spawn egg. but when I reload it just disappears from the config. Help pls

      '19':
        Type: ITEM
        Item Type: 383:90
        Item Data: 0
        Name: '&62x &aSpawn Pig'
        Amount: 2
        Enchantments: []
        Lore: []
        Metadata:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: §62x §aSpawn Pig

**Comment by jupiter1390** [comment]
Put 90 in Data value
Item type is 383 and data is 90

**Comment by Luke1702** [comment]
I tried that it isnt working

**Comment by ConnorLinfoot** [comment]
Please provide debug information as requested on the new issue screen.
