### ISSUE TITLE
opener, effects, chances

### ISSUE THREAD

**Issue by seema84** [ConnorLinfoot/CratesPlus#467]
Hello ConnorLinfoot,

1. Can you please add the csgo opener into the main plugin? I know its a example plugin but a tutorial in your wiki is enough.
2. Can you please add chest effects?
3. Can you please add a option to add items with chances?
4. Can you please add a option to make a opener slow down to the end?

thanks

**Comment by ConnorLinfoot** [comment]
1. Would rather keep this seperate.
2. Already an issue/plans for that.
3. Already implemented.
4. This would be a custom opener that you could create. Not something I plan on adding to the plugin.
