### ISSUE TITLE
Vote crate resets

### ISSUE THREAD

**Issue by InstantlyMoist** [ConnorLinfoot/CratesPlus#472]
**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

From version 4.3 there is a new '/crates debug' command. Running this will give you a single link with all the data I need to help you. Please run this and submit the share link with your issue.

### Debug Link
https://mcdebug.xyz/cratesplus/share/AMdhJEmjsv

### Link/paste of stack trace/error (if any)
The only error/message I get is '08.10 13:54:38 [Server] INFO [CratesPlus] vote crate already exists' and then it resets to default

### Actions to reproduce (if known):
Make a vote crate
(?)
See that it resets.

No patterns found.

Vote crate:
`Vote:
    Knockback: 0.0
    Block: CHEST
    Color: WHITE
    Broadcast: false
    Firework: false
    Preview: true
    Key:
      Item: TRIPWIRE_HOOK
      Name: '%type% Crate Key'
      Enchanted: true
    Winnings:
      '1':
        Type: ITEM
        Item Type: ENCHANTED_BOOK
        Item Data: 0
        Percentage: 5
        Name: NONE
        Amount: 1
        Enchantments: []
        Lore: []
      '2':
        Type: ITEM
        Item Type: ENCHANTED_BOOK
        Item Data: 0
        Percentage: 5
        Name: NONE
        Amount: 1
        Enchantments: []
        Lore: []
      '3':
        Type: ITEM
        Item Type: ENCHANTED_BOOK
        Item Data: 0
        Percentage: 5
        Name: NONE
        Amount: 1
        Enchantments: []
        Lore: []
      '4':
        Type: ITEM
        Item Type: ENCHANTED_BOOK
        Item Data: 0
        Percentage: 5
        Name: NONE
        Amount: 1
        Enchantments: []
        Lore: []
      '5':
        Type: ITEM
        Item Type: ENCHANTED_BOOK
        Item Data: 0
        Percentage: 5
        Name: NONE
        Amount: 1
        Enchantments: []
        Lore: []
      '6':
        Type: ITEM
        Item Type: OBSIDIAN
        Item Data: 0
        Percentage: 10
        Name: NONE
        Amount: 16
        Enchantments: []
        Lore: []
      '7':
        Type: ITEM
        Item Type: GOLDEN_APPLE
        Item Data: 0
        Percentage: 7
        Name: NONE
        Amount: 10
        Enchantments: []
        Lore: []
      '8':
        Type: ITEM
        Item Type: LINGERING_POTION
        Item Data: 0
        Percentage: 3
        Name: NONE
        Amount: 1
        Enchantments: []
        Lore: []
        Metadata:
          ==: ItemMeta
          meta-type: POTION
          potion-type: minecraft:water
      '9':
        Type: ITEM
        Item Type: TNT
        Item Data: 0
        Percentage: 5
        Name: NONE
        Amount: 8
        Enchantments: []
        Lore: []
      '10':
        Type: ITEM
        Item Type: TOTEM
        Item Data: 0
        Percentage: 3
        Name: NONE
        Amount: 1
        Enchantments: []
        Lore: []
      '11':
        Type: ITEM
        Item Type: TRIPWIRE_HOOK
        Item Data: 0
        Percentage: 1
        Name: '&fBlaze Crate Key'
        Amount: 1
        Enchantments:
        - DURABILITY-1
        Lore:
        - §7Right-Click on a "§fBlaze§7" crate
        - §7to win an item!
        - ''
        Metadata:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: §fBlaze Crate Key
          lore:
          - §7Right-Click on a "§fBlaze§7" crate
          - §7to win an item!
          - ''
          enchants:
            DURABILITY: 1
      '12':
        Type: ITEM
        Item Type: TRIPWIRE_HOOK
        Item Data: 0
        Percentage: 2
        Name: '&fVote Crate Key'
        Amount: 2
        Enchantments:
        - DURABILITY-1
        Lore:
        - §7Right-Click on a "§fVote§7" crate
        - §7to win an item!
        - ''
        Metadata:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: §fVote Crate Key
          lore:
          - §7Right-Click on a "§fVote§7" crate
          - §7to win an item!
          - ''
          enchants:
            DURABILITY: 1
      '13':
        Type: ITEM
        Item Type: PAPER
        Item Data: 0
        Percentage: 0.1
        Name: '&6Blaze &7rank voucher'
        Amount: 1
        Enchantments: []
        Lore:
        - §7Right click to receive §6Blaze §7rank!
        Metadata:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: §6Blaze §7rank voucher
          lore:
          - §7Right click to receive §6Blaze §7rank!
      '14':
        Type: ITEM
        Item Type: PAPER
        Item Data: 0
        Percentage: 0.9
        Name: '&c$10.000'
        Amount: 1
        Enchantments: []
        Lore:
        - §7Right click to receive $10000!
        Metadata:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: §c$10.000
          lore:
          - §7Right click to receive $10000!
      '15':
        Type: ITEM
        Item Type: EXP_BOTTLE
        Item Data: 0
        Percentage: 5
        Name: '&cExperience Bottle &7(Throw)'
        Amount: 1
        Enchantments: []
        Lore: []
        Metadata:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: §cExperience Bottle §7(Throw)
      '16':
        Type: ITEM
        Item Type: DIAMOND_BLOCK
        Item Data: 0
        Percentage: 5
        Name: NONE
        Amount: 1
        Enchantments: []
        Lore: []
      '17':
        Type: ITEM
        Item Type: DIAMOND_PICKAXE
        Item Data: 0
        Percentage: 7
        Name: NONE
        Amount: 1
        Enchantments:
        - DURABILITY-1
        - LOOT_BONUS_BLOCKS-1
        Lore: []
        Metadata:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DURABILITY: 1
            LOOT_BONUS_BLOCKS: 1
      '18':
        Type: ITEM
        Item Type: BOW
        Item Data: 0
        Percentage: 10
        Name: NONE
        Amount: 1
        Enchantments:
        - DURABILITY-1
        - ARROW_DAMAGE-1
        - ARROW_FIRE-1
        Lore: []
        Metadata:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DURABILITY: 1
            ARROW_DAMAGE: 1
            ARROW_FIRE: 1`

**Comment by ConnorLinfoot** [comment]
You have 2 vote crates in the config.yml.

**Comment by InstantlyMoist** [comment]
When I remove it and replace it by the one I sent with capital letter it will reset to the default one.

**Comment by InstantlyMoist** [comment]
I'll try to remove it only

**Comment by InstantlyMoist** [comment]
Didn't work.

08.10 15:07:51 [Server] INFO [CratesPlus] vote crate has been created

New debug
https://mcdebug.xyz/cratesplus/share/ekPIYDhYZ4

**Comment by InstantlyMoist** [comment]
Bump

**Comment by InstantlyMoist** [comment]
Can you tell me what's going wrong, when I remove the second vote crate it just regenerates it.

**Comment by InstantlyMoist** [comment]
I cleared the data file also, just ignores the fact it's cleared

**Comment by InstantlyMoist** [comment]
Can you give it a tag so I know if it's a bug or not

**Comment by InstantlyMoist** [comment]
Also, the precentage resets when adding new items via the ingame command.

**Comment by InstantlyMoist** [comment]
Please respond. I remove the second, 'vote' and reboot the server. Works fine I see all my rewards it works. but then I see the creating vote crate message and then it adds a new crate, override the other one. AND ITS ANNOYING.

https://mcdebug.xyz/cratesplus/share/EorO0YRaNq

**Comment by InstantlyMoist** [comment]
Up.

**Comment by InstantlyMoist** [comment]
bump

**Comment by InstantlyMoist** [comment]
BUMP

**Comment by ConnorLinfoot** [comment]
So following up with the reply to your Spigot 'review'. I've been unable to replicate this issue. You've stated you're seeing the message "vote crate has been created" but this only shows if someone runs the "/crate create <name>" command. You can even check the source code for this - https://github.com/ConnorLinfoot/CratesPlus/blob/8c4b6c25cee5d7035196f47269664d67f0fec804/src/main/java/plus/crates/Commands/CrateCommand.java#L256-L256

So it's likely that something on your server is mis-configured. Or you're just doing something wrong.

**Comment by InstantlyMoist** [comment]
Strange, this is my log file around the vote crate creation, I was setting up DeluxeTags and not doing anything crate-related 

16.10 13:39:50 [Server] INFO + Xylt
16.10 13:39:57 [Server] INFO Manager ♞ Xylt : Hello.
16.10 13:40:00 [Server] INFO [BuycraftX] Updating coupon list...
16.10 13:40:07 [Server] INFO Founder ♚ InstantlyMoist [#Split]: hi
16.10 13:40:11 [Server] INFO Founder ♚ InstantlyMoist [#Split]: sorry i was afk
16.10 13:40:13 [Server] INFO Founder ♚ InstantlyMoist [#Split]: making tags
16.10 13:40:18 [Server] INFO Founder ♚ InstantlyMoist [#Split]: *dnt use the command*
16.10 13:40:29 [Server] INFO Manager ♞ Xylt : I'm not sure the # looks great on that tag.
16.10 13:40:48 [Server] INFO Manager ♞ Xylt : Just my personal opinion.
16.10 13:40:53 [Server] INFO [CratesPlus] vote crate has been created
16.10 13:41:00 [Server] INFO Xylt issued server command: /fly
16.10 13:41:51 [Server] INFO Xylt issued server command: /tpo InstantlyMoist
16.10 13:42:22 [Server] INFO InstantlyMoist issued server command: /tags reload
