### ISSUE TITLE
Inconsistency: Key Name doesn't handle color conversion (& to §)

### ISSUE THREAD

**Issue by klugemonkey** [ConnorLinfoot/CratesPlus#473]
Using alternate color codes using & in the Key.Name string value doesn't get converted to § and displayed correctly.  Using § directly in the config.yml value does work.  Whereas you can use & in the Key.Lore string and it converts correctly.

Tested on latest 4.4.4 version.

**Comment by ConnorLinfoot** [comment]
Fixed in 5.0.
