### ISSUE TITLE
Fails to give crate Block: CAULDRON

### ISSUE THREAD

**Issue by klugemonkey** [ConnorLinfoot/CratesPlus#474]
Specifying CAULDRON as Block in the Crate section of the config.yml throws no error.  When giving the crate with the /crate crate CrateName it says properly that 'You have been given a %CrateName% crate', and also 'Given %player% a crate', but doesn't actually give the player the crate.

Manually editing the NBT data on a Cauldron to match the Name and Lore of a similar Chest type crate, actually is a work around and can be used to place the Cauldron crate.

**Comment by ConnorLinfoot** [comment]
This is how Minecraft/Bukkit handles cauldrons. The item material is CAULDRON_ITEM instead of just CAULDRON. Not really something that's worth me creating a work around.

**Comment by klugemonkey** [comment]
Thanks, I found that out.
