### ISSUE TITLE
Feature Request: %cratename% & %keyname%

### ISSUE THREAD

**Issue by klugemonkey** [ConnorLinfoot/CratesPlus#475]
There is no way to have a formatted Crate Name appear in the messages.

Would be useful to add a Name: value to the crate definition and allow the messages.yml to refer to this name with %cratename% rather than rely on the %crate% value which is linked to the YAML section.  This is needed not only to have spaces but to have specific formatting in multiple colors for the name.

Same goes for %keyname% to refer to the existing Name: value under the key section.  Sometimes we don't want to call the item they are receiving a key.  How to change the messages.yml to be selective about this for some crates and not for others?

**Comment by ConnorLinfoot** [comment]
I don't think putting time into the messages system is something of value for many. Whats there currently is the basics that most people need.

**Comment by klugemonkey** [comment]
Sorry to hear that.
