### ISSUE TITLE
Fixing Percentages

### ISSUE THREAD

**Issue by SiuanSong** [ConnorLinfoot/CratesPlus#479]
Currently, if you accidentally calculate your crate to over 100% and test it in game, the config deletes all the percentage lines for the items in that crate. 
I'd like to suggest having a way to calculate the total percentages in game with a command. /crate cratename percentage
Also, just having the crate be disabled instead of it deleting all percentage lines in the config file.

**Comment by ConnorLinfoot** [comment]
This limit is being removed in CratesPlus v5. Also from testing it doesn't remove them from the config if they exceed the 100% limit they just won't show in-game.
