### ISSUE TITLE
Option to Remove Holograms?

### ISSUE THREAD

**Issue by xGamingAsassinx** [ConnorLinfoot/CratesPlus#481]
Hello! 
I've been using CratesPlus for a very long time, at least 3 years ago. On my server, I was looking through the config, and either I'm very bad at looking, or there is no way to disable holograms. If this is something that has already been implemented, please let me know, but if not, can it be implemented maybe in v5? I just would rather have different holograms for each of my crates without having the same one for all four, since the colors of the names of my crates vary. Thank you for your time and I wish you a wonderful day! Excited for v5!

Sincerely, Nick

**Comment by ConnorLinfoot** [comment]
You can simply set the hologram text to be an empty list. For example to do this for all crates just set `Default Hologram Text: []` and it should cause no holograms to appear for the crates.
