### ISSUE TITLE
rewards not showing up on 1.7 servers

### ISSUE THREAD

**Issue by aycgit** [ConnorLinfoot/CratesPlus#482]
### Debug Link
broken on 1.7

### Link/paste of stack trace/error (if any)

none

### Actions to reproduce (if known):
create a config using the latest build and make multiple on a 1.7-1.8 supp server

### more
This server is running CraftBukkit version git-Spigot-1.7.9-R0.2-207-g03373bb (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)
1.7 server with some jar modification to let 1.8 ppl join, your spigot page says that this supports 1.7

config: https://gist.github.com/aycgit/d09c029cd72dca9637f6528cb032ddce
the whole file is good according to yml parser

edit: other crates seem to work but not this one, and  the /crate debug is still broken
edit: this only applies to the config part, the ingame editor works as a workaround

**Comment by ConnorLinfoot** [comment]
You're using invalid materials, I'm seeing at least `SUGARCANE` and `SOULSAND` being incorrect at first glance. They have to be a valid 1.7 [material](https://jd.bukkit.org/org/bukkit/Material.html).

**Comment by aycgit** [comment]
okay thanks, you should specify this and/or add errors so this can be found out
