### ISSUE TITLE
Crate Preview not showing every item in config

### ISSUE THREAD

**Issue by RegMCS** [ConnorLinfoot/CratesPlus#484]
### Debug Link
https://mcdebug.xyz/cratesplus/share/NKbWTQHIXq

### Link/paste of stack trace/error (if any)
Config file shows items typed in correctly but when reloaded in game, despite the crate plugin able to work perfectly, when i left click the crate it shows only 13 out of the 29 items i have keyed into the config.

    You can also simply just use code formatting in markdown!
___We need all of the stack trace! Do not cut off parts of it.___

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

**Comment by ConnorLinfoot** [comment]
>Your percentages must NOT add up to more than 100%
