### ISSUE TITLE
Can't give keys to all offline players

### ISSUE THREAD

**Issue by animeboi** [ConnorLinfoot/CratesPlus#485]
When I try using "/crate key all" to give every player (including offline) a key, it doesn't work.

Would you please either fix this or make a separate command that lets people do that? It's important to me because I'm trying to set up my Buycraft to give the whole server Legendary Keys when the community goal is reached.

**Comment by ConnorLinfoot** [comment]
The plugin doesn't support giving keys to offline players. It's possible but I'll want to do some testing with it first.

**Comment by animeboi** [comment]
![image](https://user-images.githubusercontent.com/30117600/32146100-fa85c188-bca8-11e7-9548-bcb43f4feff6.png)

**Comment by animeboi** [comment]
I've given individual people keys as well who are offline and it's worked ;/

**Comment by ConnorLinfoot** [comment]
I meant the all command doesn't, not overall 😛

**Comment by Freya778** [comment]
I would love this as a feature to be honest :D ! It would make it more fair for people that aren't online as much as others and don't afk.

**Comment by Pluginsel** [comment]
I don't like for '/crate key all' for offline players, is will cause the lag on server???
You possible to add this command for offline players? '/crate key allofflines' ?

**Comment by TheTARDIS2176** [comment]
I like the idea of this feature being a separate command as the idea behind a crate key all, if it's being given out by staff for an event maybe, it should only be those that are online that can get the key. It's also especially useful if you own a popular server with a lot of unique joins but say, only a fraction of that as an actual playerbase. It's cause a lot of lag.

**Comment by BlameXeno** [comment]
> I like the idea of this feature being a separate command as the idea behind a crate key all, if it's being given out by staff for an event maybe, it should only be those that are online that can get the key. It's also especially useful if you own a popular server with a lot of unique joins but say, only a fraction of that as an actual playerbase. It's cause a lot of lag.

I also would like to see this as a different command. Also, maybe you could have a setting in the config.yml to edit who the plugin give keys to in terms of activity. Say ExampleA hasn't been online for the last 40 days but ExampleB was on last night but has logged off, and in the config.yml you've specified the plugin to give keys to offline players who've last been online in the last 30 days, then ExampleA (along side every other non-active player) wouldn't receive a key when the command had been ran, but ExampleB would.
