### ISSUE TITLE
Editing crates while have command rewards

### ISSUE THREAD

**Issue by MattBess** [ConnorLinfoot/CratesPlus#486]
I was wondering if there is any possible way to edit the rewards of crates while they have a command set as a reward.  I tried using _/crate settings_  but I couldn't edit the rewards because 'You can not currently edit a crate in the GUI which has command items'

Would it be possible to add a command that allows you to add rewards to a crate instead of using the GUI?

**Comment by ConnorLinfoot** [comment]
The GUI is designed to basically be a "noob" way of configuring the crates and I currently don't plan on adding support for commands.
