### ISSUE TITLE
Percentages seem to be not working

### ISSUE THREAD

**Issue by SkyDevil-** [ConnorLinfoot/CratesPlus#49]
I created a config with a  test chest.
I placed Sponge at 1% and stone at 99%
I then used a stack of 64 keys after the keys where used up i had 31 sponge and 33 stone
Which kinda signals that they was both at 50 % chance

**Comment by SkyDevil-** [comment]
Sorry forgot the basics
http://pastebin.com/mEDeYgsG
server is running CraftBukkit version git-Spigot-5f38d38-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
Plugin Version 3.1.2

**Comment by ConnorLinfoot** [comment]
Looked into this (finally xD) seems like it happens if you change the GUI time, will be fixed in the next update :)

**Comment by ConnorLinfoot** [comment]
This issue no longer occurs in 4.0 (Snapshot 1)+
