### ISSUE TITLE
Holograms Wont load

### ISSUE THREAD

**Issue by Vacuouschimp** [ConnorLinfoot/CratesPlus#492]
Hello I'm having trouble when I load up my server the holograms aren't there please help me.

**Comment by Freya778** [comment]
Check your console log. My holograms don't work either and it said something about it not being supported normally anymore and there was another way you could get them to work.

You are using the built in handler for holograms. This will be removed in a future update! It is recommended to install Individual Holograms or HolographicDisplays which CratesPlus will then use to handle holograms. ---> This is what my console log said, and I read about it on the wiki or something as well. Might still be doable with the plugin itself, hopefully you can find it on the wiki.

Btw have the holograms even worked for you before? The ones that aren't there right now.

**Comment by bkGamingYT** [comment]
If you install HolographicDisplays then it will work automatically with CratesPlus

**Comment by ConnorLinfoot** [comment]
Please provide a debug link, will investigate further if provided.
