### ISSUE TITLE
Bug with percentages

### ISSUE THREAD

**Issue by Skormian** [ConnorLinfoot/CratesPlus#499]
Well my problem is a long time ago and I want to put percentages in the plugin configuration but it turns out that when you save it, it does not appear to stop all the server, do a reload and even reload from the same plugin but it still does not appear.
I need your help and I hope not to take your time.
Thanks for reading and taking a little time.
https://mcdebug.xyz/cratesplus/share/ERPjWDMOtV

**Comment by ConnorLinfoot** [comment]
I'm not sure what issue you're trying to report, the config works as expected.
