### ISSUE TITLE
NullPointerException while runing /crates reload

### ISSUE THREAD

**Issue by luniso** [ConnorLinfoot/CratesPlus#50]
There is the error log: http://pastebin.com/rPm9UcDs

**Comment by luniso** [comment]
When i use that config, something crashes and send an error when i try to see the winnings in-game or trying to open it. Config: http://pastebin.com/Vvbkwk7u
And the error log:http://pastebin.com/26wiDpJe

**Comment by ConnorLinfoot** [comment]
You'll be using invalid enchantment names.
