### ISSUE TITLE
Copying and pasting

### ISSUE THREAD

**Issue by mrblake213** [ConnorLinfoot/CratesPlus#500]
Hi
So I had a server at version 1.10 before and the crates was perfectly doing fine but we switched to 1.8 and I just copied and pasted the config from 1.10 and 1.8 but it started getting bugs again.

What is wrong with my config?
https://mcdebug.xyz/cratesplus/share/kJF6IkKaxx

Thank you.

**Comment by ConnorLinfoot** [comment]
I wouldn't use a config from a newer version of Minecraft as each version stores and handles data in different ways.
