### ISSUE TITLE
Plugin on server, /crate doesnt work, nothing shows up.

### ISSUE THREAD

**Issue by Tylerr04** [ConnorLinfoot/CratesPlus#502]
Hello, I have had the crate plugin for a day and it's worked all yesterday and today then all of the sudden it doesnt, the /crate command doesnt work whats so ever, the plugin is on the server.
 Please help

**Comment by ConnorLinfoot** [comment]
Have you checked the server log? Please post more information such as your whole server log. Does the plugin also show in "/plugins" as red or green?
