### ISSUE TITLE
Item Deletion Bug

### ISSUE THREAD

**Issue by blazex224** [ConnorLinfoot/CratesPlus#508]
Hello,
I've been loving your plugin ever since I've started using it, and I'd just like to thank you for taking the time to build this helpful resource. I really appreciate it, and I'm sure thousands of others will agree.

I've found a bug where when you are opening a crate, and it is spinning, if you left-click or right-click an item in your inventory, it will delete, and it cannot be received by logging out and back in. I'm using the latest version 4.4.4 and my spigot is up to date.

Thanks!

**Comment by ConnorLinfoot** [comment]
If this is still happening please can you open a new issue with the debug information detailed when clicking the New Issue button.
