### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by luniso** [ConnorLinfoot/CratesPlus#51]
I have testing the percentage feature, and i think that you can't make something be difficult to get, because they have to make an addition of 100, so when you have a lot of winnings set, you can't set something lower than 1, so it isn't hard at all to take every prize.
If you can and want, you could make a system to make lower percentages or make a way to difficult of getting an specific winning.
Regards, Luis.

**Comment by jon4397** [comment]
Agreed, there needs to be a percentage option. You can make a percentage of sorts by putting 2 helmets and one chestplate in the chest, making a 66% chance of getting a helmet and a 33% of getting a chestplate, but you can't do this with partial stacks of items. Please add a percentage option.

**Comment by ConnorLinfoot** [comment]
A percentage option already exists? I've had some reports of it not working correctly but that's all. it's on my list to check when i get time to look into it.
