### ISSUE TITLE
UNBREAKABLE ENCHANT request

### ISSUE THREAD

**Issue by Darkweasam** [ConnorLinfoot/CratesPlus#512]
Please, it's a must for my server!
Wish to give unbreakable diamond sword and other stuff for the rarest crates

**Comment by ConnorLinfoot** [comment]
This is already possible, if I remember correctly the Bukkit name for Unbreaking is `DURABILITY`

**Comment by Darkweasam** [comment]
Nope thats unbreaking you talking about
I want Unbreakable enchantment which has no levels, its only function is that the tool cannot be damaged in any way, in other words it has infinite durability
