### ISSUE TITLE
Can i get more than 9 Items in a crate?

### ISSUE THREAD

**Issue by gizmobrat** [ConnorLinfoot/CratesPlus#514]
**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

From version 4.3 there is a new '/crates debug' command. Running this will give you a single link with all the data I need to help you. Please run this and submit the share link with your issue.

### Debug Link
https://mcdebug.xyz/cratesplus/share/F8ASo6T7YJ

### Link/paste of stack trace/error (if any)

N/A

### Actions to reproduce (if known):
Use my configs

**Comment by ConnorLinfoot** [comment]
Yes, just add more than 9 items to the config. Make sure all Item Types are valid; https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
