### ISSUE TITLE
Issues with the configuration of a crate using commands

### ISSUE THREAD

**Issue by Draguni** [ConnorLinfoot/CratesPlus#515]
I am having issues with the configuration of a crate with commands in it.

### Debug Link
https://mcdebug.xyz/cratesplus/share/zCQmzbsCyo

### Actions to reproduce (if known):
Just try to open the crate.

**Comment by ConnorLinfoot** [comment]
I would need more information than "Just try to open the crate" considering I don't have your server setup.
