### ISSUE TITLE
CratesPlus - Items not showing up in crates

### ISSUE THREAD

**Issue by nbdSteve** [ConnorLinfoot/CratesPlus#516]
Hello!
I am a big fan of the crates plus plugin, however I have been having some problems with items not showing up in the crates and they cant be won. In my config I have about 40 items in the crate named 'meta' they all have their own percentages which add up to 100% exactly overall. I'm not sure what is going wrong and I cant seem to fix it, even if I can the percentages of items. 
Thanks, Steve

### Debug Link
https://mcdebug.xyz/cratesplus/share/MipSvRfauA

### Actions to reproduce (if known):
Image of problem: https://imgur.com/a/kx0a6

**Comment by ConnorLinfoot** [comment]
Item's won't load if they don't have a valid `Item Type`. For example I've noticed you've used "402" as an item type, which is not valid.

Looks like you're on Bukkit 1.8, here is a valid list of Materials/Item Types: http://docs.codelanx.com/Bukkit/1.8/org/bukkit/Material.html
