### ISSUE TITLE
exception while executing task 82

### ISSUE THREAD

**Issue by PortGasMC** [ConnorLinfoot/CratesPlus#519]
on startup 
https://pastebin.com/jZGahsdb
debug link
https://mcdebug.xyz/cratesplus/share/ZuIOpOg7Xo

**Comment by ConnorLinfoot** [comment]
This error shouldn't affect the plugin as it is only for  the update checker. However the issue has been resolved and is fixed in  v4.4.5 - https://www.spigotmc.org/resources/cratesplus-free-crates-plugin-1-7-1-12-2.5018/
--
