### ISSUE TITLE
Name and Items

### ISSUE THREAD

**Issue by aviswing** [ConnorLinfoot/CratesPlus#52]
When i am trying to give a user 128 TNT (For my Factions world) and i say (in the config) that i want it to give them 128 TNT if they win it, after reloading it shows up as 2 stacks if I left click the chest.
The other problem is that it is called '128 TNT' when i want it to be called the normal name of TNT (Depends what language you speak).

How do i fix these issues?

Cheers,
Avi.

**Comment by ConnorLinfoot** [comment]
This issue should be fixed in the next update (Version 4.0 most likely)

**Comment by ConnorLinfoot** [comment]
This issue no longer occurs in 4.0 (Snapshot 1)+
