### ISSUE TITLE
Found this error close to the server start

### ISSUE THREAD

**Issue by MithrandirCraft** [ConnorLinfoot/CratesPlus#523]
### Debug Link
https://mcdebug.xyz/cratesplus/share/EiA9sNxUiT

### Link/paste of stack trace/error (if any)
This is the largest chunk I could get:
https://hastebin.com/ojukovusuc.rb

### Actions to reproduce (if known):
No idea, I just started the serever and saw this.

**Comment by ConnorLinfoot** [comment]
Update to v4.4.5
