### ISSUE TITLE
[CratesPlus] Display Chance Feature

### ISSUE THREAD

**Issue by xinxcode** [ConnorLinfoot/CratesPlus#524]
**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

From version 4.3 there is a new '/crates debug' command. Running this will give you a single link with all the data I need to help you. Please run this and submit the share link with your issue.

### Debug Link
___Enter your debug link from `/crates debug`. Not providing this may result in the issue being closed without warning. If you are unable to use this command please provide your Bukkit version, a list of plugins and your config.yml for CratesPlus.___

### Link/paste of stack trace/error (if any)

    You can also simply just use code formatting in markdown!
___We need all of the stack trace! Do not cut off parts of it.___

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

===============================
Please add feature to make winning chance dissappear from previewing mode.
Sometimes people requesting to increase the chance in server's forum, it's so intruding our staff work.
Thanks.

**Comment by xinxcode** [comment]
Oh Im sorry, it's been resolved by my friend.
For sorry I want to give suggestion for adding full list of words + function in config.
It'll be very helpfull..
Thanks

**Comment by ConnorLinfoot** [comment]
Your orignal suggestion already exists and I'm not sure what you mean in your comment.
