### ISSUE TITLE
Deletes All My Crates When I Put in the Config

### ISSUE THREAD

**Issue by Messi10noah** [ConnorLinfoot/CratesPlus#53]
Whenever I add this to the server it just deletes all of the crates... I added up the percents and it equals exactly 100% and I'm pretty sure all my notation and typing is correct, so I dont know whats wrong... here is the config.  http://pastebin.com/nEULz2R2

**Comment by ConnorLinfoot** [comment]
Make sure you are configuring it correctly, probably use the example to start with: http://pastebin.com/grPRrSXp
