### ISSUE TITLE
Chest opening glitch in v4.4.4 (Didn't have it in v4.3)

### ISSUE THREAD

**Issue by BlameXeno** [ConnorLinfoot/CratesPlus#530]
**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

From version 4.3 there is a new '/crates debug' command. Running this will give you a single link with all the data I need to help you. Please run this and submit the share link with your issue.

### Debug Link
https://mcdebug.xyz/cratesplus/share/PANGzHgTin

### Link/paste of stack trace/error (if any)
`[Mon, 19. Mar 2018 20:07:44 EDT ERROR] Could not pass event PlayerInteractEvent to CratesPlus v4.4.4
[Mon, 19. Mar 2018 20:07:44 EDT ERROR] Could not pass event PlayerInteractEvent to CratesPlus v4.4.4
[Mon, 19. Mar 2018 20:07:45 EDT ERROR] Could not pass event PlayerInteractEvent to CratesPlus v4.4.4`

### Actions to reproduce (if known):
I wish I knew what the hell is going on

**Comment by ConnorLinfoot** [comment]
There would be more to an exception, please can you post the rest of the exception.

**Comment by BlameXeno** [comment]
That is all there is however the error occurred was after I reloaded the plugin which is a bad move

**Comment by BlameXeno** [comment]
Ignore my last message, I missed this when restarting the entire server

`24.03 07:51:33 [Server] WARN [CratesPlus] Plugin CratesPlus v4.4.4 generated an exception while executing task 99
24.03 07:51:33 [Server] INFO java.lang.NullPointerException: null
24.03 07:51:33 [Server] INFO at plus.crates.Utils.SpigotUpdater.runSpigot(SpigotUpdater.java:59) ~[?:?]
24.03 07:51:33 [Server] INFO at plus.crates.Utils.SpigotUpdater.<init>(SpigotUpdater.java:40) ~[?:?]
24.03 07:51:33 [Server] INFO at plus.crates.CratesPlus.checkUpdate(CratesPlus.java:357) ~[?:?]
24.03 07:51:33 [Server] INFO at plus.crates.CratesPlus.access$000(CratesPlus.java:27) ~[?:?]
24.03 07:51:33 [Server] INFO at plus.crates.CratesPlus$1.run(CratesPlus.java:240) ~[?:?]
24.03 07:51:33 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.1.jar:git-Spigot-da42974-8f47214]
24.03 07:51:33 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.1.jar:git-Spigot-da42974-8f47214]
24.03 07:51:33 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
24.03 07:51:33 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
24.03 07:51:33 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]`

**Comment by ConnorLinfoot** [comment]
This is caused by the URL of the updater changing on Spigots side, update to the latest version.
