### ISSUE TITLE
Question on oppeners

### ISSUE THREAD

**Issue by dalton62398** [ConnorLinfoot/CratesPlus#531]
i honestly just dont understand how to get the csgo opener to work, i have tried different names for the config i just cant seem to get it. it just bypasses the opener and gives the item right off the bat. i know its a dumb thing to ask i just dont understand it

**Comment by QUIQUELHAPPY** [comment]
CSGO

That's it, should look like that. Install the [csgo opener jar](https://www.spigotmc.org/resources/csgo-opener-cratesplus.24027/) on your plugins folder too
```
...
Metrics: true
Default Opener: CSGO
Default Cooldown: 5
...
```

**Comment by dalton62398** [comment]
it still doesnt work

**Comment by QUIQUELHAPPY** [comment]
do you have the last version of CratesPlus?

**Comment by ConnorLinfoot** [comment]
What doesn't work? Are you able to provide the debug link from `/crates debug`
