### ISSUE TITLE
Crates disappearing on restart (Error while enabling CratesPlus v4.5.5)

### ISSUE THREAD

**Issue by jPark195** [ConnorLinfoot/CratesPlus#534]
https://mcdebug.xyz/cratesplus/share/LXcTXBf2yi

`04.04 17:30:01 [Server] ERROR Error occurred while enabling CratesPlus v4.4.5 (Is it up to date?) 04.04 17:30:01 [Server] INFO java.lang.NullPointerException: null 04.04 17:30:01 [Server] INFO at org.bukkit.Location.getBlock(Location.java:91) ~[spigot_latest.jar:git-Spigot-c3093ef-7e94e65] 04.04 17:30:01 [Server] INFO at plus.crates.CratesPlus.loadMetaData(CratesPlus.java:443) ~[?:?] 04.04 17:30:01 [Server] INFO at plus.crates.CratesPlus.onEnable(CratesPlus.java:212) ~[?:?] 04.04 17:30:01 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot_latest.jar:git-Spigot-c3093ef-7e94e65] 04.04 17:30:01 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot_latest.jar:git-Spigot-c3093ef-7e94e65] 04.04 17:30:01 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot_latest.jar:git-Spigot-c3093ef-7e94e65] 04.04 17:30:01 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot_latest.jar:git-Spigot-c3093ef-7e94e65] 04.04 17:30:01 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot_latest.jar:git-Spigot-c3093ef-7e94e65] 04.04 17:30:01 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot_latest.jar:git-Spigot-c3093ef-7e94e65] 04.04 17:30:01 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot_latest.jar:git-Spigot-c3093ef-7e94e65] 04.04 17:30:01 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot_latest.jar:git-Spigot-c3093ef-7e94e65] 04.04 17:30:01 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot_latest.jar:git-Spigot-c3093ef-7e94e65] 04.04 17:30:01 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot_latest.jar:git-Spigot-c3093ef-7e94e65] 04.04 17:30:01 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]`

Running on 1.12. Plugin works fine, but crates disappear on server restart. Attempted fix from [issue 158](https://github.com/ConnorLinfoot/CratesPlus/issues/158) and was unsuccessful. Works fine on my other server.

**Comment by ConnorLinfoot** [comment]
Should be fixed in v5

**Comment by SirSilverYT** [comment]
This is also affecting me when shall this v5 be ready

**Comment by j19mes** [comment]
also a problem for me

**Comment by LE0ZY** [comment]
me too
