### ISSUE TITLE
Non Ops can't use the Crates 

### ISSUE THREAD

**Issue by ItsWulff** [ConnorLinfoot/CratesPlus#54]
Well i dont know why but for some reason non ops cant use my Crates and im pretty sure its a plugin thats blocking it and i dont know which plugin it could be help please? :D
Plugins: Vault, Buycraft, GAListener, EssentialsSpawn, EssentialsProtect, EssentialsChat, Essentials, Group Manager, ScoreboardStats, SilkSpawners, CratesPlus(3.1.2), CombatLog, Citizens, Votifier, WorldEdit & WorldGuard

**Comment by ConnorLinfoot** [comment]
I'm not here to sort your problems on your server. I don't have time to support everyone who has misconfiguration on their servers.

**Comment by ItsWulff** [comment]
Well Thanks! i guess im just gonna use another plugin instead of this shit
