### ISSUE TITLE
Can't Use Item Data for Keys

### ISSUE THREAD

**Issue by aulrone** [ConnorLinfoot/CratesPlus#550]
Issue:
Can't use item data, colored dyes or wools, for keys or method isn't known anywhere on the wiki/documentation/website. Using any method of data values produces an unhanded exception.

The following examples do not work:
    Key:
      Item: INK_SACK
      Item Data: 7

    Key:
      Item: INK_SACK
      Item Type: INK_SACK
      Item Data: 7

    Key:
      Item: INK_SACK, 1, 7

    Key:
      Item: LIME_DYE

    Key:
      Item: DYE

    Key:
      Item: DYE
      Item Data: 7

Replacing Item: value with any java language will also not work. E.g. Material.INK_SACK:10 etc.

**Comment by ConnorLinfoot** [comment]
Yeah currently it's not possible, it's already in the next v5 snapshot. Whenever that gets pushed 🙃
