### ISSUE TITLE
Percentages (Suggestion)

### ISSUE THREAD

**Issue by jef21** [ConnorLinfoot/CratesPlus#557]
**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

### Debug Link
~~___Enter your debug link from `/crates debug`. Not providing this may result in the issue being closed without warning. If you are unable to use this command please provide your Bukkit version, a list of plugins and your config.yml for CratesPlus.___~~

Due to a change in the GitHub Gist API the debug command currently doesn't work. Please can you upload your `config.yml` and provide your Bukkit version. If possible a plugin list and providing your `data.yml` is also appreciated and may be requested if needed.

### Link/paste of stack trace/error (if any)

    You can also simply just use code formatting in markdown!
___We need all of the stack trace! Do not cut off parts of it.___

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Hello, I was wondering if you were able to make it so we can make percentages to go higher than 100%. Or, we can choose what percentage we want on a crate. This would make the plugin better in my opinion. This is the best plugin iv'e seen for crates. But its missing the percentages to be set to how much we want.

**Comment by ConnorLinfoot** [comment]
Coming in CratesPlus v5, see #435
