### ISSUE TITLE
Crate Only Displaying First Nine Items

### ISSUE THREAD

**Issue by Glident** [ConnorLinfoot/CratesPlus#560]
**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

### Debug Link
~~___Enter your debug link from `/crates debug`. Not providing this may result in the issue being closed without warning. If you are unable to use this command please provide your Bukkit version, a list of plugins and your config.yml for CratesPlus.___~~

Due to a change in the GitHub Gist API the debug command currently doesn't work. Please can you upload your `config.yml` and provide your Bukkit version. If possible a plugin list and providing your `data.yml` is also appreciated and may be requested if needed.

### Link/paste of stack trace/error (if any) https://pastebin.com/fpvc85zZ <- Config File
Bukkit Version git-Spigot-2086bb0-8cc5a7e (MC: 1.12.2)

    You can also simply just use code formatting in markdown!
___We need all of the stack trace! Do not cut off parts of it.___

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
I have three crates in total. One of them, the supply crate, is only showing the first nine items defined in the config.

**Comment by ConnorLinfoot** [comment]
Sorry for the delay in getting back on this issue, but your problem is that `TOTEM_OF_UNDYING` is not valid for 1.12. The correct material is just `TOTEM`.
