### ISSUE TITLE
Winnings not showing while rolling

### ISSUE THREAD

**Issue by KerchooK** [ConnorLinfoot/CratesPlus#561]
Here is my config file
https://hastebin.com/wezicikabe.nginx

Here is my data file
https://hastebin.com/eyimuxapes.rb

Plugins:
AsyncWorldEditInjector, Orebfuscator4, Essentials_WarpGUI, PlaytimeRewards, ClearLag, WorldBorder, HolographicDisplays, BuycraftX, Votifier, BlowableObsidians, AsyncWorldEdit, CustomEnchants, Autoeye, PermissionsEx, Vault, MassiveCore, CratesPlus, WorldEdit, Essentials, MineSpawners, WorldGuard, EssentialsProtect, CrazyAuctions, EssentialsChat, SuperbVote, EssentialsSpawn, Factions

I am using the latest spigot 1.12.2 build.

There is no error thrown.

When you have the same item type for multiple winnings, only one is shown while rolling. As an example, if I had two winnings and both were set to the item type of paper only one will be displayed.

**Comment by ConnorLinfoot** [comment]
Those links seem to be empty? Can't help without some that work :P

**Comment by ConnorLinfoot** [comment]
Links seem to work now, will try and see if I can tell you the problem asap.

**Comment by ConnorLinfoot** [comment]
Nevermind it doesn't work again, I'd recommend Pastebin if you can upload it again. Sorry for only just responding been quite busy recently.
