### ISSUE TITLE
How do I clear a crate key from the player's inventory through commands?

### ISSUE THREAD

**Issue by FlashHUN** [ConnorLinfoot/CratesPlus#565]
For some odd reason neither /clear nor /clearinventory recognize the item as what it is when it is a crate key. Any solution?

(MC Version: 1.7.10)
(CratesPlus Version: 4.4.5)

**Comment by ConnorLinfoot** [comment]
There isn't a method to do this within CratesPlus, you would have to do something custom or find another plugin to assist with this.
