### ISSUE TITLE
Gui timing

### ISSUE THREAD

**Issue by DeepestHeart** [ConnorLinfoot/CratesPlus#566]
I've been trying to scan the configs for an option to change the amount of time it takes for the gui to roll each crate open. Right now it takes about 12 seconds give or take but when you're sitting there waiting for the crate to finish it feels like an eternity. Is there an option somewhere to change this or is it possible to add this?

**Comment by ConnorLinfoot** [comment]
There is a config option for each opener within `plugins/CratesPlus/openers`
