### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by Blazingfighter3** [ConnorLinfoot/CratesPlus#57]
opped people can open them but none opped people can't and i've tried removing/adding plugins and editing plugins and nothings worked so it's clearly the plugin, please fix and/or help me as this really bugs me.

thanks!

**Comment by Blazingfighter3** [comment]
https://gyazo.com/8a76ad886ed4030b268a6b870b00cc01

that's the list of my plugins and before you say "it's THIS PLUGIN" or "it's THAT PLUGIN" don't bother, like i said i tried removing/adding them and i tried editing them.

**Comment by ConnorLinfoot** [comment]
Either a conflicting plugin or spawn protection.

**Comment by Blazingfighter3** [comment]
Like i said, it's nothing to do with my plugins, you clearly didn't read what i put, and spawn protection is 1......

**Comment by ConnorLinfoot** [comment]
I can not replicate this issue. I've not had anyone else report the same issue of which is not being caused by something else. It'll either be another plugin is a misconfiguration.

**Comment by thaw2004** [comment]
I have this same issue,
