### ISSUE TITLE
Only 2 item showing up

### ISSUE THREAD

**Issue by RhysesPuff** [ConnorLinfoot/CratesPlus#570]
**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

### Debug Link
~~___Enter your debug link from `/crates debug`. Not providing this may result in the issue being closed without warning. If you are unable to use this command please provide your Bukkit version, a list of plugins and your config.yml for CratesPlus.___~~

Due to a change in the GitHub Gist API the debug command currently doesn't work. Please can you upload your `config.yml` and provide your Bukkit version. If possible a plugin list and providing your `data.yml` is also appreciated and may be requested if needed.

### Link/paste of stack trace/error (if any)

    You can also simply just use code formatting in markdown!
___We need all of the stack trace! Do not cut off parts of it.___

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

Hi,
I am trying to configure CratesPlus on my server using the configuration file however only 2 items show up.

Any help would be appreciated,
Thanks,

/crate debug doesn't work:

Version: 1.8.8
Config.yml:
`# [][][][][][][][][][][][][][][][][][][][][]
#  CratesPlus V4.4.5 Config
# [][][][][][][][][][][][][][][][][][][][][]
# ------------------------------------------
# There are many placeholders that can now be used withing the config and messages file, placeholders are as followed:
# - %name% - Replaces with the players name, Example: "Notch".
# - %displayname% - Replaces with the players display name, Example: "[Owner] Notch".
# - %uuid% - Replaces with the players UUID.
# - %crate% - The crate types name.
# - %prize% - The name of the winning.
# - %percentage% - Percentage of the winning, useful for "Chance Message".
# - %rand;100;500% - Generates a random number between two numbers, example is between 100 and 500.
# ------------------------------------------
# Don't change the config version!

Config Version: 6
Update Checks: false
Update Branch: spigot
Metrics: true
Default Opener: BasicGUI
Default Cooldown: 5
Crate Protection: false
Disable Key Swapping: false
Default Hologram Text:
- '%crate%'
- Right-Click to Open!
- Left-Click to Preview!
Crates:
  Vote:
    Key:
      Item: TRIPWIRE_HOOK
      Name: '%type% Crate Key'
      Enchanted: true
    Knockback: 0.0
    Broadcast: false
    Firework: false
    Preview: true
    Block: CHEST
    Color: GREEN
    Winnings:
      '1':
        Type: COMMAND
        Item Type: BOOK
        Item Data: 0
        Percentage: 30
        Commands:
        - 'eco give %name% 50000'
        Name: '&b$50 Thousand'
        Amount: 1
        Enchantments:
        - DAMAGE_ALL-1
        Lore: []
        Metadata:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 1
      '2':
        Type: COMMAND
        Item Type: BOOK
        Item Data: 0
        Percentage: 40
        Commands:
        - 'eco give %name% 25000'
        Name: '&b$25 Thousand'
        Amount: 1
        Enchantments:
        - DAMAGE_ALL-1
        Lore: []
        Metadata:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 1
      '3':
        Type: COMMAND
        Item Type: BOOK
        Item Data: 0
        Percentage: 50
        Commands:
        - 'eco give %name% 15000'
        Name: '&b$15 Thousand'
        Amount: 1
        Enchantments:
        - DAMAGE_ALL-1
        Lore: []
        Metadata:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 1
      '4':
        Type: COMMAND
        Item Type: BOOK
        Item Data: 0
        Percentage: 50
        Commands:
        - 'eco give %name% 10000'
        Name: '&b$10 Thousand'
        Amount: 1
        Enchantments:
        - DAMAGE_ALL-1
        Lore: []
        Metadata:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 1
      '5':
        Type: ITEM
        Item Type: DIAMOND_HELMET
        Item Data: 0
        Name: NONE
        Amount: 1
        Enchantments:
        - PROTECTION_ENVIRONMENTAL-5
        - DURABILITY-5
        Lore: []
        Metadata:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 5
            DURABILITY: 5
      '6':
        Type: ITEM
        Item Type: DIAMOND_CHESTPLATE
        Item Data: 0
        Name: NONE
        Amount: 1
        Enchantments:
        - PROTECTION_ENVIRONMENTAL-5
        - DURABILITY-5
        Lore: []
        Metadata:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 5
            DURABILITY: 5
      '7':
        Type: ITEM
        Item Type: DIAMOND_LEGGINGS
        Item Data: 0
        Name: NONE
        Amount: 1
        Enchantments:
        - PROTECTION_ENVIRONMENTAL-5
        - DURABILITY-5
        Lore: []
        Metadata:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 5
            DURABILITY: 5
      '8':
        Type: ITEM
        Item Type: DIAMOND_BOOTS
        Item Data: 0
        Name: NONE
        Amount: 1
        Enchantments:
        - PROTECTION_ENVIRONMENTAL-5
        - DURABILITY-5
        Lore: []
        Metadata:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 5
            DURABILITY: 5
      '9':
        Type: ITEM
        Item Type: DIAMOND_SWORD
        Item Data: 0
        Name: NONE
        Amount: 1
        Enchantments:
        - DAMAGE_ALL-5
        - DURABILITY-5
        - FIRE_ASPECT-2
        Lore: []
        Metadata:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 5
            FIRE_ASPECT: 2
            DURABILITY: 5
      '10':
        Type: ITEM
        Item Type: EXP_BOTTLE
        Item Data: 0
        Name: NONE
        Amount: 64
        Enchantments: []
        Lore: []
      '11':
        Type: ITEM
        Item Type: TRIPWIRE_HOOK
        Item Data: 0
        Name: '&dHero Crate Key'
        Amount: 1
        Enchantments:
        - DURABILITY-1
        Lore:
        - §7Right-Click on a "§dHero§7" crate
        - §7to win an item!
        - ''
        Metadata:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: §dHero Crate Key
          lore:
          - §7Right-Click on a "§dHero§7" crate
          - §7to win an item!
          - ''
          enchants:
            DURABILITY: 1
  Hero:
    Winnings:
      '1':
        Type: ITEM
        Item Type: IRON_SWORD
        Item Data: 0
        Percentage: 0
        Name: '&6&lExample Sword'
        Amount: 1
    Key:
      Item: TRIPWIRE_HOOK
      Name: '%type% Crate Key'
      Enchanted: true
    Knockback: 0.0
    Broadcast: false
    Firework: false
    Preview: true
    Block: CHEST
    Color: LIGHT_PURPLE
  Eternal:
    Winnings:
      '1':
        Type: ITEM
        Item Type: IRON_SWORD
        Item Data: 0
        Percentage: 0
        Name: '&6&lExample Sword'
        Amount: 1
    Key:
      Item: TRIPWIRE_HOOK
      Name: '%type% Crate Key'
      Enchanted: true
    Knockback: 0.0
    Broadcast: false
    Firework: false
    Preview: true
    Block: ENDER_CHEST
    Color: DARK_AQUA
  Legendary:
    Winnings:
      '1':
        Type: ITEM
        Item Type: IRON_SWORD
        Item Data: 0
        Percentage: 0
        Name: '&6&lExample Sword'
        Amount: 1
    Key:
      Item: TRIPWIRE_HOOK
      Name: '%type% Crate Key'
      Enchanted: true
    Knockback: 0.0
    Broadcast: false
    Firework: false
    Preview: true
    Block: CHEST
    Color: YELLOW
  Ultra:
    Winnings:
      '1':
        Type: ITEM
        Item Type: IRON_SWORD
        Item Data: 0
        Percentage: 0
        Name: '&6&lExample Sword'
        Amount: 1
    Key:
      Item: TRIPWIRE_HOOK
      Name: '%type% Crate Key'
      Enchanted: true
    Knockback: 0.0
    Broadcast: false
    Firework: false
    Preview: true
    Block: CHEST
    Color: BLACK
  Immortal:
    Winnings:
      '1':
        Type: ITEM
        Item Type: IRON_SWORD
        Item Data: 0
        Percentage: 0
        Name: '&6&lExample Sword'
        Amount: 1
    Key:
      Item: TRIPWIRE_HOOK
      Name: '%type% Crate Key'
      Enchanted: true
    Knockback: 0.0
    Broadcast: false
    Firework: false
    Preview: true
    Block: CHEST
    Color: GOLD
  Titan:
    Winnings:
      '1':
        Type: ITEM
        Item Type: IRON_SWORD
        Item Data: 0
        Percentage: 0
        Name: '&6&lExample Sword'
        Amount: 1
    Key:
      Item: TRIPWIRE_HOOK
      Name: '%type% Crate Key'
      Enchanted: true
    Knockback: 0.0
    Broadcast: false
    Firework: false
    Preview: true
    Block: CHEST
    Color: RED
`

**Comment by ConnorLinfoot** [comment]
Can you please upload your config to an external website, such as https://pastebin.com

**Comment by jkjokeryt** [comment]
my server is doing the same thing should I do the same thing

**Comment by jkjokeryt** [comment]
I did finish all the percentages but deleted some and some of the items came back I thought it was the items so I took some of them out bt it wasn't the case heres the paste bin https://pastebin.com/htS6zgpJ

**Comment by ConnorLinfoot** [comment]
@jkjokeryt If you use percentages they must all have them set. And be higher than 0 and add up to 100%

**Comment by jkjokeryt** [comment]
I did but it still didn't work

**Comment by ConnorLinfoot** [comment]
@jkjokeryt Well in your config you didn't :P Please open a separate issue and follow the instructions, please.
