### ISSUE TITLE
Crates only using first 13 of 20 listed winning items

### ISSUE THREAD

**Issue by hecbridge1** [ConnorLinfoot/CratesPlus#573]
[cratesplus-debug-dump-9-10-2018-and-plugin-list.txt](https://github.com/ConnorLinfoot/CratesPlus/files/2367883/cratesplus-debug-dump-9-10-2018-and-plugin-list.txt)
[data_yml.txt](https://github.com/ConnorLinfoot/CratesPlus/files/2367885/data_yml.txt)
[config_yml.txt](https://github.com/ConnorLinfoot/CratesPlus/files/2367888/config_yml.txt)

**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

### Debug Link
~~___Enter your debug link from `/crates debug`. Not providing this may result in the issue being closed without warning. If you are unable to use this command please provide your Bukkit version, a list of plugins and your config.yml for CratesPlus.___~~

Due to a change in the GitHub Gist API the debug command currently doesn't work. Please can you upload your `config.yml` and provide your Bukkit version. If possible a plugin list and providing your `data.yml` is also appreciated and may be requested if needed.

### Link/paste of stack trace/error (if any)

    You can also simply just use code formatting in markdown!
___We need all of the stack trace! Do not cut off parts of it.___

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

Hi 

I've attached the screen dump of /crate debug run and plugin list, along with config.yml and data.yml.

I appear to be having a similar issue to 2 other posts, the crate not using all of the winning items.  The config contains 20 items for each crate with a 5% assigned to each - 5x20 = 100% - check.

I checked the entire server bootup dump and no issues with CratesPlus loading were listed - but if you need entire dump, I can send that also. 

Sorry to bother you but can you please tell me what I may be doing wrong?

Thank you.

Hector

**Comment by ConnorLinfoot** [comment]
Which crate is having the issue?

**Comment by ConnorLinfoot** [comment]
If your issue is the `Vote` crate this is because item 14 is invalid. `BOTTLE` is not a valid material.

**Comment by hecbridge1** [comment]
It's all three crates that only show 13 items - sorry about that, the vote crate originally had EXPERIENCE_BOTTLE like the other 2 for item 14 but I was playing around to see if I was doing something wrong,  Thx

**Comment by ConnorLinfoot** [comment]
What Bukkit/Spigot version are you using?

**Comment by ConnorLinfoot** [comment]
Ahh 1.8, `EXPERIENCE_BOTTLE` is invalid iirc it's `EXP_BOTTLE` in 1.8
