### ISSUE TITLE
Key not working on 1.13.1

### ISSUE THREAD

**Issue by TheNickoos** [ConnorLinfoot/CratesPlus#575]
## Debug Info

[config.zip](https://github.com/ConnorLinfoot/CratesPlus/files/2387749/config.zip)
Using spigot-1.13.1-R0.1

### Link/paste of stack trace/error (if any)

No error in log.

### Actions to reproduce (if known):
![sans titre](https://user-images.githubusercontent.com/123190/45612415-2af49200-ba63-11e8-8c81-6404235e23fc.png)

**Comment by ConnorLinfoot** [comment]
This issue should now be fixed in version 4.5.1 :)
