### ISSUE TITLE
Picking Colors from the color gui doesnt do anything and name change crashes me

### ISSUE THREAD

**Issue by Scorpionvssub** [ConnorLinfoot/CratesPlus#576]
Default template isnt required.

Config = Default Configuration(as per plugin)
Version: Latest as per spigot(4.5.1)

What i expect is it to close and alter the name when i alter it.

Another error is:

17.09 22:10:07 [Server] [Informatie] CONSOLE issued server command: /list
17.09 22:10:07 [Server] [Informatie] default: Scorpionvssub
17.09 22:10:11 [Disconnect] User Scorpionvssub has disconnected, reason: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.ClassCastException: net.minecraft.server.v1_13_R2.BlockPosition cannot be cast to [Ljava.lang.String;

This occurs when hitting the name edittor nametag option which always crashes me or anyone that attempts it thus my request is to somehow do it by command?
/crate set <crate name> <new name Possibly with color?>

The error also causes my whole mc to crash/close

**Comment by ConnorLinfoot** [comment]
If I remember correctly there is a `/crate rename` command :) But I will look at adding support for sign editing in 1.13 if its an easy task.

**Comment by ConnorLinfoot** [comment]
Fixed in 5.0 snapshot 7.
