### ISSUE TITLE
Color code should be allowed for key name

### ISSUE THREAD

**Issue by HotelMakar** [ConnorLinfoot/CratesPlus#577]
**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

I think this is not a bug but a feature so i think color codes should be allowed on key name and maybe add key name lores and allow color code for lores aswell

**Comment by ConnorLinfoot** [comment]
What version are you running? And can you share your config, please?

**Comment by HotelMakar** [comment]
1.8.8 spigot
and
https://pastebin.com/4W7vEXnU

**Comment by ConnorLinfoot** [comment]
Ahh okay, I see, so it currently doesn't support color codes for the key name (I must've missed that) but it does with the lore. I  have tested using the color symbol `§` and it works (instead of `&`) so for now I'd recommend using that. And support for the other method will be added in an update 😃
