### ISSUE TITLE
Players Can Take Items From Chest!!

### ISSUE THREAD

**Issue by cooldogkidz** [ConnorLinfoot/CratesPlus#58]
Players can just right click the chest and take the items out! help!

**Comment by ConnorLinfoot** [comment]
What version of Spigot are you running?

**Comment by cooldogkidz** [comment]
Im using Bukkit

**Comment by ConnorLinfoot** [comment]
@cooldogkidz That will be your problem. CratesPlus is not compatible with CraftBukkit as stated.
