### ISSUE TITLE
Placeholder %prize% will be replaced with null

### ISSUE THREAD

**Issue by rona-tombo** [ConnorLinfoot/CratesPlus#580]
I am using the latest version of CratesPlus, but when I got a prize I was told that I got null and I did not know what I got.
Looking at messages.yml, I noticed that it was null when the part written as %prize% was displayed.
This seems to occur when the item name is a default name that does not exist.
I'm using Spigot 1.12.2

**Comment by ConnorLinfoot** [comment]
Ahh, so this is due to there being no name unless one is set as Bukkit doesn't even have a method to get a "Vanilla" name as it's displayed to the client. I can make a change to use the material name instead but for now I'd recommend just giving the items a name if you want to use `%prize%`
