### ISSUE TITLE
CratesPlus Issue - MilaDog#8249

### ISSUE THREAD

**Issue by MilaDog** [ConnorLinfoot/CratesPlus#587]
Hey! When running cratesplus and typing in the command, the chat says that there is an internal error and console gives the following: 
![image](https://user-images.githubusercontent.com/40185370/47615046-7a8e9a80-dab2-11e8-8b29-b00fdd6aa123.png)

Ive tried several versions, all giving thew same, but when there is nothing in the the config files etc, everything works well. yet the config.yml is valid.

Any ideas on this issue?

**Comment by ConnorLinfoot** [comment]
https://i.imgsha.re/Y5mb4Z.png 

Something is either disabling the plugin, or it's having an exception higher up in the console.

**Comment by MilaDog** [comment]
Also gives this error: 
![image](https://user-images.githubusercontent.com/40185370/47615731-a19d9a00-dabb-11e8-9ff7-4515cdeda1e7.png)
