### ISSUE TITLE
More than one item per key

### ISSUE THREAD

**Issue by fatmanjumprope** [ConnorLinfoot/CratesPlus#59]
While the roulette is spinning after using a key users are able to continuously grab items from the chest until it stops if they start grabbing while it's still spinning. If they're fast enough they can sometimes get up to 10 items per key use. Is there a way to stop this or fix it?

**Comment by jon4397** [comment]
I don't have this issue. I am unable to move any of the objects. Has it been fixed?

**Comment by ConnorLinfoot** [comment]
What version of Spigot are you using?

**Comment by jon4397** [comment]
I used 1.8.3 and that never happened to me. The items cannot be moved either from my own inventory or from the chest GUI.

**Comment by jon4397** [comment]
I found a way to take the item out, however you cannot use the item. Nobody can see you holding it, and if you hit someone with an enchanted sword you took out, it only deals a fist's strike. If you try to put on the armor, it disappears. Same if you try to place a block, or eat an item. The way to get the item is to left click it to see the options, then holding shift, you can click one and press "esc" really fast. This moves the item to your inventory, and closes the GUI. However, the object is invisible to others and unuseable, as well as unmoveable without it disappearing. I wouldn't consider this a problem at all. You can't even drop them with Q.

**Comment by ConnorLinfoot** [comment]
@jon4397 that's just a client side glitch. Nothing can really be done with that :P

**Comment by jon4397** [comment]
Right. As I said, not really a problem. :P
