### ISSUE TITLE
CratesPlus Players can steal

### ISSUE THREAD

**Issue by CodingWithAdin** [ConnorLinfoot/CratesPlus#598]
Hi so I have an issue where my players can take items from preview and when they are opening crates

I have these plugins: https://imgur.com/a/K0Gu8Qr

Also when players steal items, they right or left click the stolen itm disappears.
I would want to know how to make so they cant even steal them

**Comment by seema84** [comment]
yes player can take any items when they are opening crates (version 1.13.2)

**Comment by CodingWithAdin** [comment]
Im in 1.12.2

**Comment by SiuanSong** [comment]
It's just a cosmetic bug.  They won't actually have the item.

**Comment by CodingWithAdin** [comment]
How to fix that
Im on 1.12.2

**Comment by caputoortega** [comment]
I'm having the same issue on 1.13.2 using CratesPlug 4.5.1

**Comment by SiuanSong** [comment]
Is this happening when players just left click the chest to view the Possible Wins, or when they are using keys and the roulette is running?  I'm using the NoGUI function and cannot reproduce this.

**Comment by SiuanSong** [comment]
This is a really old cosmetic bug with this plugin that was fixed, idk when.  
Here's a video to show what I mean.  I'm not sure if you guys are experiencing the same glitch or not.
https://youtu.be/no-XOX1_jgI

**Comment by CodingWithAdin** [comment]
Hi Guys,
I just realized that when players DO steal on the first inventory update it disappears.

**Comment by seema84** [comment]
so you think its a vanilla issue?

**Comment by CodingWithAdin** [comment]
> so you think its a vanilla issue?

Yes, sorry for the late reply
