### ISSUE TITLE
Plugin ERROR

### ISSUE THREAD

**Issue by iTrickShotz** [ConnorLinfoot/CratesPlus#60]
the plugin errors out while it attempting to enable it.

![latest](https://cloud.githubusercontent.com/assets/16123122/11540672/0bbd1d0a-9926-11e5-8ef0-482d1af31bf6.png)

**Comment by iTrickShotz** [comment]
[latestlog.pdf](https://github.com/ConnorLinfoot/CratesPlus/files/50060/latestlog.pdf)

**Comment by ConnorLinfoot** [comment]
Not exactly any sort of helpful report with a broken "pdf" for errors.
