### ISSUE TITLE
2 problems, and 2 suggestions

### ISSUE THREAD

**Issue by jon4397** [ConnorLinfoot/CratesPlus#61]
I found this plugin to be faultless barring a couple problems. When someone opens a chest, everyone hears it regardless of the distance away. Also, when I put an enchanted book in the chest, when it comes out as a reward, there is no enchantment on it.
My suggestions are that #1 there needs to be a percentage adjustable through config. If it was 100% by default, but changeable in config, that would be good. #2 is that the GUI be changed from a single-chest's to a double-chest. I don't know how hard that would be to do, but it would make things easier to organize.

**Comment by jon4397** [comment]
I found this plugin to be faultless barring a couple problems. When someone opens a chest, everyone hears it regardless of the distance away. Also, when I put an enchanted book in the chest, when it comes out as a reward, there is no enchantment on it. 
My suggestions are that #1 there needs to be a percentage adjustable through config. If it was 100% by default, but changeable in config, that would be good. #2 is that the GUI be changed from a single-chest's to a double-chest. I don't know how hard that would be to do, but it would make things easier to organize.

**Comment by ConnorLinfoot** [comment]
What GUI are you referring too?

**Comment by jon4397** [comment]
I am referring to the GUI that you place items in that are obtainable by using the crate key on a crate. It shows a double chest GUI, but when you place items in it and left click to check the chances, it only shows a single chest GUI.

**Comment by ConnorLinfoot** [comment]
Pretty sure both the above are done. Closing issue.
