### ISSUE TITLE
Hologram stuck, cant delete it!

### ISSUE THREAD

**Issue by gustavwww** [ConnorLinfoot/CratesPlus#62]
Hey!
I had a crate, vote crate, i did put myself into gamemode 0, end deop. And i, by misstake placed out an crate. The crate went gone, but the hologram still there, and cant get away!
Please help!
Thank you!

**Comment by jon4397** [comment]
Try 
/kill @e[type=!Player,r=2]
And see if that gets rid of it. You will have to stand in the hologram.

**Comment by gustavwww** [comment]
I figured it out..
/killall named 5
and stand beside the hologram
