### ISSUE TITLE
reporting test on 1.14.1 using 

### ISSUE THREAD

**Issue by comonier** [ConnorLinfoot/CratesPlus#636]
test on spigot 1.14.1
[08:28:02] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-4f661b2-d06991d (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)

[Sun, 19. May 2019 09:19:13 EDT WARN] Plugin CratesPlus v5.0-SNAPSHOT-7 does not specify an api-version.
[Sun, 19. May 2019 09:19:13 EDT INFO] [CratesPlus] Enabling CratesPlus v5.0-SNAPSHOT-7
[Sun, 19. May 2019 09:19:13 EDT WARN] [CratesPlus] CratesPlus has not yet been officially tested with Bukkit 1.14.1 but should still work
[Sun, 19. May 2019 09:19:13 EDT INFO] CratesPlus Version 5.0-SNAPSHOT-7
[Sun, 19. May 2019 09:19:13 EDT INFO] Warning: You are running a snapshot build of CratesPlus
[Sun, 19. May 2019 09:19:13 EDT INFO] It is advised that you do NOT run this on a production server!
[Sun, 19. May 2019 09:19:13 EDT INFO] Unable to find compatible Hologram plugin, holograms will not work!
[Sun, 19. May 2019 09:19:13 EDT INFO] [PlugMan] CratesPlus has been loaded and enabled.
[Sun, 19. May 2019 09:19:13 EDT INFO] WARNING: Snapshot updates are not recommended on production servers
[Sun, 19. May 2019 09:19:13 EDT INFO] Checking for updates via snapshot branch...
[Sun, 19. May 2019 09:19:13 EDT INFO] [CratesPlus] No update was found, you are running the latest version. Will check again later.
[Sun, 19. May 2019 09:19:16 EDT ERROR] Could not pass event InventoryClickEvent to CratesPlus v5.0-SNAPSHOT-7

**Comment by comonier** [comment]
and still spamming the msg:
[Sun, 19. May 2019 09:19:16 EDT ERROR] Could not pass event InventoryClickEvent to CratesPlus v5.0-SNAPSHOT-7

**Comment by successed** [comment]
yeah this not a work, we need update this..

**Comment by CeIebrimbor** [comment]
Confirmed. Plugin seems to function, but InventoryClickEvent error spams console.

Inventory#getTitle() no longer exists
Use the InventoryView

**Comment by ConnorLinfoot** [comment]
Of course they removed one of the most use methods. Will look into adding 1.14 support as soon as possible.

**Comment by ConnorLinfoot** [comment]
Issues caused by 1.14 overall weren't too much work, rolled a build that should support 1.14. Let me know if any further issues appear by creating a new issue :)
