### ISSUE TITLE
The winnings don't show up when i click on them.

### ISSUE THREAD

**Issue by Joseph0430** [ConnorLinfoot/CratesPlus#638]
Everything else is fine, the chest opens with the crate key, but the only thing that it doesn't do is that it doesn't show the winnings when i click on them. Worldguard is in place. What do i have to do with worldguard to fix this?

**Comment by ConnorLinfoot** [comment]
https://github.com/ConnorLinfoot/CratesPlus/wiki/Debugging-Issues#players-cant-open-crates
