### ISSUE TITLE
Spamable Rewards

### ISSUE THREAD

**Issue by AcesGamingUK** [ConnorLinfoot/CratesPlus#64]
if the gui is turned of i've found my players can rapidly spam the same reward until their keys have ran out, i was wondering if you could add a cooldown option for those who wish to have the gui disabled, 

also i was wondering if you could add "amounts" to keys (crate key {name} [key] [amount])

**Comment by ConnorLinfoot** [comment]
Now added a cooldown in snapshot 20.
