### ISSUE TITLE
Were can i download CratePlus for 1.14.2 ?

### ISSUE THREAD

**Issue by comonier** [ConnorLinfoot/CratesPlus#641]
Any jekings link to test dev test build ? 

wtf 4.5.2 ? the last one was CratesPlus-5.0-SNAPSHOT-7.jar downgrade it ?

CratesPlus V4.5.2 - 1.14 - 1.14.2 Support
Feature: Support for Bukkit/Spigot 1.14 - 1.14.2.
NOTE: I haven't had the chance to fully test this update, so please report bugs over on the GitHub if anything appears for any versions. https://github.com/ConnorLinfoot/CratesPlus/issues

**Comment by ConnorLinfoot** [comment]
The snapshot builds are for development and testing purposes and shouldn't be used on production servers. But there is a snapshot 8 that released shortly after 4.5.2.
