### ISSUE TITLE
Commands get deleted

### ISSUE THREAD

**Issue by toxicone7** [ConnorLinfoot/CratesPlus#66]
Hello,
I don't know if this is a bug but it might be..
When I add an item and then gets run by console it works.. I have no clue if I configured it in a wrong way.. As soon as I restart the server or stop it, the config turns it into that http://prntscr.com/9bejld.
When it used to be like that http://prntscr.com/9bend7.
Hope you'll help me!

Regards

**Comment by ConnorLinfoot** [comment]
Anything in console? Version of Spigot? Actual config files? How are you adding the item?

Please answer those and I'll see if I can tell what the issue is.
