### ISSUE TITLE
Players can grab items out of the inventory..

### ISSUE THREAD

**Issue by GhostGuy283** [ConnorLinfoot/CratesPlus#68]
When a player is not OP the player can grab all stuff.
Video:
http://galacticcraft.ga/play/2015-12-10%2019-49-16.mp4

**Comment by GhostGuy283** [comment]
When i'm op i can't take stuff out of the chest.

**Comment by ConnorLinfoot** [comment]
What version of Spigot are you running and are you getting any errors in console?

**Comment by GhostGuy283** [comment]
git-Spigot-f928e7a-e91aed8 (MC: 1.8.7) (Implementing API version 1.8.7-R0.1-SNAPSHOT)
i don't get errors.

**Comment by GhostGuy283** [comment]
holograms aren't working either

**Comment by ConnorLinfoot** [comment]
What plugins do you have installed?

**Comment by GhostGuy283** [comment]
![2015-12-15_07 18 49](https://cloud.githubusercontent.com/assets/12268965/11803535/2fd34932-a2fc-11e5-97f8-718a0c3c54e1.png)

**Comment by ConnorLinfoot** [comment]
There's a lot of plugins and I can't really go through every single one to find which could be causing the issue. Try removing plugins and adding them back 1 by 1 till you find what's causing the issue.

**Comment by samgogogo** [comment]
Same problem here. Il send you my plugin list and we can compare:
![image](https://cloud.githubusercontent.com/assets/16963958/12686941/bbadfb28-c6c4-11e5-92d5-7bf58f1af4f4.png)
