### ISSUE TITLE
Money command in crate

### ISSUE THREAD

**Issue by DovaPrison** [ConnorLinfoot/CratesPlus#69]
Hey

I am fairly new to your plugin, and I'm trying to set it up for my server. 
While doing this I ran in to an issue. I was trying to add a chance of getting money. 
      '3':
        Type: COMMAND
        Item Type: PAPER
        Percentage: 100
        Commands:
        - 'eco give %name% 1000'
        Item Data: 0
        Name: Test
        Amount: 1
        Enchantments: []
        Lore: []
This is what I have so far. But I get the paper item in my inventory, but I DON'T want this.
I was wondering if you could help me out.
Thanks in advance.

Best regards
Matthis ~DovaPrison networkmanager.

**Comment by ConnorLinfoot** [comment]
Does it still run the command, I think i may know why it's giving the item and that should be fixed in the next update (Probably 4.0) but just wanting to check the command does still run for you?

**Comment by ConnorLinfoot** [comment]
This issue no longer occurs in 4.0 (Snapshot 1)+
