### ISSUE TITLE
fix it. and please update your plugin.

### ISSUE THREAD

**Issue by xXSeikoStormXx** [ConnorLinfoot/CratesPlus#701]
18.10 23:46:31 [Server] Server thread/ERROR Could not pass event PlayerInteractEvent to CratesPlus v4.5.2
18.10 23:46:31 [Server] INFO org.bukkit.event.EventException: null
18.10 23:46:31 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[custom.jar:git-Spigot-9de398a-9c887d4]
18.10 23:46:31 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[custom.jar:git-Spigot-9de398a-9c887d4]
18.10 23:46:31 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[custom.jar:git-Spigot-9de398a-9c887d4]
18.10 23:46:31 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[custom.jar:git-Spigot-9de398a-9c887d4]
18.10 23:46:31 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:429) ~[custom.jar:git-Spigot-9de398a-9c887d4]
18.10 23:46:31 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:396) ~[custom.jar:git-Spigot-9de398a-9c887d4]
18.10 23:46:31 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:136) ~[custom.jar:git-Spigot-9de398a-9c887d4]
18.10 23:46:31 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1185) ~[custom.jar:git-Spigot-9de398a-9c887d4]
18.10 23:46:31 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[custom.jar:git-Spigot-9de398a-9c887d4]
18.10 23:46:31 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[custom.jar:git-Spigot-9de398a-9c887d4]
18.10 23:46:31 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[custom.jar:git-Spigot-9de398a-9c887d4]
18.10 23:46:31 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [custom.jar:git-Spigot-9de398a-9c887d4]
18.10 23:46:31 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [custom.jar:git-Spigot-9de398a-9c887d4]
18.10 23:46:31 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [custom.jar:git-Spigot-9de398a-9c887d4]
18.10 23:46:31 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [custom.jar:git-Spigot-9de398a-9c887d4]
18.10 23:46:31 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:910) [custom.jar:git-Spigot-9de398a-9c887d4]
18.10 23:46:31 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:903) [custom.jar:git-Spigot-9de398a-9c887d4]
18.10 23:46:31 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [custom.jar:git-Spigot-9de398a-9c887d4]
18.10 23:46:31 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:887) [custom.jar:git-Spigot-9de398a-9c887d4]
18.10 23:46:31 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:820) [custom.jar:git-Spigot-9de398a-9c887d4]
18.10 23:46:31 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
18.10 23:46:31 [Server] INFO Caused by: java.lang.NullPointerException
18.10 23:46:31 [Server] INFO at plus.crates.Listeners.PlayerInteract.onPlayerInteract(PlayerInteract.java:45) ~[?:?]
18.10 23:46:31 [Server] INFO at sun.reflect.GeneratedMethodAccessor97.invoke(Unknown Source) ~[?:?]
18.10 23:46:31 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
18.10 23:46:31 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
18.10 23:46:31 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[custom.jar:git-Spigot-9de398a-9c887d4]

**Comment by Cylizion** [comment]
Your fix is at #678.
