### ISSUE TITLE
Getting the "Chances" item together too.

### ISSUE THREAD

**Issue by Dragzie** [ConnorLinfoot/CratesPlus#71]
I don't know what to write in the title, but this should make you understand it more
When I open the crate I will get a random item with their names, that's fine but with the chances as the lore together with the prize it doesn't look like a good looking item anymore.

![2015-12-14_14 17 07](https://cloud.githubusercontent.com/assets/14952378/11774180/7bf93d60-a26d-11e5-8dbd-e5828094993c.png)

**Comment by ConnorLinfoot** [comment]
This issue no longer occurs in 4.0 (Snapshot 1)+
