### ISSUE TITLE
Can't color code or use non-letter characters

### ISSUE THREAD

**Issue by Syrkulous** [ConnorLinfoot/CratesPlus#716]
I suggest adding in color-coding and the ability to create names
Such As:
-Creating rainbow crate titles
-Ability to fully customize crate title "-=[Legendary]=-" instead of Legendary

**Comment by Cylizion** [comment]
Did you try the crate naming via the in-game command `/crate create -=[Legendary]=-`? I know that spaces are not supported, which is understandable to an extent.

I attempted the command I mentioned above. It DID work. After reloading my server, as my holograms were only working on one crate, it DID in fact work properly.
![CratesPlus #716 - Chat Output](https://user-images.githubusercontent.com/57037696/69811605-71439600-11bc-11ea-88e3-2abf0d9b1b8b.png)
![CratesPlus #716 - Crate/Hologram](https://user-images.githubusercontent.com/57037696/69811606-71439600-11bc-11ea-9b41-260c88564b6c.png)

**Comment by Syrkulous** [comment]
I figured out how to add that.

Current Issues:
- Can't custom color
- Can't add CSGO Opener 

Some suggested on that CSGO Opener page to implement it as one of the openers of the plugins

**Comment by Cylizion** [comment]
Custom color patterns are not supported for a variety of reasons. Personally, it'd look unprofessional to have it like that; however, that's just me. Good luck!
(I'd advise you close this ticket, as the problem was in fact solved).

**Comment by Syrkulous** [comment]
It hasn't been resolved--

The CSGO Opener is not working while many are still interested in it.
Unless you're going to ignore a great idea, then fine I'll close it.

**Comment by Cylizion** [comment]
The case is about color coding and special characters. You said you figured it out. I'd recommend making a new case if you can't figure out how to use the CS:GO Opener.
