### ISSUE TITLE
CratesPlus Prefix. 

### ISSUE THREAD

**Issue by xAtomicWastex** [ConnorLinfoot/CratesPlus#72]
So, I downloaded C+ 1 day ago before something happened. It worked perfectly the day I had it. But today (1 day later) it broke. The commands weren't working, nothing was. I broke the chest, the chest was gone but the prefix is still here! So I uninstalled it, installed it and then created the chests. Still there, not gone. Deleted the chests then reloaded the plugin still here... Help me please!
![ec crates bug](https://cloud.githubusercontent.com/assets/16289429/11781562/cbda2aac-a27b-11e5-8231-5195e23922b9.png)

**Comment by ConnorLinfoot** [comment]
There is information on the Spigot thread on fixing holograms; https://www.spigotmc.org/resources/cratesplus-custom-crates-free.5018/

There was most likely an error in your config or something that caused the issue for it to stop working. That's usually the case.

**Comment by xAtomicWastex** [comment]
I found how to remove the prefixes, type:   /killall named 5     <----  Exactly like that!
