### ISSUE TITLE
Could not pass event InventoryClickEvent to CratesPlus v4.5.1

### ISSUE THREAD

**Issue by liscuate** [ConnorLinfoot/CratesPlus#729]
Spigot/Bukkit version:
**Spigot version 1.14.4**

Plugin version:
**CratesPlus 4.5.1**

I keep getting the error Could not pass event InventoryClickEvent to CratesPlus v4.5.1 in my console and it might be the reason why my server keeps crashing.

**Comment by thinkverse** [comment]
Check out #678 it has an unofficial fix for it.

**Comment by liscuate** [comment]
I will check that out, thanks.
