### ISSUE TITLE
No permission to use this crate

### ISSUE THREAD

**Issue by ZevBellringer** [ConnorLinfoot/CratesPlus#748]
The crates work when you are Op.

I added  the permission  cratesplus.crate.* to the default group, No one who isnt OP could use keys = "You do not have permission"

So as a test, i added an individual perm to the group the user was testing it was in   cratesplus.crate.vote.
still wont let him use it

so i have him personally the perm for that crate cratesplus.crate.vote
still wont let him use it

Reloaded the plugin
still wont let him use it.

I can use the crates withj OP.

So now im beat, I know Luckperms works fine, it propagates perms for oherplugins fine.

So id appreciate a clue on how you actually get it t owork for people who arent OP.

Ive spent over an hour messing round with this, its about to go into the discard folder...

MC 1.15 Crates pls 4.2  luckperms 

Config minus the stuffon the crate contents

Config Version: 6
Update Checks: true
Update Branch: spigot
Metrics: true
Default Opener: BasicGUI
Default Cooldown: 5
Crate Protection: false
Disable Key Swapping: false
Default Hologram Text:
- '%crate%'
- Right-Click to Open!
- Left-Click to Preview!
Crates:
  God:
    Key:
      Item: TRIPWIRE_HOOK
      Name: '%type% Crate Key'
      Enchanted: true
    Knockback: 0.0
    Broadcast: false
    Firework: false
    Preview: true
    Block: CHEST
    Color: WHITE
    Winnings:

**Comment by ItzMystic** [comment]
Do you  have a worldguard region within the crates?
If you do 
Flag the region with this:
**/region flag {region} Interact allow**

**Comment by mehdibouchrit** [comment]
I had the same issue and the solutions was:
- change the crate bloc, if you use some op blocs like commands bloc or other blocs, players will not be able to interact with the bloc
- Make sure that your wg regions allow use of blocs
/rg flag regionname use allow
/rg flag regionname Interact allow
