### ISSUE TITLE
4.0 snapshot No collored names

### ISSUE THREAD

**Issue by DovaPrison** [ConnorLinfoot/CratesPlus#75]
Hey

Me again. Thanks for the help last time!
But I can't figer out how to(if even possible) give crates collors.
Thanks in advance

Best regards
Matthis ~DovaNetworkmanager

**Comment by DovaPrison** [comment]
Nevermind already fixed it!

**Comment by DovaPrison** [comment]
I would actually like a bit of help on enchants on items
And also can I use enchants over the normal/vanilla threshold?

**Comment by RubixCubeGhast** [comment]
How do you do the colour?

**Comment by DovaPrison** [comment]
SupplyCrate:
    Winnings:
      '1':
        Type: ITEM
        Item Type: IRON_SWORD
        Item Data: 0
        Percentage: 0
        Name: '&6&lExample Sword'
        Amount: 1
    Key:
      Item: TRIPWIRE_HOOK
      Name: '%type% Crate Key'
      Enchanted: true
    Knockback: 0.0
    Broadcast: false
    Firework: false
    Color: RED


You edit the color on the last row. It needs to be all caps!
I don't know all the collor that are supported tho.

**Comment by DovaPrison** [comment]
I found a way to do the enchants. You have to make it as a command.
This is how I did it: 
      '4':
        Type: COMMAND
        Item Type: DIAMOND_PICKAXE
        Item Data: 0
        Name: '&4[Vote] &rPickAxe'
        Amount: 1
        Commands:
        - give BallzOfCheeze 278 1 efficiency:15 unbreaking:20 fortune:1 name:&4[Vote]_&rPickaxe

**Comment by ConnorLinfoot** [comment]
Colors and Enchantment's currently use the vanilla naming scheme's; 

https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/ChatColor.html
