### ISSUE TITLE
This feature is currently disabled!!

### ISSUE THREAD

**Issue by Nanadog** [ConnorLinfoot/CratesPlus#753]
**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

### Debug Info

Config Version: 7
Update Checks: true
Update Branch: release
Metrics: true
Default Opener: BasicGUI
Default Cooldown: 5
Crate Protection: true
Disable Key Swapping: true
Default Hologram Text:
- '%crate%'
- Right-Click to Open!
- Left-Click to Preview!
Storage Type: FLAT
MySQL Host: localhost
MySQL User: username
MySQL Pass: password
MySQL Database: database
Prefix: '&7[&bCratesPlus&7]'
Chance Message Gap: true
Crates:
  Default:
    Winnings:
      '1':
        Type: ITEM
        Item Type: IRON_SWORD
        Item Data: 0
        Percentage: 0
        Name: '&6&lExample Sword'
        Amount: 1
    Key:
      Item: TRIPWIRE_HOOK
      Name: '%type% Crate Key'
      Enchanted: true
    Knockback: 0.0
    Broadcast: false
    Firework: false
    Preview: true
    Block: CHEST
    Color: WHITE
    Type: KeyCrate
  Vip:
    Winnings:
      '1':
        Type: ITEM
        Item Type: IRON_SWORD
        Item Data: 0
        Percentage: 0
        Name: '&6&lExample Sword'
        Amount: 1
    Key:
      Item: TRIPWIRE_HOOK
      Name: '%type% Crate Key'
      Enchanted: true
    Knockback: 0.0
    Broadcast: false
    Firework: false
    Preview: true
    Block: CHEST
    Color: DARK_GREEN
    Type: KeyCrate
  Vip+:
    Winnings:
      '1':
        Type: ITEM
        Item Type: IRON_SWORD
        Item Data: 0
        Percentage: 0
        Name: '&6&lExample Sword'
        Amount: 1
    Key:
      Item: TRIPWIRE_HOOK
      Name: '%type% Crate Key'
      Enchanted: true
    Knockback: 0.0
    Broadcast: false
    Firework: false
    Preview: true
    Block: CHEST
    Color: DARK_GREEN
    Type: KeyCrate
  Mvp:
    Winnings:
      '1':
        Type: ITEM
        Item Type: IRON_SWORD
        Item Data: 0
        Percentage: 0
        Name: '&6&lExample Sword'
        Amount: 1
    Key:
      Item: TRIPWIRE_HOOK
      Name: '%type% Crate Key'
      Enchanted: true
    Knockback: 0.0
    Broadcast: false
    Firework: false
    Preview: true
    Block: CHEST
    Color: DARK_AQUA
    Type: KeyCrate
  mvp+:
    Winnings:
      '1':
        Type: ITEM
        Item Type: IRON_SWORD
        Item Data: 0
        Percentage: 0
        Name: '&6&lExample Sword'
        Amount: 1
    Key:
      Item: TRIPWIRE_HOOK
      Name: '%type% Crate Key'
      Enchanted: true
    Knockback: 0.0
    Broadcast: false
    Firework: false
    Preview: true
    Block: CHEST
    Color: DARK_BLUE
    Type: KeyCrate
  God:
    Winnings:
      '1':
        Type: ITEM
        Item Type: IRON_SWORD
        Item Data: 0
        Percentage: 0
        Name: '&6&lExample Sword'
        Amount: 1
    Key:
      Item: TRIPWIRE_HOOK
      Name: '%type% Crate Key'
      Enchanted: true
    Knockback: 0.0
    Broadcast: false
    Firework: false
    Preview: true
    Block: CHEST
    Color: YELLOW
    Type: KeyCrate
  Legand:
    Winnings:
      '1':
        Type: ITEM
        Item Type: IRON_SWORD
        Item Data: 0
        Percentage: 0
        Name: '&6&lExample Sword'
        Amount: 1
    Key:
      Item: TRIPWIRE_HOOK
      Name: '%type% Crate Key'
      Enchanted: true
    Knockback: 0.0
    Broadcast: false
    Firework: false
    Preview: true
    Block: CHEST
    Color: GOLD
    Type: KeyCrate

### Actions to reproduce (if known):
It always says that when i try to edit whats inside the crate

**Comment by ConnorLinfoot** [comment]
Intended in 5.0 snapshot, don't use on production servers.
