### ISSUE TITLE
People can take stuff out while animation is happening!

### ISSUE THREAD

**Issue by Riskz** [ConnorLinfoot/CratesPlus#77]
I've read through other questions and stuff and the only reason this is happening is because they're on craftbukkit and thats the only answer. As im running spigot i have no clue why its not working and why people can just take stuff while the animation is rolling :/

**Comment by ConnorLinfoot** [comment]
The issue can also be related to other plugins interfering with how inventories are handled. Try removing other plugins and see if the issue persists.

Also, what version of Spigot are you using?
