### ISSUE TITLE
ERROR Could not pass event PlayerInteractEvent to CratesPlus v4.5.2 11.07

### ISSUE THREAD

**Issue by Tuurvdv** [ConnorLinfoot/CratesPlus#774]
I'm trying to add keys by voting and i get this error when i vote on the server.

RROR Could not pass event PlayerInteractEvent to CratesPlus v4.5.2
11.07 21:35:52 [Server] INFO java.lang.NullPointerException: null
11.07 21:35:52 [Server] INFO at plus.crates.Listeners.PlayerInteract.onPlayerInteract(PlayerInteract.java:45) ~[?:?]
11.07 21:35:52 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor4670.execute(Unknown Source) ~[?:?]
11.07 21:35:52 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-87]
11.07 21:35:52 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-87]
11.07 21:35:52 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-87]
11.07 21:35:52 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-87]
11.07 21:35:52 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:497) ~[patched_1.16.1.jar:git-Paper-87]
11.07 21:35:52 [Server] INFO at net.minecraft.server.v1_16_R1.PlayerInteractManager.a(PlayerInteractManager.java:459) ~[patched_1.16.1.jar:git-Paper-87]
11.07 21:35:52 [Server] INFO at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1449) ~[patched_1.16.1.jar:git-Paper-87]
11.07 21:35:52 [Server] INFO at net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.1.jar:git-Paper-87]
11.07 21:35:52 [Server] INFO at net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.1.jar:git-Paper-87]
11.07 21:35:52 [Server] INFO at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-87]
11.07 21:35:52 [Server] INFO at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-87]
11.07 21:35:52 [Server] INFO at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-87]
11.07 21:35:52 [Server] INFO at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-87]
11.07 21:35:52 [Server] INFO at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-87]
11.07 21:35:52 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-87]
11.07 21:35:52 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-87]
11.07 21:35:52 [Server] INFO at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-87]
11.07 21:35:52 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.1.jar:git-Paper-87]
11.07 21:35:52 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Paper-87]
11.07 21:35:52 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-87]
11.07 21:35:52 [Server] INFO at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by ItzCreeperBoy27** [comment]
http://www.mediafire.com/file/u8o4pnrwknf6547/Crates.jar/file heres a working cratesplus that fixes that error

**Comment by ConnorLinfoot** [comment]
Fixed in upcoming update #793
