### ISSUE TITLE
What is used for Enchanted golden apples?

### ISSUE THREAD

**Issue by P4ZLE** [ConnorLinfoot/CratesPlus#787]
Hello, I seem to be having an issue accessing Enchanted Golden Apples. They wont be available in the crate when I type:

      '9':
        Type: ITEM
        Item Type: ENCHANTED_GOLDEN_APPLE
        Item Data: 
        Percentage: 1
        Name: '&6&lSPECIAL GAPPLE'
        Amount: 1

I have tried replacing ENCHANTED_GOLDEN_APPLE with NOTCH_APPLE, OP_APPLE, 332:1, and other related names/terms but none seemed to work. Am I missing something or is the plugin missing an item?

**Comment by ConnorLinfoot** [comment]
You should use the material list to your Minecraft version, search `Spigot 1.8 Material` and change 1.8 to your version
