### ISSUE TITLE
You can tile items out of the preview screen

### ISSUE THREAD

**Issue by idklpl** [ConnorLinfoot/CratesPlus#789]
So basically when you shift click a item in the preview GUI you can take that item out but when you leave the world it disappears. My server is a acid island server base version is 1.12.2 Spigot. I am using the 4.5.2 version of the plugin. If someone could tell me how to fix this that would be great! Also if it makes a difference I think it might have to maybe do with viaversion but I don’t know for sure that would be my best guess.

**Comment by JackGamer180** [comment]
if they try to use the items, touch it, etc, it will disappear too.

**Comment by ConnorLinfoot** [comment]
Fixed in upcoming update #793
