### ISSUE TITLE
My holograms are NOT showing.

### ISSUE THREAD

**Issue by Cr0Phantom** [ConnorLinfoot/CratesPlus#79]
So i've been using CratesPlus for a few days.  I managed to mock up the config and it generated a new one. So I edited it to my will and everything is working fine. Then I broke one crate and replaced it but there was no hologram now. I tried reloading the plugin a few times but nothing helps..... Hologram text is set to default.

**Comment by ConnorLinfoot** [comment]
Will likely be another plugin (Usually something like WorldGuard) blocking entity spawn because the hologram's currently use entities.

Version 4.0 will not use entities anymore so that will be fully fixed for that version, for now you'd need to find which plugin is causing the issue.
