### ISSUE TITLE
Next 1.16 error

### ISSUE THREAD

**Issue by KamilM3004** [ConnorLinfoot/CratesPlus#792]
[22:44:07 ERROR]: Could not pass event PlayerInteractEvent to CratesPlus v4.5.2
java.lang.NullPointerException: null

**Comment by KamilM3004** [comment]
Its constantly spam my console

**Comment by Mrok71** [comment]
Jeeee i have too
[22:54:32 ERROR]: Could not pass event PlayerInteractEvent to CratesPlus v4.5.2
java.lang.NullPointerException: null

**Comment by Worive** [comment]
Maybe because the plugin is not made for 1.16 yet? :) Have fun reading the title next time... :+1:

**Comment by ConnorLinfoot** [comment]
Not sure what the error is as there is no stack trace, but it may be fixed in the next version hopefully soon as there will be a few fixes included
