### ISSUE TITLE
World Guard Problem

### ISSUE THREAD

**Issue by AndyJake01** [ConnorLinfoot/CratesPlus#80]
Dear CratePlus developer. I got this plus to add to my server and it worked amazing until I added it at spawn. I didn't know what the bug was at first but then I realize it was because they couldn't right click it while it was in a region. Do you know what I would have to allow to make this work? chest-access, use, interact, and build all didn't fix the problem when I set them to allow. Please help :)

**Comment by ConnorLinfoot** [comment]
You would have to look into World Guard/contact them. I personally have no experience with the plugin.

**Comment by GreenBaii** [comment]
I think its Chest Access
