### ISSUE TITLE
Possibility to save custom potions?

### ISSUE THREAD

**Issue by Collserra** [ConnorLinfoot/CratesPlus#81]
Currently, the plugin is great at storing custom enchantments, names, lore, etc including complete formatting support, which is great.

However, trying to save custom potions (using spigot's /potion command) (i.e. originally a splash potion of jumping, but transformed into a potion that has jump -6 (can't jump), slowness 7 (can't move) and blindness all for 15 seconds, but when saved into a crate the potion is reset to default, although the custom name, and lore are saved perfectly.

It'd be amazing if this was something you could change?

**Comment by ConnorLinfoot** [comment]
This won't be added in 4.0, it may be a future thing but with 1.9 it's a little more difficult.

**Comment by ConnorLinfoot** [comment]
Don't think this is going to be added, I may add NBT tag support one day but for now I'd say just use commands.
