### ISSUE TITLE
Spawners don't seem to work?

### ISSUE THREAD

**Issue by toxicv3nomz** [ConnorLinfoot/CratesPlus#82]
Hey guys been trying to figure this out on my own for a while now but with no luck, so i thought i would come here for help as this seems most appropriate. So basically i am setting up a factions server and crates plus is of course a very important part, but along with this spawners is another super important part of a factions server, so when i added the spawner into the crate at first it was just a pig spawner, so then i installed a plugin called silkspawners to see if that would make a difference but again nothing so i am kinda stumped here, i have no idea how to make this work, any information regarding this would be awesome thanks alot
Keanan

**Comment by ConnorLinfoot** [comment]
You would need to most likely use a spawner give command to add the item. However this isn't an issue with CratesPlus itself.
