### ISSUE TITLE
i can't add item on my box

### ISSUE THREAD

**Issue by Futiax** [ConnorLinfoot/CratesPlus#826]
![2021-02-21_18 41 37](https://user-images.githubusercontent.com/79416461/108633481-b9f80680-7474-11eb-8390-0cefd72d1c8b.png)
i can't add item on my box

**Comment by ConnorLinfoot** [comment]
This is intended with the development build.

**Comment by Futiax** [comment]
so how do I do myself to add objects?

> This is intended with the development build.

so how do I do myself to add objects?
