### ISSUE TITLE
Permissions? Cant open crates.

### ISSUE THREAD

**Issue by SilverShoopie** [ConnorLinfoot/CratesPlus#83]
I use Essentials Group Manager for my groups and ranks, and the default group cant open the crates even if they have the key.  No permission I have tried works either. The player has to be oped for them to be able to open the crate.  What do I do?

**Comment by ConnorLinfoot** [comment]
There is currently no permissions to handle opening crates. If you're having issues check your spawn protection and make sure no other plugins are disabling it.

**Comment by Reblxtemp3r** [comment]
I have the same issue. Checked everything you said to and it still doesn't work.
