### ISSUE TITLE
Chest not disappearing after use/hologram remains when manually removing chest

### ISSUE THREAD

**Issue by CelestOrion** [ConnorLinfoot/CratesPlus#84]
Hello, I am currently running Spigot 1.8.8, and the plugin works great, other than the fact that when a key is used, the chest remains in place, and you cannot get rid of it unless you enter a command to replace the block with air, but if that happens, the hologram remains in the air above it. Will there be an update to fix this?

**Comment by CelestOrion** [comment]
Update: I was reading up on earlier posts, found a workaround trick about killing the holograms that were left behind by using /kill @e[type=!Player,r=2] while standing in it. Just in case anybody else comes across this.

**Comment by ConnorLinfoot** [comment]
The chest isn't suppose to remove itself. The hologram stayed because you broke it with a command and not like normal.
