### ISSUE TITLE
Very bad problem: item disappearance

### ISSUE THREAD

**Issue by jon4397** [ConnorLinfoot/CratesPlus#87]
If a player right clicks on a crate while not holding that crate's key, it sets the player's hand to empty by deleting the item from their inventory. The class or method that updates the player's inventory based on a used key is apparently not run inside a proper if statement that would check their item in hand first.

**Comment by ConnorLinfoot** [comment]
Personally just tested this and also checked the source. Nothing in the CratesPlus plugin would create this issue.
