### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by SirCow** [ConnorLinfoot/CratesPlus#88]
When I change the colour of a crate in the config it disables the whole plugin! (Unless the colour is White)

Please fix?

**Comment by ConnorLinfoot** [comment]
Personally not had any issues with this, you're most likely using an invalid colour. Check here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/ChatColor.html

If you still have an issue please post with more information and a copy of your config.
