### ISSUE TITLE
Gui Bug?

### ISSUE THREAD

**Issue by Nicecardigan** [ConnorLinfoot/CratesPlus#90]
I saw another member talk about this on the spigot forums, and i followed your instructions to go here!

I loaded up your plugin, it works 100% but, anyone can preview the items and steal them for free?? this is a major bug, please can you reply, before i change this plugin to another :dash:

**Comment by ConnorLinfoot** [comment]
The issue is usually related to other plugins interfering with how inventories are handled. Try removing other plugins and see if the issue persists.

**Comment by GreenBaii** [comment]
I am changing because Of this

**Comment by ConnorLinfoot** [comment]
This issue has been fixed, it was caused by using CraftBukkit.

You can now use version 3.1.6 or above and it should be fixed; https://www.spigotmc.org/resources/cratesplus-custom-crates-1-8-1-9-free.5018/download?version=72888
