### ISSUE TITLE
What colors can I use for the chests?

### ISSUE THREAD

**Issue by butterontoast7** [ConnorLinfoot/CratesPlus#91]
Rare:
    Winnings:
      '1':
        Type: ITEM
        Item Type: IRON_SWORD
        Item Data: 0
        Percentage: 0
        Name: '&6&lExample Sword'
        Amount: 1
    Knockback: 0.0
    Broadcast: true
    Firework: true
    Color: BLACK

FOR the color i noticed it lets me use blue green and red and yellow. But if I put in any other colors it crashes the plugin and I cant use it. Am I limited to certain colors? if so what are they? or am I typing them in wrong?

**Comment by ConnorLinfoot** [comment]
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/ChatColor.html
