### ISSUE TITLE
Issue with COMMANDs instead of ITEMs

### ISSUE THREAD

**Issue by Jumpingjim01** [ConnorLinfoot/CratesPlus#93]
Hi
When using the command thing instead of items (so I can add lots more customization to items) if they win that thing they also get the item that shows in the GUI which I don't want them to get.

Example:

>       '6':
        Type: COMMAND
        Item Type: TRIPWIRE_HOOK
        Percentage: 5
        Commands:
        - 'crate key %name% voting'
        - 'crate key %name% voting'
        - 'crate key %name% voting'
        - 'crate key %name% voting'
        - 'crate key %name% voting'
        Name: '&b5x &cVote Keys'
        Item Data: 0
        Amount: 5
        Enchantments:
        - KNOCKBACK-1
        Lore: []

This gives them 5 working crate keys but also 5 tripwire hooks that I used to show what you get in the preview. It would be amazing if you could fix this. thanks
Also would be cool if you could give more than one key at a time :)
(My server is FAYZ.beastmc.com)

**Comment by ConnorLinfoot** [comment]
Fixed in V4.0
