### ISSUE TITLE
Command & Item

### ISSUE THREAD

**Issue by dustin1525** [ConnorLinfoot/CratesPlus#95]
This code does the command, AND gives the gold ingot to them, I was wondering how to make it only do the command.

`      '4':
        Type: COMMAND
        Item Type: GOLD_INGOT
        Percentage: 50
        Commands:
        - 'money give %name% 100'
        Name: '&a&l$100'
        Item Data: 0
        Amount: 1`

**Comment by ItsWulff** [comment]
Just leaving a comment here for the answer :)

**Comment by ConnorLinfoot** [comment]
This was a bug, it's fixed in 4.0
