### ISSUE TITLE
Players can take out the glass, and possible winnings

### ISSUE THREAD

**Issue by BunnyTadPole** [ConnorLinfoot/CratesPlus#96]
Hi! First of all, great plugin, But i've noticed, that in the latest version, players are able to take out the possible winnings, and the colored glass, before and after your prize is shown. What can I do to prevent this?

**Comment by BunnyTadPole** [comment]
Never mind! I fixed this!

**Comment by GreenBaii** [comment]
Hi BunnyTadPole how did you do this?

**Comment by GreenBaii** [comment]
How did you do it?

**Comment by BunnyTadPole** [comment]
I downloaded a pre-alpha jar or something.

**Comment by ConnorLinfoot** [comment]
This issue has been fixed, it was caused by using CraftBukkit.

You can now use version 3.1.6 or above and it should be fixed; https://www.spigotmc.org/resources/cratesplus-custom-crates-1-8-1-9-free.5018/download?version=72888
