### ISSUE TITLE
Crates Preview

### ISSUE THREAD

**Issue by GreenBaii** [ConnorLinfoot/CratesPlus#97]
Hi my users on the server can preview whats in the crate and take it, and keep doing it and doing it is there a way to stop it?

**Comment by GreenBaii** [comment]
On the newest version

**Comment by ConnorLinfoot** [comment]
Issue is caused by conflicting plugins/invalid configuration. Not an issue with the plugin.

**Comment by GreenBaii** [comment]
CratesPlus, PurchaseCommands, AntiSwear, GroupManager, ChopTree2, MotdManager, CustomServerMessages, MaxBans, Vault, PlayerVaults, HolographicDisplays, MyCommand, mcMMO, Essentials, Banknotes, TitleManager, EssentialsChat
There the plugins i have which on possibly would it be
